; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=amdgcn -mcpu=gfx906 < %s | FileCheck -check-prefixes=GCN %s


declare <4 x float> @llvm.amdgcn.image.gather4.2d.v4f32.f32(i32, float, float, <8 x i32>, <4 x i32>, i1, i32, i32)


define amdgpu_ps <4 x float> @water_loop_rsrc(<8 x i32> %rsrc, <4 x i32> inreg %samp, float %s, float %t) {
; GCN-LABEL: water_loop_rsrc:
; GCN:       ; %bb.0: ; %main_body
; GCN-NEXT:    s_mov_b64 s[16:17], exec
; GCN-NEXT:    s_wqm_b64 exec, exec
; GCN-NEXT:    v_mov_b32_e32 v13, v9
; GCN-NEXT:    v_mov_b32_e32 v12, v8
; GCN-NEXT:    s_mov_b32 s15, s3
; GCN-NEXT:    s_mov_b32 s14, s2
; GCN-NEXT:    s_mov_b32 s13, s1
; GCN-NEXT:    s_mov_b32 s12, s0
; GCN-NEXT:    s_mov_b64 s[2:3], exec
; GCN-NEXT:  .LBB0_1: ; =>This Inner Loop Header: Depth=1
; GCN-NEXT:    v_readfirstlane_b32 s4, v0
; GCN-NEXT:    v_readfirstlane_b32 s5, v1
; GCN-NEXT:    v_readfirstlane_b32 s6, v2
; GCN-NEXT:    v_readfirstlane_b32 s7, v3
; GCN-NEXT:    v_cmp_eq_u64_e32 vcc, s[4:5], v[0:1]
; GCN-NEXT:    v_cmp_eq_u64_e64 s[0:1], s[6:7], v[2:3]
; GCN-NEXT:    v_readfirstlane_b32 s8, v4
; GCN-NEXT:    v_readfirstlane_b32 s9, v5
; GCN-NEXT:    s_and_b64 s[18:19], vcc, s[0:1]
; GCN-NEXT:    v_cmp_eq_u64_e32 vcc, s[8:9], v[4:5]
; GCN-NEXT:    v_readfirstlane_b32 s10, v6
; GCN-NEXT:    v_readfirstlane_b32 s11, v7
; GCN-NEXT:    v_cmp_eq_u64_e64 s[0:1], s[10:11], v[6:7]
; GCN-NEXT:    s_and_b64 s[18:19], s[18:19], vcc
; GCN-NEXT:    s_and_b64 s[0:1], s[18:19], s[0:1]
; GCN-NEXT:    s_and_saveexec_b64 s[0:1], s[0:1]
; GCN-NEXT:    s_nop 0
; GCN-NEXT:    image_gather4 v[8:11], v[12:13], s[4:11], s[12:15] dmask:0x1
; GCN-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GCN-NEXT:    ; implicit-def: $vgpr12_vgpr13
; GCN-NEXT:    s_xor_b64 exec, exec, s[0:1]
; GCN-NEXT:    s_cbranch_execnz .LBB0_1
; GCN-NEXT:  ; %bb.2:
; GCN-NEXT:    s_mov_b64 exec, s[2:3]
; GCN-NEXT:    s_and_b64 exec, exec, s[16:17]
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    v_mov_b32_e32 v0, v8
; GCN-NEXT:    v_mov_b32_e32 v1, v9
; GCN-NEXT:    v_mov_b32_e32 v2, v10
; GCN-NEXT:    v_mov_b32_e32 v3, v11
; GCN-NEXT:    ; return to shader part epilog
main_body:
  %v = call <4 x float> @llvm.amdgcn.image.gather4.2d.v4f32.f32(i32 1, float %s, float %t, <8 x i32> %rsrc, <4 x i32> %samp, i1 0, i32 0, i32 0)
  ret <4 x float> %v
}





define amdgpu_ps <4 x float> @water_loop_samp(<8 x i32> inreg %rsrc, <4 x i32> %samp, float %s, float %t) {
; GCN-LABEL: water_loop_samp:
; GCN:       ; %bb.0: ; %main_body
; GCN-NEXT:    s_mov_b64 s[16:17], exec
; GCN-NEXT:    s_wqm_b64 exec, exec
; GCN-NEXT:    v_mov_b32_e32 v9, v5
; GCN-NEXT:    v_mov_b32_e32 v8, v4
; GCN-NEXT:    s_mov_b32 s11, s7
; GCN-NEXT:    s_mov_b32 s10, s6
; GCN-NEXT:    s_mov_b32 s9, s5
; GCN-NEXT:    s_mov_b32 s8, s4
; GCN-NEXT:    s_mov_b32 s7, s3
; GCN-NEXT:    s_mov_b32 s6, s2
; GCN-NEXT:    s_mov_b32 s5, s1
; GCN-NEXT:    s_mov_b32 s4, s0
; GCN-NEXT:    s_mov_b64 s[2:3], exec
; GCN-NEXT:  .LBB1_1: ; =>This Inner Loop Header: Depth=1
; GCN-NEXT:    v_readfirstlane_b32 s12, v0
; GCN-NEXT:    v_readfirstlane_b32 s13, v1
; GCN-NEXT:    v_readfirstlane_b32 s14, v2
; GCN-NEXT:    v_readfirstlane_b32 s15, v3
; GCN-NEXT:    v_cmp_eq_u64_e32 vcc, s[12:13], v[0:1]
; GCN-NEXT:    v_cmp_eq_u64_e64 s[0:1], s[14:15], v[2:3]
; GCN-NEXT:    s_and_b64 s[0:1], vcc, s[0:1]
; GCN-NEXT:    s_and_saveexec_b64 s[0:1], s[0:1]
; GCN-NEXT:    s_nop 0
; GCN-NEXT:    image_gather4 v[4:7], v[8:9], s[4:11], s[12:15] dmask:0x1
; GCN-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3
; GCN-NEXT:    ; implicit-def: $vgpr8_vgpr9
; GCN-NEXT:    s_xor_b64 exec, exec, s[0:1]
; GCN-NEXT:    s_cbranch_execnz .LBB1_1
; GCN-NEXT:  ; %bb.2:
; GCN-NEXT:    s_mov_b64 exec, s[2:3]
; GCN-NEXT:    s_and_b64 exec, exec, s[16:17]
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    v_mov_b32_e32 v0, v4
; GCN-NEXT:    v_mov_b32_e32 v1, v5
; GCN-NEXT:    v_mov_b32_e32 v2, v6
; GCN-NEXT:    v_mov_b32_e32 v3, v7
; GCN-NEXT:    ; return to shader part epilog
main_body:
  %v = call <4 x float> @llvm.amdgcn.image.gather4.2d.v4f32.f32(i32 1, float %s, float %t, <8 x i32> %rsrc, <4 x i32> %samp, i1 0, i32 0, i32 0)
  ret <4 x float> %v
}
