; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; Test sibling calls.
;
; RUN: llc < %s -mtriple=s390x-linux-gnu | FileCheck %s

declare void @ok(i8 %r2, i16 %r3, i32 %r4, i64 %r5, float %f0, double %f2,
                 float %f4, double %f6)
declare void @uses_r6(i8 %r2, i16 %r3, i32 %r4, i64 %r5, i64 %r6)
declare void @uses_indirect(fp128 %r2)
declare void @uses_stack(float %f0, float %f2, float %f4, float %f6,
                         float %stack)
declare i32 @returns_i32()
declare i64 @returns_i64()

; Check the maximum number of arguments that we can pass and still use
; a sibling call.
define void @f1() {
; CHECK-LABEL: f1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lzer %f4
; CHECK-NEXT:    lzdr %f6
; CHECK-NEXT:    lhi %r2, 1
; CHECK-NEXT:    lhi %r3, 2
; CHECK-NEXT:    lhi %r4, 3
; CHECK-NEXT:    lghi %r5, 4
; CHECK-NEXT:    ler %f0, %f4
; CHECK-NEXT:    ldr %f2, %f6
; CHECK-NEXT:    jg ok@PLT
  tail call void @ok(i8 1, i16 2, i32 3, i64 4, float 0.0, double 0.0,
                     float 0.0, double 0.0)
  ret void
}

; Check a call that uses %r6 to pass an argument.  At the moment we don't
; use sibling calls in that case.
define void @f2() {
; CHECK-LABEL: f2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r6, %r15, 48(%r15)
; CHECK-NEXT:    .cfi_offset %r6, -112
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    lhi %r2, 1
; CHECK-NEXT:    lhi %r3, 2
; CHECK-NEXT:    lhi %r4, 3
; CHECK-NEXT:    lghi %r5, 4
; CHECK-NEXT:    lghi %r6, 5
; CHECK-NEXT:    brasl %r14, uses_r6@PLT
; CHECK-NEXT:    lmg %r6, %r15, 208(%r15)
; CHECK-NEXT:    br %r14
  tail call void @uses_r6(i8 1, i16 2, i32 3, i64 4, i64 5)
  ret void
}

; Check a call that passes indirect arguments.  We can't use sibling
; calls in that case.
define void @f3() {
; CHECK-LABEL: f3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -176
; CHECK-NEXT:    .cfi_def_cfa_offset 336
; CHECK-NEXT:    lzxr %f0
; CHECK-NEXT:    la %r2, 160(%r15)
; CHECK-NEXT:    std %f0, 160(%r15)
; CHECK-NEXT:    std %f2, 168(%r15)
; CHECK-NEXT:    brasl %r14, uses_indirect@PLT
; CHECK-NEXT:    lmg %r14, %r15, 288(%r15)
; CHECK-NEXT:    br %r14
  tail call void @uses_indirect(fp128 0xL00000000000000000000000000000000)
  ret void
}

; Check a call that uses direct stack arguments, which again prevents
; sibling calls
define void @f4() {
; CHECK-LABEL: f4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -168
; CHECK-NEXT:    .cfi_def_cfa_offset 328
; CHECK-NEXT:    lzer %f6
; CHECK-NEXT:    mvhi 164(%r15), 0
; CHECK-NEXT:    ler %f0, %f6
; CHECK-NEXT:    ler %f2, %f6
; CHECK-NEXT:    ler %f4, %f6
; CHECK-NEXT:    brasl %r14, uses_stack@PLT
; CHECK-NEXT:    lmg %r14, %r15, 280(%r15)
; CHECK-NEXT:    br %r14
  tail call void @uses_stack(float 0.0, float 0.0, float 0.0, float 0.0,
                             float 0.0)
  ret void
}

; Check an indirect call.  In this case the only acceptable choice for
; the target register is %r1.
define void @f5(ptr %foo) {
; CHECK-LABEL: f5:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lgr %r1, %r2
; CHECK-NEXT:    lhi %r2, 1
; CHECK-NEXT:    lhi %r3, 2
; CHECK-NEXT:    lhi %r4, 3
; CHECK-NEXT:    lhi %r5, 4
; CHECK-NEXT:    br %r1
  tail call void %foo(i32 1, i32 2, i32 3, i32 4)
  ret void
}

; Check an indirect call that will be forced into a call-saved GPR
; (which should be %r13, the highest GPR not used for anything else).
define void @f6(ptr %foo) {
; CHECK-LABEL: f6:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r13, %r15, 104(%r15)
; CHECK-NEXT:    .cfi_offset %r13, -56
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    lgr %r13, %r2
; CHECK-NEXT:    brasl %r14, returns_i32@PLT
; CHECK-NEXT:    lgr %r1, %r13
; CHECK-NEXT:    lmg %r13, %r15, 264(%r15)
; CHECK-NEXT:    br %r1
  %arg = call i32 @returns_i32()
  tail call void %foo(i32 %arg)
  ret void
}

; Test a function that returns a value.
define i64 @f7() {
; CHECK-LABEL: f7:
; CHECK:       # %bb.0:
; CHECK-NEXT:    jg returns_i64@PLT
  %res = tail call i64 @returns_i64()
  ret i64 %res
}

; Test a function that returns a value truncated from i64 to i32.
define i32 @f8() {
; CHECK-LABEL: f8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    jg returns_i64@PLT
  %res = tail call i64 @returns_i64()
  %trunc = trunc i64 %res to i32
  ret i32 %trunc
}

; Test a function that returns a value truncated from i64 to i7.
define i7 @f9() {
; CHECK-LABEL: f9:
; CHECK:       # %bb.0:
; CHECK-NEXT:    jg returns_i64@PLT
  %res = tail call i64 @returns_i64()
  %trunc = trunc i64 %res to i7
  ret i7 %trunc
}

; Test a function that returns a value truncated from i32 to i8.
define i8 @f10() {
; CHECK-LABEL: f10:
; CHECK:       # %bb.0:
; CHECK-NEXT:    jg returns_i32@PLT
  %res = tail call i32 @returns_i32()
  %trunc = trunc i32 %res to i8
  ret i8 %trunc
}
