; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; Verify that floating-point strict signaling compares cannot be omitted
; even if CC already has the right value.
;
; RUN: llc < %s -mtriple=s390x-linux-gnu -mcpu=z10 \
; RUN:   -enable-misched=0 -no-integrated-as | FileCheck %s
;
; We need -enable-misched=0 to make sure f12 and following routines really
; test the compare elimination pass.


declare float @llvm.fabs.f32(float %f)

; Test addition followed by EQ, which could use the CC result of the addition.
define float @f1(float %a, float %b, ptr %dest) #0 {
; CHECK-LABEL: f1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    aebr %f0, %f2
; CHECK-NEXT:    lzer %f1
; CHECK-NEXT:    kebr %f0, %f1
; CHECK-NEXT:    ber %r14
; CHECK-NEXT:  .LBB0_1: # %store
; CHECK-NEXT:    ste %f2, 0(%r2)
; CHECK-NEXT:    br %r14
entry:
  %res = call float @llvm.experimental.constrained.fadd.f32(
                        float %a, float %b,
                        metadata !"round.dynamic",
                        metadata !"fpexcept.strict") #0
  %cmp = call i1 @llvm.experimental.constrained.fcmps.f32(
                                               float %res, float 0.0,
                                               metadata !"oeq",
                                               metadata !"fpexcept.strict") #0
  br i1 %cmp, label %exit, label %store

store:
  store float %b, ptr %dest
  br label %exit

exit:
  ret float %res
}

; Test the result of LOAD POSITIVE.
define float @f6(float %dummy, float %a, ptr %dest) #0 {
; CHECK-LABEL: f6:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lpdfr %f0, %f2
; CHECK-NEXT:    lzer %f1
; CHECK-NEXT:    kebr %f0, %f1
; CHECK-NEXT:    bhr %r14
; CHECK-NEXT:  .LBB1_1: # %store
; CHECK-NEXT:    ste %f0, 0(%r2)
; CHECK-NEXT:    br %r14
entry:
  %res = call float @llvm.fabs.f32(float %a) #0
  %cmp = call i1 @llvm.experimental.constrained.fcmps.f32(
                                               float %res, float 0.0,
                                               metadata !"ogt",
                                               metadata !"fpexcept.strict") #0
  br i1 %cmp, label %exit, label %store

store:
  store float %res, ptr %dest
  br label %exit

exit:
  ret float %res
}

; Test the result of LOAD NEGATIVE.
define float @f7(float %dummy, float %a, ptr %dest) #0 {
; CHECK-LABEL: f7:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lndfr %f0, %f2
; CHECK-NEXT:    lzer %f1
; CHECK-NEXT:    kebr %f0, %f1
; CHECK-NEXT:    blr %r14
; CHECK-NEXT:  .LBB2_1: # %store
; CHECK-NEXT:    ste %f0, 0(%r2)
; CHECK-NEXT:    br %r14
entry:
  %abs = call float @llvm.fabs.f32(float %a) #0
  %res = fneg float %abs
  %cmp = call i1 @llvm.experimental.constrained.fcmps.f32(
                                               float %res, float 0.0,
                                               metadata !"olt",
                                               metadata !"fpexcept.strict") #0
  br i1 %cmp, label %exit, label %store

store:
  store float %res, ptr %dest
  br label %exit

exit:
  ret float %res
}

; Test the result of LOAD COMPLEMENT.
define float @f8(float %dummy, float %a, ptr %dest) #0 {
; CHECK-LABEL: f8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lcdfr %f0, %f2
; CHECK-NEXT:    lzer %f1
; CHECK-NEXT:    kebr %f0, %f1
; CHECK-NEXT:    bler %r14
; CHECK-NEXT:  .LBB3_1: # %store
; CHECK-NEXT:    ste %f0, 0(%r2)
; CHECK-NEXT:    br %r14
entry:
  %res = fneg float %a
  %cmp = call i1 @llvm.experimental.constrained.fcmps.f32(
                                               float %res, float 0.0,
                                               metadata !"ole",
                                               metadata !"fpexcept.strict") #0
  br i1 %cmp, label %exit, label %store

store:
  store float %res, ptr %dest
  br label %exit

exit:
  ret float %res
}

define half @f12_half(half %dummy, half %val) #0 {
; CHECK-LABEL: f12_half:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -184
; CHECK-NEXT:    .cfi_def_cfa_offset 344
; CHECK-NEXT:    std %f8, 176(%r15) # 8-byte Spill
; CHECK-NEXT:    std %f9, 168(%r15) # 8-byte Spill
; CHECK-NEXT:    std %f10, 160(%r15) # 8-byte Spill
; CHECK-NEXT:    .cfi_offset %f8, -168
; CHECK-NEXT:    .cfi_offset %f9, -176
; CHECK-NEXT:    .cfi_offset %f10, -184
; CHECK-NEXT:    ler %f8, %f2
; CHECK-NEXT:    ler %f0, %f2
; CHECK-NEXT:    #APP
; CHECK-NEXT:    ler %f9, %f0
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    lzer %f0
; CHECK-NEXT:    brasl %r14, __extendhfsf2@PLT
; CHECK-NEXT:    ler %f10, %f0
; CHECK-NEXT:    ler %f0, %f8
; CHECK-NEXT:    brasl %r14, __extendhfsf2@PLT
; CHECK-NEXT:    kebr %f0, %f10
; CHECK-NEXT:    jl .LBB4_2
; CHECK-NEXT:  # %bb.1: # %store
; CHECK-NEXT:    #APP
; CHECK-NEXT:    blah
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:  .LBB4_2: # %exit
; CHECK-NEXT:    ler %f0, %f9
; CHECK-NEXT:    ld %f8, 176(%r15) # 8-byte Reload
; CHECK-NEXT:    ld %f9, 168(%r15) # 8-byte Reload
; CHECK-NEXT:    ld %f10, 160(%r15) # 8-byte Reload
; CHECK-NEXT:    lmg %r14, %r15, 296(%r15)
; CHECK-NEXT:    br %r14
entry:
  %ret = call half asm "ler $0, $1", "=f,{f0}"(half %val) #0
  %cmp = call i1 @llvm.experimental.constrained.fcmps.f16(
                                               half %val, half 0.0,
                                               metadata !"olt",
                                               metadata !"fpexcept.strict") #0
  br i1 %cmp, label %exit, label %store

store:
  call void asm sideeffect "blah", ""() #0
  br label %exit

exit:
  ret half %ret
}

; Test that LER does not get converted to LTEBR.
define float @f12(float %dummy, float %val) #0 {
; CHECK-LABEL: f12:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ler %f0, %f2
; CHECK-NEXT:    #APP
; CHECK-NEXT:    blah %f0
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    lzer %f1
; CHECK-NEXT:    kebr %f2, %f1
; CHECK-NEXT:    blr %r14
; CHECK-NEXT:  .LBB5_1: # %store
; CHECK-NEXT:    #APP
; CHECK-NEXT:    blah
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    br %r14
entry:
  %ret = call float asm "blah $1", "=f,{f0}"(float %val) #0
  %cmp = call i1 @llvm.experimental.constrained.fcmps.f32(
                                               float %val, float 0.0,
                                               metadata !"olt",
                                               metadata !"fpexcept.strict") #0
  br i1 %cmp, label %exit, label %store

store:
  call void asm sideeffect "blah", ""() #0
  br label %exit

exit:
  ret float %ret
}

attributes #0 = { strictfp }

declare float @llvm.experimental.constrained.fadd.f32(float, float, metadata, metadata)
declare float @llvm.experimental.constrained.fsub.f32(float, float, metadata, metadata)
declare float @llvm.experimental.constrained.fmul.f32(float, float, metadata, metadata)
declare float @llvm.experimental.constrained.fdiv.f32(float, float, metadata, metadata)
declare i1 @llvm.experimental.constrained.fcmps.f32(float, float, metadata, metadata)
declare i1 @llvm.experimental.constrained.fcmps.f64(double, double, metadata, metadata)
declare i1 @llvm.experimental.constrained.fcmps.f128(fp128, fp128, metadata, metadata)
