; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=armv7-linux-gnueabi -verify-machineinstrs < %s | FileCheck %s --check-prefix=ASM
; RUN: llc -mtriple=armv7-linux-gnueabi -verify-machineinstrs -stop-after=finalize-isel < %s | FileCheck %s --check-prefix=ISEL
; RUN: llc -mtriple=armv7-linux-gnueabi -verify-machineinstrs -stop-after=kcfi < %s | FileCheck %s --check-prefix=KCFI

; MIR checks for all functions (grouped here to prevent update_llc_test_checks.py from removing them)







define void @f1(ptr noundef %x) !kcfi_type !1 {
; ASM-LABEL: f1:
; ASM:       @ %bb.0:
; ASM-NEXT:    .save {r11, lr}
; ASM-NEXT:    push {r11, lr}
; ASM-NEXT:    bic r12, r0, #1
; ASM-NEXT:    ldr r12, [r12, #-4]
; ASM-NEXT:    eor r12, r12, #78
; ASM-NEXT:    eor r12, r12, #24832
; ASM-NEXT:    eor r12, r12, #12320768
; ASM-NEXT:    eors r12, r12, #0
; ASM-NEXT:    beq .Ltmp0
; ASM-NEXT:    udf #33760
; ASM-NEXT:  .Ltmp0:
; ASM-NEXT:    blx r0
; ASM-NEXT:    pop {r11, pc}
; ISEL-LABEL: name: f1
; ISEL: bb.0 (%ir-block.0):
; ISEL-NEXT:   liveins: $r0
; ISEL-NEXT: {{  $}}
; ISEL-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $r0
; ISEL-NEXT:   ADJCALLSTACKDOWN 0, 0, 14 /* CC::al */, $noreg, implicit-def dead $sp, implicit $sp
; ISEL-NEXT:   BLX [[COPY]], csr_aapcs, implicit-def dead $lr, implicit $sp, implicit-def $sp, cfi-type 12345678
; ISEL-NEXT:   ADJCALLSTACKUP 0, -1, 14 /* CC::al */, $noreg, implicit-def dead $sp, implicit $sp
; ISEL-NEXT:   BX_RET 14 /* CC::al */, $noreg
;
; KCFI-LABEL: name: f1
; KCFI: bb.0 (%ir-block.0):
; KCFI-NEXT:   liveins: $r0, $r11, $lr
; KCFI-NEXT: {{  $}}
; KCFI-NEXT:   $sp = frame-setup STMDB_UPD $sp, 14 /* CC::al */, $noreg, killed $r11, killed $lr
; KCFI-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 8
; KCFI-NEXT:   frame-setup CFI_INSTRUCTION offset $lr, -4
; KCFI-NEXT:   frame-setup CFI_INSTRUCTION offset $r11, -8
; KCFI-NEXT:   BUNDLE implicit-def dead $lr, implicit-def $sp, implicit killed $r0, implicit $sp {
; KCFI-NEXT:     KCFI_CHECK_ARM $r0, 12345678
; KCFI-NEXT:     BLX killed $r0, csr_aapcs, implicit-def dead $lr, implicit $sp, implicit-def $sp
; KCFI-NEXT:   }
; KCFI-NEXT:   $sp = frame-destroy LDMIA_RET $sp, 14 /* CC::al */, $noreg, def $r11, def $pc

  call void %x() [ "kcfi"(i32 12345678) ]
  ret void
}

; Test with tail call
define void @f2(ptr noundef %x) !kcfi_type !1 {
; ASM-LABEL: f2:
; ASM:       @ %bb.0:
; ASM-NEXT:    bic r12, r0, #1
; ASM-NEXT:    ldr r12, [r12, #-4]
; ASM-NEXT:    eor r12, r12, #78
; ASM-NEXT:    eor r12, r12, #24832
; ASM-NEXT:    eor r12, r12, #12320768
; ASM-NEXT:    eors r12, r12, #0
; ASM-NEXT:    beq .Ltmp1
; ASM-NEXT:    udf #33760
; ASM-NEXT:  .Ltmp1:
; ASM-NEXT:    bx r0
; ISEL-LABEL: name: f2
; ISEL: bb.0 (%ir-block.0):
; ISEL-NEXT:   liveins: $r0
; ISEL-NEXT: {{  $}}
; ISEL-NEXT:   [[COPY:%[0-9]+]]:tcgpr = COPY $r0
; ISEL-NEXT:   TCRETURNri [[COPY]], 0, csr_aapcs, implicit $sp, cfi-type 12345678
;
; KCFI-LABEL: name: f2
; KCFI: bb.0 (%ir-block.0):
; KCFI-NEXT:   liveins: $r0
; KCFI-NEXT: {{  $}}
; KCFI-NEXT:   BUNDLE implicit killed $r0, implicit $sp {
; KCFI-NEXT:     KCFI_CHECK_ARM $r0, 12345678
; KCFI-NEXT:     TAILJMPr killed $r0, csr_aapcs, implicit $sp, implicit $sp
; KCFI-NEXT:   }

  tail call void %x() [ "kcfi"(i32 12345678) ]
  ret void
}

; Test r3 spill/reload when target is r12 and r3 is a call argument.
; With 5+ arguments (target + 4 args), r0-r3 are all used for arguments,
; forcing r3 to be spilled when we need it as scratch register.
define void @f3_r3_spill(ptr noundef %target, i32 %a, i32 %b, i32 %c, i32 %d) !kcfi_type !1 {
; ASM-LABEL: f3_r3_spill:
; ASM:       @ %bb.0:
; ASM-NEXT:    .save {r11, lr}
; ASM-NEXT:    push {r11, lr}
; ASM-NEXT:    ldr r12, [sp, #8]
; ASM-NEXT:    mov lr, r0
; ASM-NEXT:    mov r0, r1
; ASM-NEXT:    mov r1, r2
; ASM-NEXT:    mov r2, r3
; ASM-NEXT:    mov r3, r12
; ASM-NEXT:    bic r12, lr, #1
; ASM-NEXT:    ldr r12, [r12, #-4]
; ASM-NEXT:    eor r12, r12, #78
; ASM-NEXT:    eor r12, r12, #24832
; ASM-NEXT:    eor r12, r12, #12320768
; ASM-NEXT:    eors r12, r12, #0
; ASM-NEXT:    beq .Ltmp2
; ASM-NEXT:    udf #33774
; ASM-NEXT:  .Ltmp2:
; ASM-NEXT:    blx lr
; ASM-NEXT:    pop {r11, pc}
; ISEL-LABEL: name: f3_r3_spill
; ISEL: bb.0 (%ir-block.0):
; ISEL-NEXT:   liveins: $r0, $r1, $r2, $r3
; ISEL-NEXT: {{  $}}
; ISEL-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $r3
; ISEL-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $r2
; ISEL-NEXT:   [[COPY2:%[0-9]+]]:gpr = COPY $r1
; ISEL-NEXT:   [[COPY3:%[0-9]+]]:gpr = COPY $r0
; ISEL-NEXT:   [[LDRi12_:%[0-9]+]]:gpr = LDRi12 %fixed-stack.0, 0, 14 /* CC::al */, $noreg :: (load (s32) from %fixed-stack.0, align 8)
; ISEL-NEXT:   ADJCALLSTACKDOWN 0, 0, 14 /* CC::al */, $noreg, implicit-def dead $sp, implicit $sp
; ISEL-NEXT:   $r0 = COPY [[COPY2]]
; ISEL-NEXT:   $r1 = COPY [[COPY1]]
; ISEL-NEXT:   $r2 = COPY [[COPY]]
; ISEL-NEXT:   $r3 = COPY [[LDRi12_]]
; ISEL-NEXT:   BLX [[COPY3]], csr_aapcs, implicit-def dead $lr, implicit $sp, implicit $r0, implicit $r1, implicit $r2, implicit $r3, implicit-def $sp, cfi-type 12345678
; ISEL-NEXT:   ADJCALLSTACKUP 0, -1, 14 /* CC::al */, $noreg, implicit-def dead $sp, implicit $sp
; ISEL-NEXT:   BX_RET 14 /* CC::al */, $noreg
;
; KCFI-LABEL: name: f3_r3_spill
; KCFI: bb.0 (%ir-block.0):
; KCFI-NEXT:   liveins: $r0, $r1, $r2, $r3, $r11, $lr
; KCFI-NEXT: {{  $}}
; KCFI-NEXT:   $sp = frame-setup STMDB_UPD $sp, 14 /* CC::al */, $noreg, killed $r11, killed $lr
; KCFI-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 8
; KCFI-NEXT:   frame-setup CFI_INSTRUCTION offset $lr, -4
; KCFI-NEXT:   frame-setup CFI_INSTRUCTION offset $r11, -8
; KCFI-NEXT:   $lr = MOVr $r0, 14 /* CC::al */, $noreg, $noreg
; KCFI-NEXT:   renamable $r12 = LDRi12 $sp, 8, 14 /* CC::al */, $noreg :: (load (s32) from %fixed-stack.0, align 8)
; KCFI-NEXT:   $r0 = MOVr killed $r1, 14 /* CC::al */, $noreg, $noreg
; KCFI-NEXT:   $r1 = MOVr killed $r2, 14 /* CC::al */, $noreg, $noreg
; KCFI-NEXT:   $r2 = MOVr killed $r3, 14 /* CC::al */, $noreg, $noreg
; KCFI-NEXT:   $r3 = MOVr killed $r12, 14 /* CC::al */, $noreg, $noreg
; KCFI-NEXT:   BUNDLE implicit-def dead $lr, implicit-def $sp, implicit killed $lr, implicit $sp, implicit $r0, implicit $r1, implicit $r2, implicit $r3 {
; KCFI-NEXT:     KCFI_CHECK_ARM $lr, 12345678
; KCFI-NEXT:     BLX killed $lr, csr_aapcs, implicit-def dead $lr, implicit $sp, implicit $r0, implicit $r1, implicit $r2, implicit $r3, implicit-def $sp
; KCFI-NEXT:   }
; KCFI-NEXT:   $sp = frame-destroy LDMIA_RET $sp, 14 /* CC::al */, $noreg, def $r11, def $pc
; Arguments: r0=%target, r1=%a, r2=%b, r3=%c, [sp]=%d
; Call needs: r0=%a, r1=%b, r2=%c, r3=%d, target in r12
; Compiler shuffles arguments into place, saving r3 (c) in lr, loading d from stack
; r3 is live as 4th argument, so push it before KCFI check
; Restore r3 immediately after comparison, before branch
  call void %target(i32 %a, i32 %b, i32 %c, i32 %d) [ "kcfi"(i32 12345678) ]
  ret void
}

; Test with 3 arguments - r3 not live, target in r12, so r3 used as scratch without spilling
define void @f4_r3_unused(ptr noundef %target, i32 %a, i32 %b) !kcfi_type !1 {
; ASM-LABEL: f4_r3_unused:
; ASM:       @ %bb.0:
; ASM-NEXT:    .save {r11, lr}
; ASM-NEXT:    push {r11, lr}
; ASM-NEXT:    mov r3, r0
; ASM-NEXT:    mov r0, r1
; ASM-NEXT:    mov r1, r2
; ASM-NEXT:    bic r12, r3, #1
; ASM-NEXT:    ldr r12, [r12, #-4]
; ASM-NEXT:    eor r12, r12, #78
; ASM-NEXT:    eor r12, r12, #24832
; ASM-NEXT:    eor r12, r12, #12320768
; ASM-NEXT:    eors r12, r12, #0
; ASM-NEXT:    beq .Ltmp3
; ASM-NEXT:    udf #33763
; ASM-NEXT:  .Ltmp3:
; ASM-NEXT:    blx r3
; ASM-NEXT:    pop {r11, pc}
; ISEL-LABEL: name: f4_r3_unused
; ISEL: bb.0 (%ir-block.0):
; ISEL-NEXT:   liveins: $r0, $r1, $r2
; ISEL-NEXT: {{  $}}
; ISEL-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $r2
; ISEL-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $r1
; ISEL-NEXT:   [[COPY2:%[0-9]+]]:gpr = COPY $r0
; ISEL-NEXT:   ADJCALLSTACKDOWN 0, 0, 14 /* CC::al */, $noreg, implicit-def dead $sp, implicit $sp
; ISEL-NEXT:   $r0 = COPY [[COPY1]]
; ISEL-NEXT:   $r1 = COPY [[COPY]]
; ISEL-NEXT:   BLX [[COPY2]], csr_aapcs, implicit-def dead $lr, implicit $sp, implicit $r0, implicit $r1, implicit-def $sp, cfi-type 12345678
; ISEL-NEXT:   ADJCALLSTACKUP 0, -1, 14 /* CC::al */, $noreg, implicit-def dead $sp, implicit $sp
; ISEL-NEXT:   BX_RET 14 /* CC::al */, $noreg
;
; KCFI-LABEL: name: f4_r3_unused
; KCFI: bb.0 (%ir-block.0):
; KCFI-NEXT:   liveins: $r0, $r1, $r2, $r11, $lr
; KCFI-NEXT: {{  $}}
; KCFI-NEXT:   $sp = frame-setup STMDB_UPD $sp, 14 /* CC::al */, $noreg, killed $r11, killed $lr
; KCFI-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 8
; KCFI-NEXT:   frame-setup CFI_INSTRUCTION offset $lr, -4
; KCFI-NEXT:   frame-setup CFI_INSTRUCTION offset $r11, -8
; KCFI-NEXT:   $r3 = MOVr $r0, 14 /* CC::al */, $noreg, $noreg
; KCFI-NEXT:   $r0 = MOVr killed $r1, 14 /* CC::al */, $noreg, $noreg
; KCFI-NEXT:   $r1 = MOVr killed $r2, 14 /* CC::al */, $noreg, $noreg
; KCFI-NEXT:   BUNDLE implicit-def dead $lr, implicit-def $sp, implicit killed $r3, implicit $sp, implicit $r0, implicit $r1 {
; KCFI-NEXT:     KCFI_CHECK_ARM $r3, 12345678
; KCFI-NEXT:     BLX killed $r3, csr_aapcs, implicit-def dead $lr, implicit $sp, implicit $r0, implicit $r1, implicit-def $sp
; KCFI-NEXT:   }
; KCFI-NEXT:   $sp = frame-destroy LDMIA_RET $sp, 14 /* CC::al */, $noreg, def $r11, def $pc
; Only 3 arguments total, so r3 is not used as call argument
; Compiler puts target→r3, a→r0, b→r1
; r3 is the target, so we use r12 as scratch (no spill needed)
  call void %target(i32 %a, i32 %b) [ "kcfi"(i32 12345678) ]
  ret void
}

!llvm.module.flags = !{!0}
!0 = !{i32 4, !"kcfi", i32 1}
!1 = !{i32 12345678}
