; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=thumbv6m-none-eabi | FileCheck %s

define i1 @unsigned_multiplication_did_overflow(i32, i32) {
; CHECK-LABEL: unsigned_multiplication_did_overflow:
; CHECK:       @ %bb.0: @ %entry-block
; CHECK-NEXT:    .save {r7, lr}
; CHECK-NEXT:    push {r7, lr}
; CHECK-NEXT:    mov r2, r1
; CHECK-NEXT:    movs r3, #0
; CHECK-NEXT:    mov r1, r3
; CHECK-NEXT:    bl __aeabi_lmul
; CHECK-NEXT:    mov r0, r1
; CHECK-NEXT:    subs r1, r1, #1
; CHECK-NEXT:    sbcs r0, r1
; CHECK-NEXT:    pop {r7, pc}
entry-block:
  %2 = tail call { i32, i1 } @llvm.umul.with.overflow.i32(i32 %0, i32 %1)
  %3 = extractvalue { i32, i1 } %2, 1
  ret i1 %3

}

declare { i32, i1 } @llvm.umul.with.overflow.i32(i32, i32)
