; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-unknown -mattr=+egpr | FileCheck %s --check-prefix=EGPR
; RUN: llc < %s -mtriple=x86_64-unknown -mattr=+egpr,+ndd,+prefer-ndd-imm,+prefer-ndd-mem | FileCheck %s --check-prefix=EGPR-NDD

define void @test_1024(ptr %a, ptr %b, ptr %out) nounwind {
; EGPR-LABEL: test_1024:
; EGPR:       # %bb.0:
; EGPR-NEXT:    pushq %rbp
; EGPR-NEXT:    pushq %r15
; EGPR-NEXT:    pushq %r14
; EGPR-NEXT:    pushq %r13
; EGPR-NEXT:    pushq %r12
; EGPR-NEXT:    pushq %rbx
; EGPR-NEXT:    subq $112, %rsp
; EGPR-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NEXT:    movq %rdi, %r18
; EGPR-NEXT:    movq (%rdi), %r17
; EGPR-NEXT:    movq 8(%rdi), %r13
; EGPR-NEXT:    movq 24(%rdi), %r14
; EGPR-NEXT:    movq 16(%rdi), %r27
; EGPR-NEXT:    movq 40(%rdi), %rdi
; EGPR-NEXT:    movq 32(%r18), %r30
; EGPR-NEXT:    movq 56(%r18), %r28
; EGPR-NEXT:    movq 48(%r18), %r29
; EGPR-NEXT:    movq %rsi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NEXT:    movq 24(%rsi), %r26
; EGPR-NEXT:    movq 16(%rsi), %r21
; EGPR-NEXT:    movq (%rsi), %r31
; EGPR-NEXT:    movq 8(%rsi), %r20
; EGPR-NEXT:    movq %r29, %rax
; EGPR-NEXT:    mulq %r31
; EGPR-NEXT:    movq %rdx, %rcx
; EGPR-NEXT:    movq %rax, %r9
; EGPR-NEXT:    movq %r28, %rax
; EGPR-NEXT:    mulq %r31
; EGPR-NEXT:    movq %rdx, %r8
; EGPR-NEXT:    movq %rax, %r11
; EGPR-NEXT:    addq %rcx, %r11
; EGPR-NEXT:    adcq $0, %r8
; EGPR-NEXT:    movq %r29, %rax
; EGPR-NEXT:    mulq %r20
; EGPR-NEXT:    movq %rdx, %rcx
; EGPR-NEXT:    movq %rax, %r10
; EGPR-NEXT:    addq %r11, %r10
; EGPR-NEXT:    adcq %r8, %rcx
; EGPR-NEXT:    setb %al
; EGPR-NEXT:    movzbl %al, %r8d
; EGPR-NEXT:    movq %r28, %rax
; EGPR-NEXT:    mulq %r20
; EGPR-NEXT:    movq %rdx, %r11
; EGPR-NEXT:    movq %rax, %r16
; EGPR-NEXT:    addq %rcx, %r16
; EGPR-NEXT:    adcq %r8, %r11
; EGPR-NEXT:    movq %r30, %rax
; EGPR-NEXT:    mulq %r31
; EGPR-NEXT:    movq %rdx, %r8
; EGPR-NEXT:    movq %rax, %rcx
; EGPR-NEXT:    movq %rdi, %rax
; EGPR-NEXT:    mulq %r31
; EGPR-NEXT:    movq %rdx, %r19
; EGPR-NEXT:    movq %rax, %r22
; EGPR-NEXT:    addq %r8, %r22
; EGPR-NEXT:    adcq $0, %r19
; EGPR-NEXT:    movq %r30, %rax
; EGPR-NEXT:    mulq %r20
; EGPR-NEXT:    movq %rdx, %r23
; EGPR-NEXT:    movq %rax, %r8
; EGPR-NEXT:    addq %r22, %r8
; EGPR-NEXT:    adcq %r19, %r23
; EGPR-NEXT:    setb %al
; EGPR-NEXT:    movzbl %al, %r19d
; EGPR-NEXT:    movq %rdi, %rax
; EGPR-NEXT:    mulq %r20
; EGPR-NEXT:    movq %rdx, %r24
; EGPR-NEXT:    movq %rax, %r25
; EGPR-NEXT:    addq %r23, %r25
; EGPR-NEXT:    adcq %r19, %r24
; EGPR-NEXT:    addq %r9, %r25
; EGPR-NEXT:    adcq %r10, %r24
; EGPR-NEXT:    adcq $0, %r16
; EGPR-NEXT:    adcq $0, %r11
; EGPR-NEXT:    movq %r30, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NEXT:    movq %r30, %rax
; EGPR-NEXT:    mulq %r21
; EGPR-NEXT:    movq %rdx, %r10
; EGPR-NEXT:    movq %rax, %r9
; EGPR-NEXT:    movq %rdi, %rax
; EGPR-NEXT:    movq %rdi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NEXT:    mulq %r21
; EGPR-NEXT:    movq %rdx, %r19
; EGPR-NEXT:    movq %rax, %r22
; EGPR-NEXT:    addq %r10, %r22
; EGPR-NEXT:    adcq $0, %r19
; EGPR-NEXT:    movq %r30, %rax
; EGPR-NEXT:    mulq %r26
; EGPR-NEXT:    movq %rdx, %r23
; EGPR-NEXT:    movq %rax, %r10
; EGPR-NEXT:    addq %r22, %r10
; EGPR-NEXT:    adcq %r19, %r23
; EGPR-NEXT:    setb %al
; EGPR-NEXT:    movzbl %al, %r30d
; EGPR-NEXT:    movq %rdi, %rax
; EGPR-NEXT:    mulq %r26
; EGPR-NEXT:    movq %rdx, %r19
; EGPR-NEXT:    movq %rax, %r22
; EGPR-NEXT:    addq %r23, %r22
; EGPR-NEXT:    adcq %r30, %r19
; EGPR-NEXT:    addq %r25, %r9
; EGPR-NEXT:    adcq %r24, %r10
; EGPR-NEXT:    adcq $0, %r22
; EGPR-NEXT:    adcq $0, %r19
; EGPR-NEXT:    addq %r16, %r22
; EGPR-NEXT:    adcq %r11, %r19
; EGPR-NEXT:    setb %al
; EGPR-NEXT:    movzbl %al, %r11d
; EGPR-NEXT:    movq %r29, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NEXT:    movq %r29, %rax
; EGPR-NEXT:    mulq %r21
; EGPR-NEXT:    movq %rdx, %r16
; EGPR-NEXT:    movq %rax, %rsi
; EGPR-NEXT:    movq %r28, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NEXT:    movq %r28, %rax
; EGPR-NEXT:    mulq %r21
; EGPR-NEXT:    movq %rdx, %r25
; EGPR-NEXT:    movq %rax, %r30
; EGPR-NEXT:    addq %r16, %r30
; EGPR-NEXT:    adcq $0, %r25
; EGPR-NEXT:    movq %r29, %rax
; EGPR-NEXT:    mulq %r26
; EGPR-NEXT:    movq %rdx, %r16
; EGPR-NEXT:    movq %rax, %rdi
; EGPR-NEXT:    addq %r30, %rdi
; EGPR-NEXT:    adcq %r25, %r16
; EGPR-NEXT:    setb %al
; EGPR-NEXT:    movzbl %al, %r30d
; EGPR-NEXT:    movq %r28, %rax
; EGPR-NEXT:    mulq %r26
; EGPR-NEXT:    movq %rdx, %r25
; EGPR-NEXT:    movq %rax, %rbx
; EGPR-NEXT:    addq %r16, %rbx
; EGPR-NEXT:    adcq %r30, %r25
; EGPR-NEXT:    addq %r22, %rsi
; EGPR-NEXT:    movq %rsi, %r23
; EGPR-NEXT:    adcq %r19, %rdi
; EGPR-NEXT:    adcq %r11, %rbx
; EGPR-NEXT:    adcq $0, %r25
; EGPR-NEXT:    movq %r27, %rax
; EGPR-NEXT:    mulq %r31
; EGPR-NEXT:    movq %rdx, %r11
; EGPR-NEXT:    movq %rax, %r19
; EGPR-NEXT:    movq %r14, %rax
; EGPR-NEXT:    mulq %r31
; EGPR-NEXT:    movq %rdx, %r16
; EGPR-NEXT:    movq %rax, %r30
; EGPR-NEXT:    addq %r11, %r30
; EGPR-NEXT:    adcq $0, %r16
; EGPR-NEXT:    movq %r27, %rax
; EGPR-NEXT:    movq %r20, %rsi
; EGPR-NEXT:    mulq %r20
; EGPR-NEXT:    movq %rdx, %r20
; EGPR-NEXT:    movq %rax, %r22
; EGPR-NEXT:    addq %r30, %r22
; EGPR-NEXT:    adcq %r16, %r20
; EGPR-NEXT:    setb %al
; EGPR-NEXT:    movzbl %al, %r30d
; EGPR-NEXT:    movq %r14, %rax
; EGPR-NEXT:    mulq %rsi
; EGPR-NEXT:    movq %rdx, %r11
; EGPR-NEXT:    movq %rax, %r16
; EGPR-NEXT:    addq %r20, %r16
; EGPR-NEXT:    adcq %r30, %r11
; EGPR-NEXT:    movq %r17, %rax
; EGPR-NEXT:    mulq %r31
; EGPR-NEXT:    movq %rdx, %r30
; EGPR-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NEXT:    movq %r13, %rax
; EGPR-NEXT:    mulq %r31
; EGPR-NEXT:    movq %rdx, %r20
; EGPR-NEXT:    movq %rax, %r28
; EGPR-NEXT:    addq %r30, %r28
; EGPR-NEXT:    adcq $0, %r20
; EGPR-NEXT:    movq %r17, %rax
; EGPR-NEXT:    movq %rsi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NEXT:    mulq %rsi
; EGPR-NEXT:    movq %rdx, %r29
; EGPR-NEXT:    addq %r28, %rax
; EGPR-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NEXT:    adcq %r20, %r29
; EGPR-NEXT:    setb %r20b
; EGPR-NEXT:    movq %r13, %rax
; EGPR-NEXT:    mulq %rsi
; EGPR-NEXT:    movq %rdx, %r30
; EGPR-NEXT:    movq %rax, %r28
; EGPR-NEXT:    addq %r29, %r28
; EGPR-NEXT:    movzbl %r20b, %eax
; EGPR-NEXT:    adcq %rax, %r30
; EGPR-NEXT:    addq %r19, %r28
; EGPR-NEXT:    adcq %r22, %r30
; EGPR-NEXT:    adcq $0, %r16
; EGPR-NEXT:    adcq $0, %r11
; EGPR-NEXT:    movq %r17, %rax
; EGPR-NEXT:    mulq %r21
; EGPR-NEXT:    movq %rdx, %r19
; EGPR-NEXT:    movq %rax, %rsi
; EGPR-NEXT:    movq %r13, %rax
; EGPR-NEXT:    mulq %r21
; EGPR-NEXT:    movq %rdx, %r22
; EGPR-NEXT:    movq %rax, %r20
; EGPR-NEXT:    addq %r19, %r20
; EGPR-NEXT:    adcq $0, %r22
; EGPR-NEXT:    movq %r17, %rax
; EGPR-NEXT:    mulq %r26
; EGPR-NEXT:    movq %rdx, %r29
; EGPR-NEXT:    addq %r20, %rax
; EGPR-NEXT:    movq %rax, %r15
; EGPR-NEXT:    adcq %r22, %r29
; EGPR-NEXT:    setb %r20b
; EGPR-NEXT:    movq %r13, %rax
; EGPR-NEXT:    mulq %r26
; EGPR-NEXT:    movq %rdx, %r19
; EGPR-NEXT:    movq %rax, %r22
; EGPR-NEXT:    addq %r29, %r22
; EGPR-NEXT:    movzbl %r20b, %eax
; EGPR-NEXT:    adcq %rax, %r19
; EGPR-NEXT:    addq %r28, %rsi
; EGPR-NEXT:    movq %rsi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NEXT:    adcq %r30, %r15
; EGPR-NEXT:    movq %r15, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NEXT:    adcq $0, %r22
; EGPR-NEXT:    adcq $0, %r19
; EGPR-NEXT:    addq %r16, %r22
; EGPR-NEXT:    adcq %r11, %r19
; EGPR-NEXT:    setb %r16b
; EGPR-NEXT:    movq %r27, %rax
; EGPR-NEXT:    movq %r21, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NEXT:    mulq %r21
; EGPR-NEXT:    movq %rdx, %r30
; EGPR-NEXT:    movq %rax, %r11
; EGPR-NEXT:    movq %r14, %rax
; EGPR-NEXT:    mulq %r21
; EGPR-NEXT:    movq %rdx, %r20
; EGPR-NEXT:    movq %rax, %r28
; EGPR-NEXT:    addq %r30, %r28
; EGPR-NEXT:    adcq $0, %r20
; EGPR-NEXT:    movq %r27, %rax
; EGPR-NEXT:    mulq %r26
; EGPR-NEXT:    movq %rdx, %r30
; EGPR-NEXT:    movq %rax, %r12
; EGPR-NEXT:    addq %r28, %r12
; EGPR-NEXT:    adcq %r20, %r30
; EGPR-NEXT:    setb %r28b
; EGPR-NEXT:    movq %r14, %rax
; EGPR-NEXT:    movq %r14, %r21
; EGPR-NEXT:    mulq %r26
; EGPR-NEXT:    movq %rdx, %rbp
; EGPR-NEXT:    movq %rax, %r20
; EGPR-NEXT:    addq %r30, %r20
; EGPR-NEXT:    movzbl %r28b, %eax
; EGPR-NEXT:    adcq %rax, %rbp
; EGPR-NEXT:    addq %r22, %r11
; EGPR-NEXT:    adcq %r19, %r12
; EGPR-NEXT:    movzbl %r16b, %eax
; EGPR-NEXT:    adcq %rax, %r20
; EGPR-NEXT:    adcq $0, %rbp
; EGPR-NEXT:    addq %rcx, %r11
; EGPR-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Reload
; EGPR-NEXT:    movq 32(%rcx), %rsi
; EGPR-NEXT:    adcq %r8, %r12
; EGPR-NEXT:    adcq %r9, %r20
; EGPR-NEXT:    adcq %r10, %rbp
; EGPR-NEXT:    adcq $0, %r23
; EGPR-NEXT:    movq %r23, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NEXT:    adcq $0, %rdi
; EGPR-NEXT:    adcq $0, %rbx
; EGPR-NEXT:    adcq $0, %r25
; EGPR-NEXT:    movq %r27, %rax
; EGPR-NEXT:    mulq %rsi
; EGPR-NEXT:    movq %rdx, %r9
; EGPR-NEXT:    movq %rax, %r8
; EGPR-NEXT:    movq %r14, %rax
; EGPR-NEXT:    mulq %rsi
; EGPR-NEXT:    movq %rdx, %r10
; EGPR-NEXT:    movq %rax, %r16
; EGPR-NEXT:    addq %r9, %r16
; EGPR-NEXT:    adcq $0, %r10
; EGPR-NEXT:    movq 40(%rcx), %r19
; EGPR-NEXT:    movq %r27, %rax
; EGPR-NEXT:    mulq %r19
; EGPR-NEXT:    movq %rdx, %r22
; EGPR-NEXT:    movq %rax, %r9
; EGPR-NEXT:    addq %r16, %r9
; EGPR-NEXT:    adcq %r10, %r22
; EGPR-NEXT:    setb %r30b
; EGPR-NEXT:    movq %r14, %rax
; EGPR-NEXT:    mulq %r19
; EGPR-NEXT:    movq %rdx, %r10
; EGPR-NEXT:    movq %rax, %r16
; EGPR-NEXT:    addq %r22, %r16
; EGPR-NEXT:    movzbl %r30b, %eax
; EGPR-NEXT:    adcq %rax, %r10
; EGPR-NEXT:    movq %r17, %rax
; EGPR-NEXT:    mulq %rsi
; EGPR-NEXT:    movq %rdx, %r22
; EGPR-NEXT:    movq %rax, %r23
; EGPR-NEXT:    movq %r13, %rax
; EGPR-NEXT:    mulq %rsi
; EGPR-NEXT:    movq %rdx, %r30
; EGPR-NEXT:    movq %rax, %r28
; EGPR-NEXT:    addq %r22, %r28
; EGPR-NEXT:    adcq $0, %r30
; EGPR-NEXT:    movq %r17, %rax
; EGPR-NEXT:    movq %r17, %r14
; EGPR-NEXT:    movq %r17, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NEXT:    mulq %r19
; EGPR-NEXT:    movq %rdx, %r29
; EGPR-NEXT:    addq %r28, %rax
; EGPR-NEXT:    movq %rax, %r17
; EGPR-NEXT:    adcq %r30, %r29
; EGPR-NEXT:    setb %r28b
; EGPR-NEXT:    movq %r13, %rax
; EGPR-NEXT:    movq %r13, %r24
; EGPR-NEXT:    mulq %r19
; EGPR-NEXT:    movq %rdx, %r22
; EGPR-NEXT:    movq %rax, %r30
; EGPR-NEXT:    addq %r29, %r30
; EGPR-NEXT:    movzbl %r28b, %eax
; EGPR-NEXT:    adcq %rax, %r22
; EGPR-NEXT:    addq %r8, %r30
; EGPR-NEXT:    adcq %r9, %r22
; EGPR-NEXT:    adcq $0, %r16
; EGPR-NEXT:    adcq $0, %r10
; EGPR-NEXT:    movq 48(%rcx), %r9
; EGPR-NEXT:    movq %r14, %rax
; EGPR-NEXT:    mulq %r9
; EGPR-NEXT:    movq %rdx, %r8
; EGPR-NEXT:    movq %rax, %r13
; EGPR-NEXT:    movq %r24, %rax
; EGPR-NEXT:    movq %r24, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NEXT:    mulq %r9
; EGPR-NEXT:    movq %rdx, %r28
; EGPR-NEXT:    movq %rax, %r29
; EGPR-NEXT:    addq %r8, %r29
; EGPR-NEXT:    adcq $0, %r28
; EGPR-NEXT:    movq 56(%rcx), %r8
; EGPR-NEXT:    movq %r14, %rax
; EGPR-NEXT:    mulq %r8
; EGPR-NEXT:    movq %rdx, %r14
; EGPR-NEXT:    addq %r29, %rax
; EGPR-NEXT:    movq %rax, %rcx
; EGPR-NEXT:    adcq %r28, %r14
; EGPR-NEXT:    setb %r15b
; EGPR-NEXT:    movq %r24, %rax
; EGPR-NEXT:    mulq %r8
; EGPR-NEXT:    movq %rdx, %r28
; EGPR-NEXT:    movq %rax, %r29
; EGPR-NEXT:    addq %r14, %r29
; EGPR-NEXT:    movzbl %r15b, %eax
; EGPR-NEXT:    adcq %rax, %r28
; EGPR-NEXT:    addq %r30, %r13
; EGPR-NEXT:    movq %r13, %r24
; EGPR-NEXT:    adcq %r22, %rcx
; EGPR-NEXT:    adcq $0, %r29
; EGPR-NEXT:    adcq $0, %r28
; EGPR-NEXT:    addq %r16, %r29
; EGPR-NEXT:    adcq %r10, %r28
; EGPR-NEXT:    setb %r14b
; EGPR-NEXT:    movq %r27, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NEXT:    movq %r27, %rax
; EGPR-NEXT:    mulq %r9
; EGPR-NEXT:    movq %rdx, %r16
; EGPR-NEXT:    movq %rax, %r10
; EGPR-NEXT:    movq %r21, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NEXT:    movq %r21, %rax
; EGPR-NEXT:    mulq %r9
; EGPR-NEXT:    movq %rdx, %r22
; EGPR-NEXT:    movq %rax, %r30
; EGPR-NEXT:    addq %r16, %r30
; EGPR-NEXT:    adcq $0, %r22
; EGPR-NEXT:    movq %r27, %rax
; EGPR-NEXT:    mulq %r8
; EGPR-NEXT:    movq %rdx, %r15
; EGPR-NEXT:    movq %rax, %r16
; EGPR-NEXT:    addq %r30, %r16
; EGPR-NEXT:    adcq %r22, %r15
; EGPR-NEXT:    setb %r13b
; EGPR-NEXT:    movq %r21, %rax
; EGPR-NEXT:    mulq %r8
; EGPR-NEXT:    movq %rdx, %r22
; EGPR-NEXT:    movq %rax, %r30
; EGPR-NEXT:    addq %r15, %r30
; EGPR-NEXT:    movzbl %r13b, %eax
; EGPR-NEXT:    adcq %rax, %r22
; EGPR-NEXT:    addq %r29, %r10
; EGPR-NEXT:    adcq %r28, %r16
; EGPR-NEXT:    movzbl %r14b, %eax
; EGPR-NEXT:    adcq %rax, %r30
; EGPR-NEXT:    adcq $0, %r22
; EGPR-NEXT:    addq %r11, %r23
; EGPR-NEXT:    movq %r23, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NEXT:    adcq %r12, %r17
; EGPR-NEXT:    movq %r17, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NEXT:    adcq %r20, %r24
; EGPR-NEXT:    movq %r24, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NEXT:    adcq %rbp, %rcx
; EGPR-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NEXT:    adcq $0, %r10
; EGPR-NEXT:    adcq $0, %r16
; EGPR-NEXT:    adcq $0, %r30
; EGPR-NEXT:    adcq $0, %r22
; EGPR-NEXT:    addq {{[-0-9]+}}(%r{{[sb]}}p), %r10 # 8-byte Folded Reload
; EGPR-NEXT:    adcq %rdi, %r16
; EGPR-NEXT:    adcq %rbx, %r30
; EGPR-NEXT:    adcq %r25, %r22
; EGPR-NEXT:    setb %r11b
; EGPR-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r17 # 8-byte Reload
; EGPR-NEXT:    movq %r17, %rax
; EGPR-NEXT:    mulq %rsi
; EGPR-NEXT:    movq %rdx, %r23
; EGPR-NEXT:    movq %rax, %r25
; EGPR-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Reload
; EGPR-NEXT:    movq %rcx, %rax
; EGPR-NEXT:    mulq %rsi
; EGPR-NEXT:    movq %rdx, %r24
; EGPR-NEXT:    movq %rax, %r28
; EGPR-NEXT:    addq %r23, %r28
; EGPR-NEXT:    adcq $0, %r24
; EGPR-NEXT:    movq %r17, %rax
; EGPR-NEXT:    movq %r17, %r21
; EGPR-NEXT:    mulq %r19
; EGPR-NEXT:    movq %rdx, %r29
; EGPR-NEXT:    movq %rax, %r20
; EGPR-NEXT:    addq %r28, %r20
; EGPR-NEXT:    adcq %r24, %r29
; EGPR-NEXT:    setb %r28b
; EGPR-NEXT:    movq %rcx, %rax
; EGPR-NEXT:    movq %rcx, %r15
; EGPR-NEXT:    mulq %r19
; EGPR-NEXT:    movq %rdx, %r23
; EGPR-NEXT:    movq %rax, %r24
; EGPR-NEXT:    addq %r29, %r24
; EGPR-NEXT:    movzbl %r28b, %eax
; EGPR-NEXT:    adcq %rax, %r23
; EGPR-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Reload
; EGPR-NEXT:    movq %rcx, %rax
; EGPR-NEXT:    mulq %rsi
; EGPR-NEXT:    movq %rdx, %r28
; EGPR-NEXT:    movq %rax, %rdi
; EGPR-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r17 # 8-byte Reload
; EGPR-NEXT:    movq %r17, %rax
; EGPR-NEXT:    mulq %rsi
; EGPR-NEXT:    movq %rdx, %r29
; EGPR-NEXT:    movq %rax, %rbx
; EGPR-NEXT:    addq %r28, %rbx
; EGPR-NEXT:    adcq $0, %r29
; EGPR-NEXT:    movq %rcx, %rax
; EGPR-NEXT:    movq %rcx, %r27
; EGPR-NEXT:    mulq %r19
; EGPR-NEXT:    movq %rdx, %r14
; EGPR-NEXT:    addq %rbx, %rax
; EGPR-NEXT:    movq %rax, %rcx
; EGPR-NEXT:    adcq %r29, %r14
; EGPR-NEXT:    setb %r29b
; EGPR-NEXT:    movq %r17, %rax
; EGPR-NEXT:    movq %r17, %r12
; EGPR-NEXT:    mulq %r19
; EGPR-NEXT:    movq %rdx, %r28
; EGPR-NEXT:    movq %rax, %rbx
; EGPR-NEXT:    addq %r14, %rbx
; EGPR-NEXT:    movzbl %r29b, %eax
; EGPR-NEXT:    adcq %rax, %r28
; EGPR-NEXT:    addq %r25, %rbx
; EGPR-NEXT:    adcq %r20, %r28
; EGPR-NEXT:    adcq $0, %r24
; EGPR-NEXT:    adcq $0, %r23
; EGPR-NEXT:    movq %r27, %rax
; EGPR-NEXT:    mulq %r9
; EGPR-NEXT:    movq %rdx, %r25
; EGPR-NEXT:    movq %rax, %r17
; EGPR-NEXT:    movq %r12, %rax
; EGPR-NEXT:    mulq %r9
; EGPR-NEXT:    movq %rdx, %r20
; EGPR-NEXT:    movq %rax, %r29
; EGPR-NEXT:    addq %r25, %r29
; EGPR-NEXT:    adcq $0, %r20
; EGPR-NEXT:    movq %r27, %rax
; EGPR-NEXT:    mulq %r8
; EGPR-NEXT:    movq %rdx, %r14
; EGPR-NEXT:    addq %r29, %rax
; EGPR-NEXT:    movq %rax, %r27
; EGPR-NEXT:    adcq %r20, %r14
; EGPR-NEXT:    setb %r29b
; EGPR-NEXT:    movq %r12, %rax
; EGPR-NEXT:    mulq %r8
; EGPR-NEXT:    movq %rdx, %r25
; EGPR-NEXT:    movq %rax, %r20
; EGPR-NEXT:    addq %r14, %r20
; EGPR-NEXT:    movzbl %r29b, %eax
; EGPR-NEXT:    adcq %rax, %r25
; EGPR-NEXT:    addq %rbx, %r17
; EGPR-NEXT:    adcq %r28, %r27
; EGPR-NEXT:    adcq $0, %r20
; EGPR-NEXT:    adcq $0, %r25
; EGPR-NEXT:    addq %r24, %r20
; EGPR-NEXT:    adcq %r23, %r25
; EGPR-NEXT:    setb %r28b
; EGPR-NEXT:    movq %r21, %rax
; EGPR-NEXT:    mulq %r9
; EGPR-NEXT:    movq %rdx, %r23
; EGPR-NEXT:    movq %rax, %rbx
; EGPR-NEXT:    movq %r15, %rax
; EGPR-NEXT:    mulq %r9
; EGPR-NEXT:    movq %rdx, %r24
; EGPR-NEXT:    movq %rax, %r29
; EGPR-NEXT:    addq %r23, %r29
; EGPR-NEXT:    adcq $0, %r24
; EGPR-NEXT:    movq %r21, %rax
; EGPR-NEXT:    mulq %r8
; EGPR-NEXT:    movq %rdx, %r14
; EGPR-NEXT:    addq %r29, %rax
; EGPR-NEXT:    movq %rax, %r23
; EGPR-NEXT:    adcq %r24, %r14
; EGPR-NEXT:    setb %r29b
; EGPR-NEXT:    movq %r15, %rax
; EGPR-NEXT:    mulq %r8
; EGPR-NEXT:    movq %rdx, %rbp
; EGPR-NEXT:    movq %rax, %r12
; EGPR-NEXT:    addq %r14, %r12
; EGPR-NEXT:    movzbl %r29b, %eax
; EGPR-NEXT:    adcq %rax, %rbp
; EGPR-NEXT:    addq %r20, %rbx
; EGPR-NEXT:    adcq %r25, %r23
; EGPR-NEXT:    movzbl %r28b, %eax
; EGPR-NEXT:    adcq %rax, %r12
; EGPR-NEXT:    adcq $0, %rbp
; EGPR-NEXT:    addq %r10, %rdi
; EGPR-NEXT:    movq %rdi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NEXT:    adcq %r16, %rcx
; EGPR-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NEXT:    adcq %r30, %r17
; EGPR-NEXT:    movq %r17, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NEXT:    adcq %r22, %r27
; EGPR-NEXT:    movq %r27, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NEXT:    movzbl %r11b, %eax
; EGPR-NEXT:    adcq %rax, %rbx
; EGPR-NEXT:    movq %rbx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NEXT:    adcq $0, %r23
; EGPR-NEXT:    movq %r23, (%rsp) # 8-byte Spill
; EGPR-NEXT:    adcq $0, %r12
; EGPR-NEXT:    adcq $0, %rbp
; EGPR-NEXT:    movq 64(%r18), %r10
; EGPR-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r17 # 8-byte Reload
; EGPR-NEXT:    movq %r17, %rax
; EGPR-NEXT:    mulq %r10
; EGPR-NEXT:    movq %rdx, %r11
; EGPR-NEXT:    movq %rax, %r25
; EGPR-NEXT:    movq %r26, %rax
; EGPR-NEXT:    mulq %r10
; EGPR-NEXT:    movq %rdx, %r16
; EGPR-NEXT:    movq %rax, %r22
; EGPR-NEXT:    addq %r11, %r22
; EGPR-NEXT:    adcq $0, %r16
; EGPR-NEXT:    movq 72(%r18), %r11
; EGPR-NEXT:    movq %r17, %rax
; EGPR-NEXT:    mulq %r11
; EGPR-NEXT:    movq %rdx, %r20
; EGPR-NEXT:    movq %rax, %r30
; EGPR-NEXT:    addq %r22, %r30
; EGPR-NEXT:    adcq %r16, %r20
; EGPR-NEXT:    setb %r28b
; EGPR-NEXT:    movq %r26, %rax
; EGPR-NEXT:    mulq %r11
; EGPR-NEXT:    movq %rdx, %r16
; EGPR-NEXT:    movq %rax, %r22
; EGPR-NEXT:    addq %r20, %r22
; EGPR-NEXT:    movzbl %r28b, %eax
; EGPR-NEXT:    adcq %rax, %r16
; EGPR-NEXT:    movq %r31, %rax
; EGPR-NEXT:    mulq %r10
; EGPR-NEXT:    movq %rdx, %r20
; EGPR-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r23 # 8-byte Reload
; EGPR-NEXT:    movq %r23, %rax
; EGPR-NEXT:    mulq %r10
; EGPR-NEXT:    movq %rdx, %r28
; EGPR-NEXT:    movq %rax, %r29
; EGPR-NEXT:    addq %r20, %r29
; EGPR-NEXT:    adcq $0, %r28
; EGPR-NEXT:    movq %r31, %rax
; EGPR-NEXT:    mulq %r11
; EGPR-NEXT:    movq %rdx, %r14
; EGPR-NEXT:    addq %r29, %rax
; EGPR-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NEXT:    adcq %r28, %r14
; EGPR-NEXT:    setb %r28b
; EGPR-NEXT:    movq %r23, %rax
; EGPR-NEXT:    mulq %r11
; EGPR-NEXT:    movq %rdx, %r20
; EGPR-NEXT:    movq %rax, %r13
; EGPR-NEXT:    addq %r14, %r13
; EGPR-NEXT:    movzbl %r28b, %eax
; EGPR-NEXT:    adcq %rax, %r20
; EGPR-NEXT:    addq %r25, %r13
; EGPR-NEXT:    adcq %r30, %r20
; EGPR-NEXT:    adcq $0, %r22
; EGPR-NEXT:    adcq $0, %r16
; EGPR-NEXT:    movq 80(%r18), %r28
; EGPR-NEXT:    movq %r31, %rax
; EGPR-NEXT:    mulq %r28
; EGPR-NEXT:    movq %rdx, %r25
; EGPR-NEXT:    movq %rax, %rdi
; EGPR-NEXT:    movq %r23, %rax
; EGPR-NEXT:    mulq %r28
; EGPR-NEXT:    movq %rdx, %r30
; EGPR-NEXT:    movq %rax, %r14
; EGPR-NEXT:    addq %r25, %r14
; EGPR-NEXT:    adcq $0, %r30
; EGPR-NEXT:    movq 88(%r18), %r29
; EGPR-NEXT:    movq %r31, %rax
; EGPR-NEXT:    mulq %r29
; EGPR-NEXT:    movq %rdx, %rcx
; EGPR-NEXT:    addq %r14, %rax
; EGPR-NEXT:    movq %rax, %r24
; EGPR-NEXT:    adcq %r30, %rcx
; EGPR-NEXT:    setb %r30b
; EGPR-NEXT:    movq %r23, %rax
; EGPR-NEXT:    mulq %r29
; EGPR-NEXT:    movq %rdx, %r14
; EGPR-NEXT:    movq %rax, %r15
; EGPR-NEXT:    addq %rcx, %r15
; EGPR-NEXT:    movzbl %r30b, %eax
; EGPR-NEXT:    adcq %rax, %r14
; EGPR-NEXT:    addq %r13, %rdi
; EGPR-NEXT:    movq %rdi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NEXT:    adcq %r20, %r24
; EGPR-NEXT:    movq %r24, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NEXT:    adcq $0, %r15
; EGPR-NEXT:    adcq $0, %r14
; EGPR-NEXT:    addq %r22, %r15
; EGPR-NEXT:    adcq %r16, %r14
; EGPR-NEXT:    setb %cl
; EGPR-NEXT:    movq %r17, %rdi
; EGPR-NEXT:    movq %r17, %rax
; EGPR-NEXT:    mulq %r28
; EGPR-NEXT:    movq %rdx, %r22
; EGPR-NEXT:    movq %rax, %r17
; EGPR-NEXT:    movq %r26, %rax
; EGPR-NEXT:    mulq %r28
; EGPR-NEXT:    movq %rdx, %r30
; EGPR-NEXT:    movq %rax, %r20
; EGPR-NEXT:    addq %r22, %r20
; EGPR-NEXT:    adcq $0, %r30
; EGPR-NEXT:    movq %rdi, %rax
; EGPR-NEXT:    mulq %r29
; EGPR-NEXT:    movq %rdx, %r13
; EGPR-NEXT:    movq %rax, %r22
; EGPR-NEXT:    addq %r20, %r22
; EGPR-NEXT:    adcq %r30, %r13
; EGPR-NEXT:    setb %r16b
; EGPR-NEXT:    movq %r26, %rax
; EGPR-NEXT:    mulq %r29
; EGPR-NEXT:    movq %rdx, %r30
; EGPR-NEXT:    movq %rax, %r20
; EGPR-NEXT:    addq %r13, %r20
; EGPR-NEXT:    movzbl %r16b, %eax
; EGPR-NEXT:    adcq %rax, %r30
; EGPR-NEXT:    addq %r15, %r17
; EGPR-NEXT:    adcq %r14, %r22
; EGPR-NEXT:    movzbl %cl, %eax
; EGPR-NEXT:    adcq %rax, %r20
; EGPR-NEXT:    adcq $0, %r30
; EGPR-NEXT:    imulq %rsi, %r29
; EGPR-NEXT:    movq %rsi, %rax
; EGPR-NEXT:    mulq %r28
; EGPR-NEXT:    movq %rax, %rcx
; EGPR-NEXT:    addq %r29, %rdx
; EGPR-NEXT:    imulq %r19, %r28
; EGPR-NEXT:    addq %rdx, %r28
; EGPR-NEXT:    movq %r9, %r16
; EGPR-NEXT:    imulq %r11, %r16
; EGPR-NEXT:    movq %r9, %rax
; EGPR-NEXT:    mulq %r10
; EGPR-NEXT:    movq %rax, %r9
; EGPR-NEXT:    addq %r16, %rdx
; EGPR-NEXT:    imulq %r10, %r8
; EGPR-NEXT:    addq %rdx, %r8
; EGPR-NEXT:    addq %rcx, %r9
; EGPR-NEXT:    adcq %r28, %r8
; EGPR-NEXT:    movq %r10, %rax
; EGPR-NEXT:    mulq %rsi
; EGPR-NEXT:    movq %rdx, %rcx
; EGPR-NEXT:    movq %rax, %r28
; EGPR-NEXT:    movq %r11, %rax
; EGPR-NEXT:    mulq %rsi
; EGPR-NEXT:    movq %rdx, %rsi
; EGPR-NEXT:    movq %rax, %r16
; EGPR-NEXT:    addq %rcx, %r16
; EGPR-NEXT:    adcq $0, %rsi
; EGPR-NEXT:    movq %r10, %rax
; EGPR-NEXT:    mulq %r19
; EGPR-NEXT:    movq %rdx, %rcx
; EGPR-NEXT:    movq %rax, %r10
; EGPR-NEXT:    addq %r16, %r10
; EGPR-NEXT:    adcq %rsi, %rcx
; EGPR-NEXT:    setb %sil
; EGPR-NEXT:    movq %r11, %rax
; EGPR-NEXT:    mulq %r19
; EGPR-NEXT:    movq %rdx, %r11
; EGPR-NEXT:    movq %rax, %r19
; EGPR-NEXT:    addq %rcx, %r19
; EGPR-NEXT:    movzbl %sil, %eax
; EGPR-NEXT:    adcq %rax, %r11
; EGPR-NEXT:    addq %r9, %r19
; EGPR-NEXT:    adcq %r8, %r11
; EGPR-NEXT:    movq 112(%r18), %rcx
; EGPR-NEXT:    movq %r31, %rax
; EGPR-NEXT:    mulq %rcx
; EGPR-NEXT:    movq %rax, %rsi
; EGPR-NEXT:    imulq %r23, %rcx
; EGPR-NEXT:    addq %rdx, %rcx
; EGPR-NEXT:    movq 120(%r18), %rax
; EGPR-NEXT:    imulq %r31, %rax
; EGPR-NEXT:    addq %rax, %rcx
; EGPR-NEXT:    movq 96(%r18), %r8
; EGPR-NEXT:    movq 104(%r18), %r9
; EGPR-NEXT:    movq %rdi, %rax
; EGPR-NEXT:    imulq %r9, %rdi
; EGPR-NEXT:    mulq %r8
; EGPR-NEXT:    movq %rax, %r16
; EGPR-NEXT:    addq %rdi, %rdx
; EGPR-NEXT:    imulq %r8, %r26
; EGPR-NEXT:    addq %rdx, %r26
; EGPR-NEXT:    addq %rsi, %r16
; EGPR-NEXT:    adcq %rcx, %r26
; EGPR-NEXT:    movq %r8, %rax
; EGPR-NEXT:    mulq %r31
; EGPR-NEXT:    movq %rdx, %rsi
; EGPR-NEXT:    movq %rax, %rbx
; EGPR-NEXT:    movq %r9, %rax
; EGPR-NEXT:    mulq %r31
; EGPR-NEXT:    movq %rdx, %r31
; EGPR-NEXT:    movq %rax, %r21
; EGPR-NEXT:    addq %rsi, %r21
; EGPR-NEXT:    adcq $0, %r31
; EGPR-NEXT:    movq %r8, %rax
; EGPR-NEXT:    mulq %r23
; EGPR-NEXT:    movq %rdx, %rsi
; EGPR-NEXT:    movq %rax, %r24
; EGPR-NEXT:    addq %r21, %r24
; EGPR-NEXT:    adcq %r31, %rsi
; EGPR-NEXT:    setb %r31b
; EGPR-NEXT:    movq %r9, %rax
; EGPR-NEXT:    mulq %r23
; EGPR-NEXT:    movq %rdx, %r23
; EGPR-NEXT:    movq %rax, %r9
; EGPR-NEXT:    addq %rsi, %r9
; EGPR-NEXT:    movzbl %r31b, %eax
; EGPR-NEXT:    adcq %rax, %r23
; EGPR-NEXT:    addq %r16, %r9
; EGPR-NEXT:    adcq %r26, %r23
; EGPR-NEXT:    addq %r28, %rbx
; EGPR-NEXT:    adcq %r10, %r24
; EGPR-NEXT:    adcq %r19, %r9
; EGPR-NEXT:    adcq %r11, %r23
; EGPR-NEXT:    addq %r17, %rbx
; EGPR-NEXT:    adcq %r22, %r24
; EGPR-NEXT:    adcq %r20, %r9
; EGPR-NEXT:    adcq %r30, %r23
; EGPR-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r25 # 8-byte Reload
; EGPR-NEXT:    movq 80(%r25), %r10
; EGPR-NEXT:    movq %r10, %rax
; EGPR-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r8 # 8-byte Reload
; EGPR-NEXT:    mulq %r8
; EGPR-NEXT:    movq %rax, %r31
; EGPR-NEXT:    movq %rdx, %rsi
; EGPR-NEXT:    movq 88(%r25), %r26
; EGPR-NEXT:    movq %r26, %rax
; EGPR-NEXT:    mulq %r8
; EGPR-NEXT:    movq %rdx, %r11
; EGPR-NEXT:    movq %rax, %r16
; EGPR-NEXT:    addq %rsi, %r16
; EGPR-NEXT:    adcq $0, %r11
; EGPR-NEXT:    movq %r10, %rax
; EGPR-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rdi # 8-byte Reload
; EGPR-NEXT:    mulq %rdi
; EGPR-NEXT:    movq %rdx, %rsi
; EGPR-NEXT:    movq %rax, %r20
; EGPR-NEXT:    addq %r16, %r20
; EGPR-NEXT:    adcq %r11, %rsi
; EGPR-NEXT:    setb %r11b
; EGPR-NEXT:    movq %r26, %rax
; EGPR-NEXT:    mulq %rdi
; EGPR-NEXT:    movq %rdx, %r22
; EGPR-NEXT:    movq %rax, %r30
; EGPR-NEXT:    addq %rsi, %r30
; EGPR-NEXT:    movzbl %r11b, %eax
; EGPR-NEXT:    adcq %rax, %r22
; EGPR-NEXT:    movq 64(%r25), %r16
; EGPR-NEXT:    movq %r16, %rax
; EGPR-NEXT:    mulq %r8
; EGPR-NEXT:    movq %rax, %r19
; EGPR-NEXT:    movq %rdx, %rsi
; EGPR-NEXT:    movq 72(%r25), %r11
; EGPR-NEXT:    movq %r11, %rax
; EGPR-NEXT:    mulq %r8
; EGPR-NEXT:    movq %rdx, %r17
; EGPR-NEXT:    movq %rax, %r21
; EGPR-NEXT:    addq %rsi, %r21
; EGPR-NEXT:    adcq $0, %r17
; EGPR-NEXT:    movq %r16, %rax
; EGPR-NEXT:    mulq %rdi
; EGPR-NEXT:    movq %rdx, %rsi
; EGPR-NEXT:    movq %rax, %r27
; EGPR-NEXT:    addq %r21, %r27
; EGPR-NEXT:    adcq %r17, %rsi
; EGPR-NEXT:    setb %r17b
; EGPR-NEXT:    movq %r11, %rax
; EGPR-NEXT:    mulq %rdi
; EGPR-NEXT:    movq %rdx, %r28
; EGPR-NEXT:    movq %rax, %r15
; EGPR-NEXT:    addq %rsi, %r15
; EGPR-NEXT:    movzbl %r17b, %eax
; EGPR-NEXT:    adcq %rax, %r28
; EGPR-NEXT:    addq %r31, %r15
; EGPR-NEXT:    adcq %r20, %r28
; EGPR-NEXT:    adcq $0, %r30
; EGPR-NEXT:    adcq $0, %r22
; EGPR-NEXT:    movq %r16, %rax
; EGPR-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r18 # 8-byte Reload
; EGPR-NEXT:    mulq %r18
; EGPR-NEXT:    movq %rdx, %rsi
; EGPR-NEXT:    movq %rax, %r31
; EGPR-NEXT:    movq %r11, %rax
; EGPR-NEXT:    mulq %r18
; EGPR-NEXT:    movq %rdx, %r17
; EGPR-NEXT:    movq %rax, %r20
; EGPR-NEXT:    addq %rsi, %r20
; EGPR-NEXT:    adcq $0, %r17
; EGPR-NEXT:    movq %r16, %rax
; EGPR-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Reload
; EGPR-NEXT:    mulq %rcx
; EGPR-NEXT:    movq %rdx, %rsi
; EGPR-NEXT:    movq %rax, %r21
; EGPR-NEXT:    addq %r20, %r21
; EGPR-NEXT:    adcq %r17, %rsi
; EGPR-NEXT:    setb %r17b
; EGPR-NEXT:    movq %r11, %rax
; EGPR-NEXT:    mulq %rcx
; EGPR-NEXT:    movq %rdx, %r29
; EGPR-NEXT:    movq %rax, %r14
; EGPR-NEXT:    addq %rsi, %r14
; EGPR-NEXT:    movzbl %r17b, %eax
; EGPR-NEXT:    adcq %rax, %r29
; EGPR-NEXT:    addq %r15, %r31
; EGPR-NEXT:    adcq %r28, %r21
; EGPR-NEXT:    adcq $0, %r14
; EGPR-NEXT:    adcq $0, %r29
; EGPR-NEXT:    addq %r30, %r14
; EGPR-NEXT:    adcq %r22, %r29
; EGPR-NEXT:    setb %sil
; EGPR-NEXT:    movq %r10, %rax
; EGPR-NEXT:    mulq %r18
; EGPR-NEXT:    movq %rdx, %r17
; EGPR-NEXT:    movq %rax, %r22
; EGPR-NEXT:    movq %r26, %rax
; EGPR-NEXT:    mulq %r18
; EGPR-NEXT:    movq %rdx, %r20
; EGPR-NEXT:    movq %rax, %r28
; EGPR-NEXT:    addq %r17, %r28
; EGPR-NEXT:    adcq $0, %r20
; EGPR-NEXT:    movq %r10, %rax
; EGPR-NEXT:    mulq %rcx
; EGPR-NEXT:    movq %rdx, %r17
; EGPR-NEXT:    movq %rax, %r30
; EGPR-NEXT:    addq %r28, %r30
; EGPR-NEXT:    adcq %r20, %r17
; EGPR-NEXT:    setb %r15b
; EGPR-NEXT:    movq %r26, %rax
; EGPR-NEXT:    mulq %rcx
; EGPR-NEXT:    movq %rdx, %r20
; EGPR-NEXT:    movq %rax, %r28
; EGPR-NEXT:    addq %r17, %r28
; EGPR-NEXT:    movzbl %r15b, %eax
; EGPR-NEXT:    adcq %rax, %r20
; EGPR-NEXT:    addq %r14, %r22
; EGPR-NEXT:    adcq %r29, %r30
; EGPR-NEXT:    movzbl %sil, %eax
; EGPR-NEXT:    adcq %rax, %r28
; EGPR-NEXT:    adcq $0, %r20
; EGPR-NEXT:    movq 96(%r25), %r17
; EGPR-NEXT:    imulq %r17, %rcx
; EGPR-NEXT:    movq %r17, %rax
; EGPR-NEXT:    mulq %r18
; EGPR-NEXT:    movq %rax, %rsi
; EGPR-NEXT:    addq %rcx, %rdx
; EGPR-NEXT:    movq 104(%r25), %r29
; EGPR-NEXT:    movq %r18, %rax
; EGPR-NEXT:    imulq %r29, %rax
; EGPR-NEXT:    addq %rdx, %rax
; EGPR-NEXT:    movq %rax, %rcx
; EGPR-NEXT:    movq 112(%r25), %rax
; EGPR-NEXT:    movq %rax, %r14
; EGPR-NEXT:    imulq %rdi, %r14
; EGPR-NEXT:    mulq %r8
; EGPR-NEXT:    movq %rax, %r15
; EGPR-NEXT:    addq %r14, %rdx
; EGPR-NEXT:    movq 120(%r25), %r14
; EGPR-NEXT:    imulq %r8, %r14
; EGPR-NEXT:    addq %rdx, %r14
; EGPR-NEXT:    addq %rsi, %r15
; EGPR-NEXT:    adcq %rcx, %r14
; EGPR-NEXT:    movq %r8, %rax
; EGPR-NEXT:    mulq %r17
; EGPR-NEXT:    movq %rdx, %r18
; EGPR-NEXT:    movq %rax, %r25
; EGPR-NEXT:    movq %rdi, %rax
; EGPR-NEXT:    mulq %r17
; EGPR-NEXT:    movq %rdx, %r13
; EGPR-NEXT:    movq %rax, %rcx
; EGPR-NEXT:    addq %r18, %rcx
; EGPR-NEXT:    adcq $0, %r13
; EGPR-NEXT:    movq %r8, %rax
; EGPR-NEXT:    mulq %r29
; EGPR-NEXT:    movq %rdx, %rsi
; EGPR-NEXT:    movq %rax, %r17
; EGPR-NEXT:    addq %rcx, %r17
; EGPR-NEXT:    adcq %r13, %rsi
; EGPR-NEXT:    setb %cl
; EGPR-NEXT:    movq %rdi, %rax
; EGPR-NEXT:    mulq %r29
; EGPR-NEXT:    movq %rdx, %r18
; EGPR-NEXT:    movq %rax, %r29
; EGPR-NEXT:    addq %rsi, %r29
; EGPR-NEXT:    movzbl %cl, %eax
; EGPR-NEXT:    adcq %rax, %r18
; EGPR-NEXT:    addq %r15, %r29
; EGPR-NEXT:    adcq %r14, %r18
; EGPR-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rsi # 8-byte Reload
; EGPR-NEXT:    imulq %r16, %rsi
; EGPR-NEXT:    movq %r16, %rax
; EGPR-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rdi # 8-byte Reload
; EGPR-NEXT:    mulq %rdi
; EGPR-NEXT:    movq %rax, %rcx
; EGPR-NEXT:    addq %rsi, %rdx
; EGPR-NEXT:    movq %rdi, %rax
; EGPR-NEXT:    imulq %r11, %rax
; EGPR-NEXT:    addq %rdx, %rax
; EGPR-NEXT:    movq %rax, %r15
; EGPR-NEXT:    movq %r10, %rsi
; EGPR-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rdi # 8-byte Reload
; EGPR-NEXT:    imulq %rdi, %rsi
; EGPR-NEXT:    movq %r10, %rax
; EGPR-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r10 # 8-byte Reload
; EGPR-NEXT:    mulq %r10
; EGPR-NEXT:    movq %rax, %r14
; EGPR-NEXT:    addq %rsi, %rdx
; EGPR-NEXT:    imulq %r10, %r26
; EGPR-NEXT:    addq %rdx, %r26
; EGPR-NEXT:    addq %rcx, %r14
; EGPR-NEXT:    adcq %r15, %r26
; EGPR-NEXT:    movq %r10, %rax
; EGPR-NEXT:    movq %r10, %r13
; EGPR-NEXT:    mulq %r16
; EGPR-NEXT:    movq %rdx, %rcx
; EGPR-NEXT:    movq %rax, %r10
; EGPR-NEXT:    movq %rdi, %rax
; EGPR-NEXT:    mulq %r16
; EGPR-NEXT:    movq %rdx, %rsi
; EGPR-NEXT:    movq %rax, %r15
; EGPR-NEXT:    addq %rcx, %r15
; EGPR-NEXT:    adcq $0, %rsi
; EGPR-NEXT:    movq %r13, %rax
; EGPR-NEXT:    mulq %r11
; EGPR-NEXT:    movq %rdx, %rcx
; EGPR-NEXT:    movq %rax, %r16
; EGPR-NEXT:    addq %r15, %r16
; EGPR-NEXT:    adcq %rsi, %rcx
; EGPR-NEXT:    setb %sil
; EGPR-NEXT:    movq %rdi, %rax
; EGPR-NEXT:    mulq %r11
; EGPR-NEXT:    addq %rcx, %rax
; EGPR-NEXT:    movzbl %sil, %ecx
; EGPR-NEXT:    adcq %rcx, %rdx
; EGPR-NEXT:    addq %r14, %rax
; EGPR-NEXT:    adcq %r26, %rdx
; EGPR-NEXT:    addq %r25, %r10
; EGPR-NEXT:    adcq %r17, %r16
; EGPR-NEXT:    adcq %r29, %rax
; EGPR-NEXT:    adcq %r18, %rdx
; EGPR-NEXT:    addq %r22, %r10
; EGPR-NEXT:    adcq %r30, %r16
; EGPR-NEXT:    adcq %r28, %rax
; EGPR-NEXT:    adcq %r20, %rdx
; EGPR-NEXT:    addq {{[-0-9]+}}(%r{{[sb]}}p), %r19 # 8-byte Folded Reload
; EGPR-NEXT:    adcq {{[-0-9]+}}(%r{{[sb]}}p), %r27 # 8-byte Folded Reload
; EGPR-NEXT:    adcq {{[-0-9]+}}(%r{{[sb]}}p), %r31 # 8-byte Folded Reload
; EGPR-NEXT:    adcq {{[-0-9]+}}(%r{{[sb]}}p), %r21 # 8-byte Folded Reload
; EGPR-NEXT:    adcq %rbx, %r10
; EGPR-NEXT:    adcq %r24, %r16
; EGPR-NEXT:    adcq %r9, %rax
; EGPR-NEXT:    adcq %r23, %rdx
; EGPR-NEXT:    addq {{[-0-9]+}}(%r{{[sb]}}p), %r19 # 8-byte Folded Reload
; EGPR-NEXT:    adcq {{[-0-9]+}}(%r{{[sb]}}p), %r27 # 8-byte Folded Reload
; EGPR-NEXT:    adcq {{[-0-9]+}}(%r{{[sb]}}p), %r31 # 8-byte Folded Reload
; EGPR-NEXT:    adcq {{[-0-9]+}}(%r{{[sb]}}p), %r21 # 8-byte Folded Reload
; EGPR-NEXT:    adcq {{[-0-9]+}}(%r{{[sb]}}p), %r10 # 8-byte Folded Reload
; EGPR-NEXT:    adcq (%rsp), %r16 # 8-byte Folded Reload
; EGPR-NEXT:    adcq %r12, %rax
; EGPR-NEXT:    adcq %rbp, %rdx
; EGPR-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Reload
; EGPR-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rsi # 8-byte Reload
; EGPR-NEXT:    movq %rsi, (%rcx)
; EGPR-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rsi # 8-byte Reload
; EGPR-NEXT:    movq %rsi, 8(%rcx)
; EGPR-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rsi # 8-byte Reload
; EGPR-NEXT:    movq %rsi, 16(%rcx)
; EGPR-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rsi # 8-byte Reload
; EGPR-NEXT:    movq %rsi, 24(%rcx)
; EGPR-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rsi # 8-byte Reload
; EGPR-NEXT:    movq %rsi, 32(%rcx)
; EGPR-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rsi # 8-byte Reload
; EGPR-NEXT:    movq %rsi, 40(%rcx)
; EGPR-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rsi # 8-byte Reload
; EGPR-NEXT:    movq %rsi, 48(%rcx)
; EGPR-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rsi # 8-byte Reload
; EGPR-NEXT:    movq %rsi, 56(%rcx)
; EGPR-NEXT:    movq %r19, 64(%rcx)
; EGPR-NEXT:    movq %r27, 72(%rcx)
; EGPR-NEXT:    movq %r31, 80(%rcx)
; EGPR-NEXT:    movq %r21, 88(%rcx)
; EGPR-NEXT:    movq %r10, 96(%rcx)
; EGPR-NEXT:    movq %r16, 104(%rcx)
; EGPR-NEXT:    movq %rax, 112(%rcx)
; EGPR-NEXT:    movq %rdx, 120(%rcx)
; EGPR-NEXT:    addq $112, %rsp
; EGPR-NEXT:    popq %rbx
; EGPR-NEXT:    popq %r12
; EGPR-NEXT:    popq %r13
; EGPR-NEXT:    popq %r14
; EGPR-NEXT:    popq %r15
; EGPR-NEXT:    popq %rbp
; EGPR-NEXT:    retq
;
; EGPR-NDD-LABEL: test_1024:
; EGPR-NDD:       # %bb.0:
; EGPR-NDD-NEXT:    pushq %rbp
; EGPR-NDD-NEXT:    pushq %r15
; EGPR-NDD-NEXT:    pushq %r14
; EGPR-NDD-NEXT:    pushq %r13
; EGPR-NDD-NEXT:    pushq %r12
; EGPR-NDD-NEXT:    pushq %rbx
; EGPR-NDD-NEXT:    subq $64, %rsp
; EGPR-NDD-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NDD-NEXT:    movq %rsi, %r28
; EGPR-NDD-NEXT:    movq %rdi, %r25
; EGPR-NDD-NEXT:    movq (%rdi), %r12
; EGPR-NDD-NEXT:    movq 8(%rdi), %r16
; EGPR-NDD-NEXT:    movq 24(%rdi), %r17
; EGPR-NDD-NEXT:    movq 16(%rdi), %rbp
; EGPR-NDD-NEXT:    movq 40(%rdi), %r11
; EGPR-NDD-NEXT:    movq 32(%rdi), %r18
; EGPR-NDD-NEXT:    movq 56(%rdi), %r30
; EGPR-NDD-NEXT:    movq 48(%rdi), %r20
; EGPR-NDD-NEXT:    movq 24(%rsi), %r21
; EGPR-NDD-NEXT:    movq 16(%rsi), %r31
; EGPR-NDD-NEXT:    movq (%rsi), %r27
; EGPR-NDD-NEXT:    movq 8(%rsi), %r26
; EGPR-NDD-NEXT:    movq %r20, %rax
; EGPR-NDD-NEXT:    mulq %r27
; EGPR-NDD-NEXT:    movq %rdx, %rcx
; EGPR-NDD-NEXT:    movq %rax, %rdi
; EGPR-NDD-NEXT:    movq %r30, %rax
; EGPR-NDD-NEXT:    mulq %r27
; EGPR-NDD-NEXT:    addq %rax, %rcx
; EGPR-NDD-NEXT:    adcq $0, %rdx, %rsi
; EGPR-NDD-NEXT:    movq %r20, %rax
; EGPR-NDD-NEXT:    mulq %r26
; EGPR-NDD-NEXT:    addq %rcx, %rax, %r8
; EGPR-NDD-NEXT:    adcq %rdx, %rsi
; EGPR-NDD-NEXT:    setb %al
; EGPR-NDD-NEXT:    movzbl %al, %ecx
; EGPR-NDD-NEXT:    movq %r30, %rax
; EGPR-NDD-NEXT:    mulq %r26
; EGPR-NDD-NEXT:    addq %rsi, %rax, %r9
; EGPR-NDD-NEXT:    adcq %rcx, %rdx, %r10
; EGPR-NDD-NEXT:    movq %r18, %rax
; EGPR-NDD-NEXT:    mulq %r27
; EGPR-NDD-NEXT:    movq %rdx, %rsi
; EGPR-NDD-NEXT:    movq %rax, %rcx
; EGPR-NDD-NEXT:    movq %r11, %rax
; EGPR-NDD-NEXT:    mulq %r27
; EGPR-NDD-NEXT:    addq %rax, %rsi
; EGPR-NDD-NEXT:    adcq $0, %rdx, %r19
; EGPR-NDD-NEXT:    movq %r18, %rax
; EGPR-NDD-NEXT:    mulq %r26
; EGPR-NDD-NEXT:    addq %rax, %rsi
; EGPR-NDD-NEXT:    adcq %rdx, %r19
; EGPR-NDD-NEXT:    setb %al
; EGPR-NDD-NEXT:    movzbl %al, %r22d
; EGPR-NDD-NEXT:    movq %r11, %rax
; EGPR-NDD-NEXT:    mulq %r26
; EGPR-NDD-NEXT:    addq %r19, %rax
; EGPR-NDD-NEXT:    adcq %r22, %rdx
; EGPR-NDD-NEXT:    addq %rax, %rdi
; EGPR-NDD-NEXT:    adcq %rdx, %r8
; EGPR-NDD-NEXT:    adcq $0, %r9
; EGPR-NDD-NEXT:    adcq $0, %r10
; EGPR-NDD-NEXT:    movq %r18, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NDD-NEXT:    movq %r18, %rax
; EGPR-NDD-NEXT:    mulq %r31
; EGPR-NDD-NEXT:    movq %rdx, %r19
; EGPR-NDD-NEXT:    movq %rax, %r15
; EGPR-NDD-NEXT:    movq %r11, %rax
; EGPR-NDD-NEXT:    movq %r11, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NDD-NEXT:    mulq %r31
; EGPR-NDD-NEXT:    addq %rax, %r19
; EGPR-NDD-NEXT:    adcq $0, %rdx, %r22
; EGPR-NDD-NEXT:    movq %r18, %rax
; EGPR-NDD-NEXT:    mulq %r21
; EGPR-NDD-NEXT:    addq %rax, %r19
; EGPR-NDD-NEXT:    adcq %rdx, %r22
; EGPR-NDD-NEXT:    setb %al
; EGPR-NDD-NEXT:    movzbl %al, %r24d
; EGPR-NDD-NEXT:    movq %r11, %rax
; EGPR-NDD-NEXT:    mulq %r21
; EGPR-NDD-NEXT:    addq %r22, %rax
; EGPR-NDD-NEXT:    adcq %r24, %rdx
; EGPR-NDD-NEXT:    addq %rdi, %r15
; EGPR-NDD-NEXT:    adcq %r8, %r19, %r23
; EGPR-NDD-NEXT:    adcq $0, %rax
; EGPR-NDD-NEXT:    adcq $0, %rdx
; EGPR-NDD-NEXT:    addq %rax, %r9
; EGPR-NDD-NEXT:    adcq %rdx, %r10
; EGPR-NDD-NEXT:    setb %al
; EGPR-NDD-NEXT:    movzbl %al, %r29d
; EGPR-NDD-NEXT:    movq %r20, %rax
; EGPR-NDD-NEXT:    mulq %r31
; EGPR-NDD-NEXT:    movq %rdx, %rdi
; EGPR-NDD-NEXT:    movq %rax, %r8
; EGPR-NDD-NEXT:    movq %r30, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NDD-NEXT:    movq %r30, %rax
; EGPR-NDD-NEXT:    mulq %r31
; EGPR-NDD-NEXT:    addq %rax, %rdi
; EGPR-NDD-NEXT:    adcq $0, %rdx, %r19
; EGPR-NDD-NEXT:    movq %r20, %rax
; EGPR-NDD-NEXT:    mulq %r21
; EGPR-NDD-NEXT:    addq %rax, %rdi
; EGPR-NDD-NEXT:    adcq %rdx, %r19
; EGPR-NDD-NEXT:    setb %al
; EGPR-NDD-NEXT:    movzbl %al, %r22d
; EGPR-NDD-NEXT:    movq %r30, %rax
; EGPR-NDD-NEXT:    mulq %r21
; EGPR-NDD-NEXT:    addq %r19, %rax
; EGPR-NDD-NEXT:    adcq %r22, %rdx
; EGPR-NDD-NEXT:    addq %r8, %r9
; EGPR-NDD-NEXT:    adcq %r10, %rdi, %r11
; EGPR-NDD-NEXT:    adcq %rax, %r29
; EGPR-NDD-NEXT:    adcq $0, %rdx, %r13
; EGPR-NDD-NEXT:    movq %rbp, %rax
; EGPR-NDD-NEXT:    mulq %r27
; EGPR-NDD-NEXT:    movq %rdx, %r8
; EGPR-NDD-NEXT:    movq %rax, %rdi
; EGPR-NDD-NEXT:    movq %r17, %rax
; EGPR-NDD-NEXT:    mulq %r27
; EGPR-NDD-NEXT:    addq %rax, %r8
; EGPR-NDD-NEXT:    adcq $0, %rdx, %r10
; EGPR-NDD-NEXT:    movq %rbp, %rax
; EGPR-NDD-NEXT:    mulq %r26
; EGPR-NDD-NEXT:    addq %rax, %r8
; EGPR-NDD-NEXT:    adcq %rdx, %r10
; EGPR-NDD-NEXT:    setb %al
; EGPR-NDD-NEXT:    movzbl %al, %r19d
; EGPR-NDD-NEXT:    movq %r17, %rax
; EGPR-NDD-NEXT:    mulq %r26
; EGPR-NDD-NEXT:    addq %rax, %r10
; EGPR-NDD-NEXT:    adcq %rdx, %r19
; EGPR-NDD-NEXT:    movq %r12, %rax
; EGPR-NDD-NEXT:    mulq %r27
; EGPR-NDD-NEXT:    movq %rdx, %r22
; EGPR-NDD-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NDD-NEXT:    movq %r16, %rax
; EGPR-NDD-NEXT:    mulq %r27
; EGPR-NDD-NEXT:    addq %rax, %r22
; EGPR-NDD-NEXT:    adcq $0, %rdx, %r24
; EGPR-NDD-NEXT:    movq %r12, %rax
; EGPR-NDD-NEXT:    mulq %r26
; EGPR-NDD-NEXT:    addq %r22, %rax
; EGPR-NDD-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NDD-NEXT:    adcq %rdx, %r24
; EGPR-NDD-NEXT:    setb %r22b
; EGPR-NDD-NEXT:    movq %r16, %rax
; EGPR-NDD-NEXT:    mulq %r26
; EGPR-NDD-NEXT:    addq %r24, %rax
; EGPR-NDD-NEXT:    movzbl %r22b, %r22d
; EGPR-NDD-NEXT:    adcq %r22, %rdx
; EGPR-NDD-NEXT:    addq %rax, %rdi
; EGPR-NDD-NEXT:    adcq %rdx, %r8
; EGPR-NDD-NEXT:    adcq $0, %r10
; EGPR-NDD-NEXT:    adcq $0, %r19
; EGPR-NDD-NEXT:    movq %r12, %rax
; EGPR-NDD-NEXT:    mulq %r31
; EGPR-NDD-NEXT:    movq %rdx, %r22
; EGPR-NDD-NEXT:    movq %rax, %r24
; EGPR-NDD-NEXT:    movq %r16, %rax
; EGPR-NDD-NEXT:    mulq %r31
; EGPR-NDD-NEXT:    addq %rax, %r22
; EGPR-NDD-NEXT:    adcq $0, %rdx, %rbx
; EGPR-NDD-NEXT:    movq %r12, %rax
; EGPR-NDD-NEXT:    mulq %r21
; EGPR-NDD-NEXT:    addq %rax, %r22
; EGPR-NDD-NEXT:    adcq %rdx, %rbx
; EGPR-NDD-NEXT:    setb %r14b
; EGPR-NDD-NEXT:    movq %r16, %rax
; EGPR-NDD-NEXT:    mulq %r21
; EGPR-NDD-NEXT:    addq %rbx, %rax
; EGPR-NDD-NEXT:    movzbl %r14b, %ebx
; EGPR-NDD-NEXT:    adcq %rbx, %rdx
; EGPR-NDD-NEXT:    addq %r24, %rdi
; EGPR-NDD-NEXT:    movq %rdi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NDD-NEXT:    adcq %r22, %r8
; EGPR-NDD-NEXT:    movq %r8, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NDD-NEXT:    adcq $0, %rax
; EGPR-NDD-NEXT:    adcq $0, %rdx
; EGPR-NDD-NEXT:    addq %rax, %r10
; EGPR-NDD-NEXT:    adcq %rdx, %r19
; EGPR-NDD-NEXT:    setb %dil
; EGPR-NDD-NEXT:    movq %rbp, %rax
; EGPR-NDD-NEXT:    mulq %r31
; EGPR-NDD-NEXT:    movq %rdx, %r8
; EGPR-NDD-NEXT:    movq %rax, %r22
; EGPR-NDD-NEXT:    movq %r17, %r30
; EGPR-NDD-NEXT:    movq %r17, %rax
; EGPR-NDD-NEXT:    mulq %r31
; EGPR-NDD-NEXT:    addq %rax, %r8
; EGPR-NDD-NEXT:    adcq $0, %rdx, %r24
; EGPR-NDD-NEXT:    movq %rbp, %rax
; EGPR-NDD-NEXT:    mulq %r21
; EGPR-NDD-NEXT:    addq %rax, %r8
; EGPR-NDD-NEXT:    adcq %rdx, %r24
; EGPR-NDD-NEXT:    setb %bl
; EGPR-NDD-NEXT:    movq %r17, %rax
; EGPR-NDD-NEXT:    mulq %r21
; EGPR-NDD-NEXT:    addq %r24, %rax
; EGPR-NDD-NEXT:    movzbl %bl, %r24d
; EGPR-NDD-NEXT:    adcq %r24, %rdx
; EGPR-NDD-NEXT:    addq %r22, %r10
; EGPR-NDD-NEXT:    adcq %r8, %r19
; EGPR-NDD-NEXT:    movzbl %dil, %edi
; EGPR-NDD-NEXT:    adcq %rdi, %rax
; EGPR-NDD-NEXT:    adcq $0, %rdx
; EGPR-NDD-NEXT:    addq %r10, %rcx
; EGPR-NDD-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NDD-NEXT:    movq 32(%r28), %r17
; EGPR-NDD-NEXT:    adcq %r19, %rsi, %r14
; EGPR-NDD-NEXT:    adcq %rax, %r15
; EGPR-NDD-NEXT:    adcq %rdx, %r23, %rbx
; EGPR-NDD-NEXT:    adcq $0, %r9
; EGPR-NDD-NEXT:    movq %r9, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NDD-NEXT:    adcq $0, %r11
; EGPR-NDD-NEXT:    movq %r11, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NDD-NEXT:    adcq $0, %r29
; EGPR-NDD-NEXT:    movq %r29, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NDD-NEXT:    adcq $0, %r13, %r29
; EGPR-NDD-NEXT:    movq %rbp, %rax
; EGPR-NDD-NEXT:    mulq %r17
; EGPR-NDD-NEXT:    movq %rdx, %rdi
; EGPR-NDD-NEXT:    movq %rax, %rsi
; EGPR-NDD-NEXT:    movq %r30, %rax
; EGPR-NDD-NEXT:    mulq %r17
; EGPR-NDD-NEXT:    addq %rax, %rdi
; EGPR-NDD-NEXT:    adcq $0, %rdx, %r9
; EGPR-NDD-NEXT:    movq 40(%r28), %r23
; EGPR-NDD-NEXT:    movq %rbp, %rax
; EGPR-NDD-NEXT:    mulq %r23
; EGPR-NDD-NEXT:    addq %rax, %rdi
; EGPR-NDD-NEXT:    adcq %rdx, %r9
; EGPR-NDD-NEXT:    setb %r19b
; EGPR-NDD-NEXT:    movq %r30, %rax
; EGPR-NDD-NEXT:    mulq %r23
; EGPR-NDD-NEXT:    addq %rax, %r9
; EGPR-NDD-NEXT:    movzbl %r19b, %eax
; EGPR-NDD-NEXT:    adcq %rax, %rdx, %r24
; EGPR-NDD-NEXT:    movq %r12, %rax
; EGPR-NDD-NEXT:    mulq %r17
; EGPR-NDD-NEXT:    movq %rdx, %r22
; EGPR-NDD-NEXT:    movq %rax, %r19
; EGPR-NDD-NEXT:    movq %r16, %rax
; EGPR-NDD-NEXT:    mulq %r17
; EGPR-NDD-NEXT:    addq %rax, %r22
; EGPR-NDD-NEXT:    adcq $0, %rdx, %r13
; EGPR-NDD-NEXT:    movq %r12, %rax
; EGPR-NDD-NEXT:    mulq %r23
; EGPR-NDD-NEXT:    addq %rax, %r22
; EGPR-NDD-NEXT:    adcq %rdx, %r13
; EGPR-NDD-NEXT:    setb %cl
; EGPR-NDD-NEXT:    movq %r16, %rax
; EGPR-NDD-NEXT:    movq %r16, %r11
; EGPR-NDD-NEXT:    mulq %r23
; EGPR-NDD-NEXT:    addq %r13, %rax
; EGPR-NDD-NEXT:    movzbl %cl, %ecx
; EGPR-NDD-NEXT:    adcq %rdx, %rcx
; EGPR-NDD-NEXT:    addq %rax, %rsi, %r8
; EGPR-NDD-NEXT:    adcq %rcx, %rdi, %r10
; EGPR-NDD-NEXT:    adcq $0, %r9, %r13
; EGPR-NDD-NEXT:    adcq $0, %r24
; EGPR-NDD-NEXT:    movq 48(%r28), %r16
; EGPR-NDD-NEXT:    movq %r12, %rax
; EGPR-NDD-NEXT:    mulq %r16
; EGPR-NDD-NEXT:    movq %rdx, %r9
; EGPR-NDD-NEXT:    movq %rax, %rdi
; EGPR-NDD-NEXT:    movq %r11, %rax
; EGPR-NDD-NEXT:    movq %r11, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NDD-NEXT:    mulq %r16
; EGPR-NDD-NEXT:    addq %rax, %r9
; EGPR-NDD-NEXT:    adcq $0, %rdx, %rcx
; EGPR-NDD-NEXT:    movq 56(%r28), %r18
; EGPR-NDD-NEXT:    movq %r12, %rax
; EGPR-NDD-NEXT:    mulq %r18
; EGPR-NDD-NEXT:    addq %rax, %r9
; EGPR-NDD-NEXT:    adcq %rdx, %rcx
; EGPR-NDD-NEXT:    setb %sil
; EGPR-NDD-NEXT:    movq %r11, %rax
; EGPR-NDD-NEXT:    mulq %r18
; EGPR-NDD-NEXT:    addq %rcx, %rax
; EGPR-NDD-NEXT:    movzbl %sil, %ecx
; EGPR-NDD-NEXT:    adcq %rdx, %rcx
; EGPR-NDD-NEXT:    addq %r8, %rdi, %r11
; EGPR-NDD-NEXT:    adcq %r10, %r9
; EGPR-NDD-NEXT:    adcq $0, %rax
; EGPR-NDD-NEXT:    adcq $0, %rcx
; EGPR-NDD-NEXT:    addq %rax, %r13
; EGPR-NDD-NEXT:    adcq %rcx, %r24, %rdi
; EGPR-NDD-NEXT:    setb %sil
; EGPR-NDD-NEXT:    movq %rbp, %rax
; EGPR-NDD-NEXT:    mulq %r16
; EGPR-NDD-NEXT:    movq %rdx, %r8
; EGPR-NDD-NEXT:    movq %rax, %r10
; EGPR-NDD-NEXT:    movq %r30, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NDD-NEXT:    movq %r30, %rax
; EGPR-NDD-NEXT:    mulq %r16
; EGPR-NDD-NEXT:    addq %rax, %r8
; EGPR-NDD-NEXT:    adcq $0, %rdx, %r24
; EGPR-NDD-NEXT:    movq %rbp, %rax
; EGPR-NDD-NEXT:    mulq %r18
; EGPR-NDD-NEXT:    addq %rax, %r8
; EGPR-NDD-NEXT:    adcq %rdx, %r24
; EGPR-NDD-NEXT:    setb %cl
; EGPR-NDD-NEXT:    movq %r30, %rax
; EGPR-NDD-NEXT:    mulq %r18
; EGPR-NDD-NEXT:    addq %r24, %rax
; EGPR-NDD-NEXT:    movzbl %cl, %ecx
; EGPR-NDD-NEXT:    adcq %rdx, %rcx
; EGPR-NDD-NEXT:    addq %r13, %r10
; EGPR-NDD-NEXT:    adcq %r8, %rdi
; EGPR-NDD-NEXT:    movzbl %sil, %edx
; EGPR-NDD-NEXT:    adcq %rdx, %rax
; EGPR-NDD-NEXT:    adcq $0, %rcx
; EGPR-NDD-NEXT:    addq {{[-0-9]+}}(%r{{[sb]}}p), %r19 # 8-byte Folded Reload
; EGPR-NDD-NEXT:    movq %r19, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NDD-NEXT:    adcq %r14, %r22
; EGPR-NDD-NEXT:    movq %r22, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NDD-NEXT:    adcq %r15, %r11
; EGPR-NDD-NEXT:    movq %r11, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NDD-NEXT:    adcq %rbx, %r9
; EGPR-NDD-NEXT:    movq %r9, (%rsp) # 8-byte Spill
; EGPR-NDD-NEXT:    adcq $0, %r10
; EGPR-NDD-NEXT:    adcq $0, %rdi
; EGPR-NDD-NEXT:    adcq $0, %rax
; EGPR-NDD-NEXT:    adcq $0, %rcx, %rdx
; EGPR-NDD-NEXT:    addq %r10, {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Folded Reload
; EGPR-NDD-NEXT:    adcq %rdi, {{[-0-9]+}}(%r{{[sb]}}p), %rsi # 8-byte Folded Reload
; EGPR-NDD-NEXT:    movq %rsi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NDD-NEXT:    adcq %rax, {{[-0-9]+}}(%r{{[sb]}}p), %rdi # 8-byte Folded Reload
; EGPR-NDD-NEXT:    adcq %rdx, %r29
; EGPR-NDD-NEXT:    setb %bl
; EGPR-NDD-NEXT:    movq %r20, %rax
; EGPR-NDD-NEXT:    mulq %r17
; EGPR-NDD-NEXT:    movq %rdx, %r8
; EGPR-NDD-NEXT:    movq %rax, %rsi
; EGPR-NDD-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r11 # 8-byte Reload
; EGPR-NDD-NEXT:    movq %r11, %rax
; EGPR-NDD-NEXT:    mulq %r17
; EGPR-NDD-NEXT:    addq %rax, %r8
; EGPR-NDD-NEXT:    adcq $0, %rdx, %r9
; EGPR-NDD-NEXT:    movq %r20, %rax
; EGPR-NDD-NEXT:    movq %r20, %r30
; EGPR-NDD-NEXT:    mulq %r23
; EGPR-NDD-NEXT:    addq %rax, %r8
; EGPR-NDD-NEXT:    adcq %rdx, %r9
; EGPR-NDD-NEXT:    setb %r10b
; EGPR-NDD-NEXT:    movq %r11, %rax
; EGPR-NDD-NEXT:    movq %r11, %r13
; EGPR-NDD-NEXT:    mulq %r23
; EGPR-NDD-NEXT:    addq %rax, %r9
; EGPR-NDD-NEXT:    movzbl %r10b, %eax
; EGPR-NDD-NEXT:    adcq %rax, %rdx, %r10
; EGPR-NDD-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r20 # 8-byte Reload
; EGPR-NDD-NEXT:    movq %r20, %rax
; EGPR-NDD-NEXT:    mulq %r17
; EGPR-NDD-NEXT:    movq %rdx, %r11
; EGPR-NDD-NEXT:    movq %rax, %r19
; EGPR-NDD-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r14 # 8-byte Reload
; EGPR-NDD-NEXT:    movq %r14, %rax
; EGPR-NDD-NEXT:    mulq %r17
; EGPR-NDD-NEXT:    addq %rax, %r11
; EGPR-NDD-NEXT:    adcq $0, %rdx, %r24
; EGPR-NDD-NEXT:    movq %r20, %rax
; EGPR-NDD-NEXT:    movq %r20, %r15
; EGPR-NDD-NEXT:    mulq %r23
; EGPR-NDD-NEXT:    addq %r11, %rax, %r22
; EGPR-NDD-NEXT:    adcq %rdx, %r24
; EGPR-NDD-NEXT:    setb %r11b
; EGPR-NDD-NEXT:    movq %r14, %r20
; EGPR-NDD-NEXT:    movq %r14, %rax
; EGPR-NDD-NEXT:    mulq %r23
; EGPR-NDD-NEXT:    addq %r24, %rax
; EGPR-NDD-NEXT:    movzbl %r11b, %r11d
; EGPR-NDD-NEXT:    adcq %r11, %rdx
; EGPR-NDD-NEXT:    addq %rax, %rsi
; EGPR-NDD-NEXT:    adcq %rdx, %r8
; EGPR-NDD-NEXT:    adcq $0, %r9
; EGPR-NDD-NEXT:    adcq $0, %r10
; EGPR-NDD-NEXT:    movq %r15, %rax
; EGPR-NDD-NEXT:    mulq %r16
; EGPR-NDD-NEXT:    movq %rdx, %r11
; EGPR-NDD-NEXT:    movq %rax, %r24
; EGPR-NDD-NEXT:    movq %r14, %rax
; EGPR-NDD-NEXT:    mulq %r16
; EGPR-NDD-NEXT:    addq %rax, %r11
; EGPR-NDD-NEXT:    adcq $0, %rdx, %r14
; EGPR-NDD-NEXT:    movq %r15, %rax
; EGPR-NDD-NEXT:    mulq %r18
; EGPR-NDD-NEXT:    addq %rax, %r11
; EGPR-NDD-NEXT:    adcq %rdx, %r14
; EGPR-NDD-NEXT:    setb %r15b
; EGPR-NDD-NEXT:    movq %r20, %rax
; EGPR-NDD-NEXT:    mulq %r18
; EGPR-NDD-NEXT:    addq %r14, %rax
; EGPR-NDD-NEXT:    movzbl %r15b, %r14d
; EGPR-NDD-NEXT:    adcq %r14, %rdx
; EGPR-NDD-NEXT:    addq %r24, %rsi
; EGPR-NDD-NEXT:    adcq %r11, %r8
; EGPR-NDD-NEXT:    adcq $0, %rax
; EGPR-NDD-NEXT:    adcq $0, %rdx
; EGPR-NDD-NEXT:    addq %rax, %r9
; EGPR-NDD-NEXT:    adcq %rdx, %r10
; EGPR-NDD-NEXT:    setb %r11b
; EGPR-NDD-NEXT:    movq %r30, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NDD-NEXT:    movq %r30, %rax
; EGPR-NDD-NEXT:    mulq %r16
; EGPR-NDD-NEXT:    movq %rdx, %r24
; EGPR-NDD-NEXT:    movq %rax, %r14
; EGPR-NDD-NEXT:    movq %r13, %r20
; EGPR-NDD-NEXT:    movq %r13, %rax
; EGPR-NDD-NEXT:    mulq %r16
; EGPR-NDD-NEXT:    addq %rax, %r24
; EGPR-NDD-NEXT:    adcq $0, %rdx, %r15
; EGPR-NDD-NEXT:    movq %r30, %rax
; EGPR-NDD-NEXT:    mulq %r18
; EGPR-NDD-NEXT:    addq %rax, %r24
; EGPR-NDD-NEXT:    adcq %rdx, %r15
; EGPR-NDD-NEXT:    setb %r13b
; EGPR-NDD-NEXT:    movq %r20, %rax
; EGPR-NDD-NEXT:    mulq %r18
; EGPR-NDD-NEXT:    addq %r15, %rax
; EGPR-NDD-NEXT:    movzbl %r13b, %r15d
; EGPR-NDD-NEXT:    adcq %r15, %rdx
; EGPR-NDD-NEXT:    addq %r14, %r9
; EGPR-NDD-NEXT:    adcq %r24, %r10
; EGPR-NDD-NEXT:    movzbl %r11b, %r11d
; EGPR-NDD-NEXT:    adcq %r11, %rax
; EGPR-NDD-NEXT:    adcq $0, %rdx
; EGPR-NDD-NEXT:    addq %r19, %rcx
; EGPR-NDD-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NDD-NEXT:    adcq {{[-0-9]+}}(%r{{[sb]}}p), %r22 # 8-byte Folded Reload
; EGPR-NDD-NEXT:    movq %r22, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NDD-NEXT:    adcq %rdi, %rsi
; EGPR-NDD-NEXT:    movq %rsi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NDD-NEXT:    adcq %r29, %r8
; EGPR-NDD-NEXT:    movq %r8, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NDD-NEXT:    movzbl %bl, %ecx
; EGPR-NDD-NEXT:    adcq %r9, %rcx
; EGPR-NDD-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NDD-NEXT:    adcq $0, %r10
; EGPR-NDD-NEXT:    movq %r10, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NDD-NEXT:    adcq $0, %rax
; EGPR-NDD-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NDD-NEXT:    adcq $0, %rdx
; EGPR-NDD-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NDD-NEXT:    movq 64(%r25), %r20
; EGPR-NDD-NEXT:    movq %r31, %rax
; EGPR-NDD-NEXT:    mulq %r20
; EGPR-NDD-NEXT:    movq %rdx, %rsi
; EGPR-NDD-NEXT:    movq %rax, %rcx
; EGPR-NDD-NEXT:    movq %r21, %rax
; EGPR-NDD-NEXT:    mulq %r20
; EGPR-NDD-NEXT:    addq %rsi, %rax, %rdi
; EGPR-NDD-NEXT:    adcq $0, %rdx, %r8
; EGPR-NDD-NEXT:    movq 72(%r25), %rsi
; EGPR-NDD-NEXT:    movq %r31, %rax
; EGPR-NDD-NEXT:    mulq %rsi
; EGPR-NDD-NEXT:    addq %rax, %rdi
; EGPR-NDD-NEXT:    adcq %rdx, %r8
; EGPR-NDD-NEXT:    setb %r9b
; EGPR-NDD-NEXT:    movq %r21, %rax
; EGPR-NDD-NEXT:    mulq %rsi
; EGPR-NDD-NEXT:    addq %rax, %r8
; EGPR-NDD-NEXT:    movzbl %r9b, %eax
; EGPR-NDD-NEXT:    adcq %rax, %rdx, %r9
; EGPR-NDD-NEXT:    movq %r27, %rax
; EGPR-NDD-NEXT:    mulq %r20
; EGPR-NDD-NEXT:    movq %rdx, %r10
; EGPR-NDD-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; EGPR-NDD-NEXT:    movq %r26, %rax
; EGPR-NDD-NEXT:    mulq %r20
; EGPR-NDD-NEXT:    addq %rax, %r10
; EGPR-NDD-NEXT:    adcq $0, %rdx, %r11
; EGPR-NDD-NEXT:    movq %r27, %rax
; EGPR-NDD-NEXT:    mulq %rsi
; EGPR-NDD-NEXT:    addq %r10, %rax, %r13
; EGPR-NDD-NEXT:    adcq %rdx, %r11
; EGPR-NDD-NEXT:    setb %r10b
; EGPR-NDD-NEXT:    movq %r26, %rax
; EGPR-NDD-NEXT:    mulq %rsi
; EGPR-NDD-NEXT:    addq %r11, %rax
; EGPR-NDD-NEXT:    movzbl %r10b, %r10d
; EGPR-NDD-NEXT:    adcq %r10, %rdx
; EGPR-NDD-NEXT:    addq %rax, %rcx, %r15
; EGPR-NDD-NEXT:    adcq %rdx, %rdi
; EGPR-NDD-NEXT:    adcq $0, %r8
; EGPR-NDD-NEXT:    adcq $0, %r9
; EGPR-NDD-NEXT:    movq 80(%r25), %r29
; EGPR-NDD-NEXT:    movq %r27, %rax
; EGPR-NDD-NEXT:    mulq %r29
; EGPR-NDD-NEXT:    movq %rdx, %rcx
; EGPR-NDD-NEXT:    movq %rax, %r10
; EGPR-NDD-NEXT:    movq %r26, %rax
; EGPR-NDD-NEXT:    mulq %r29
; EGPR-NDD-NEXT:    addq %rcx, %rax, %r11
; EGPR-NDD-NEXT:    adcq $0, %rdx, %r19
; EGPR-NDD-NEXT:    movq 88(%r25), %rcx
; EGPR-NDD-NEXT:    movq %r27, %rax
; EGPR-NDD-NEXT:    mulq %rcx
; EGPR-NDD-NEXT:    addq %rax, %r11
; EGPR-NDD-NEXT:    adcq %rdx, %r19
; EGPR-NDD-NEXT:    setb %r22b
; EGPR-NDD-NEXT:    movq %r26, %rax
; EGPR-NDD-NEXT:    mulq %rcx
; EGPR-NDD-NEXT:    addq %r19, %rax
; EGPR-NDD-NEXT:    movzbl %r22b, %r19d
; EGPR-NDD-NEXT:    adcq %r19, %rdx
; EGPR-NDD-NEXT:    addq %r10, %r15
; EGPR-NDD-NEXT:    adcq %rdi, %r11, %r14
; EGPR-NDD-NEXT:    adcq $0, %rax
; EGPR-NDD-NEXT:    adcq $0, %rdx
; EGPR-NDD-NEXT:    addq %rax, %r8
; EGPR-NDD-NEXT:    adcq %rdx, %r9, %r24
; EGPR-NDD-NEXT:    setb %dil
; EGPR-NDD-NEXT:    movq %r31, %rax
; EGPR-NDD-NEXT:    mulq %r29
; EGPR-NDD-NEXT:    movq %rdx, %r9
; EGPR-NDD-NEXT:    movq %rax, %r10
; EGPR-NDD-NEXT:    movq %r21, %rax
; EGPR-NDD-NEXT:    mulq %r29
; EGPR-NDD-NEXT:    addq %rax, %r9
; EGPR-NDD-NEXT:    adcq $0, %rdx, %r11
; EGPR-NDD-NEXT:    movq %r31, %rax
; EGPR-NDD-NEXT:    mulq %rcx
; EGPR-NDD-NEXT:    addq %r9, %rax, %r19
; EGPR-NDD-NEXT:    adcq %rdx, %r11
; EGPR-NDD-NEXT:    setb %r9b
; EGPR-NDD-NEXT:    movq %r21, %rax
; EGPR-NDD-NEXT:    mulq %rcx
; EGPR-NDD-NEXT:    addq %r11, %rax
; EGPR-NDD-NEXT:    movzbl %r9b, %r9d
; EGPR-NDD-NEXT:    adcq %r9, %rdx
; EGPR-NDD-NEXT:    addq %r8, %r10, %r9
; EGPR-NDD-NEXT:    adcq %r19, %r24
; EGPR-NDD-NEXT:    movzbl %dil, %r19d
; EGPR-NDD-NEXT:    adcq %rax, %r19
; EGPR-NDD-NEXT:    adcq $0, %rdx, %r22
; EGPR-NDD-NEXT:    imulq %r17, %rcx
; EGPR-NDD-NEXT:    movq %r17, %rax
; EGPR-NDD-NEXT:    mulq %r29
; EGPR-NDD-NEXT:    movq %rax, %rdi
; EGPR-NDD-NEXT:    addq %rdx, %rcx
; EGPR-NDD-NEXT:    imulq %r23, %r29
; EGPR-NDD-NEXT:    addq %r29, %rcx
; EGPR-NDD-NEXT:    imulq %rsi, %r16, %r8
; EGPR-NDD-NEXT:    movq %r16, %rax
; EGPR-NDD-NEXT:    mulq %r20
; EGPR-NDD-NEXT:    addq %r8, %rdx
; EGPR-NDD-NEXT:    imulq %r20, %r18
; EGPR-NDD-NEXT:    addq %r18, %rdx
; EGPR-NDD-NEXT:    addq %rdi, %rax, %r8
; EGPR-NDD-NEXT:    adcq %rcx, %rdx, %r10
; EGPR-NDD-NEXT:    movq %r20, %rax
; EGPR-NDD-NEXT:    mulq %r17
; EGPR-NDD-NEXT:    movq %rdx, %rdi
; EGPR-NDD-NEXT:    movq %rax, %rcx
; EGPR-NDD-NEXT:    movq %rsi, %rax
; EGPR-NDD-NEXT:    mulq %r17
; EGPR-NDD-NEXT:    addq %rax, %rdi
; EGPR-NDD-NEXT:    adcq $0, %rdx, %r11
; EGPR-NDD-NEXT:    movq %r20, %rax
; EGPR-NDD-NEXT:    mulq %r23
; EGPR-NDD-NEXT:    addq %rax, %rdi
; EGPR-NDD-NEXT:    adcq %rdx, %r11
; EGPR-NDD-NEXT:    setb %r16b
; EGPR-NDD-NEXT:    movq %rsi, %rax
; EGPR-NDD-NEXT:    mulq %r23
; EGPR-NDD-NEXT:    addq %r11, %rax
; EGPR-NDD-NEXT:    movzbl %r16b, %esi
; EGPR-NDD-NEXT:    adcq %rsi, %rdx
; EGPR-NDD-NEXT:    addq %r8, %rax, %rsi
; EGPR-NDD-NEXT:    adcq %r10, %rdx, %r8
; EGPR-NDD-NEXT:    movq 112(%r25), %r10
; EGPR-NDD-NEXT:    movq %r27, %rax
; EGPR-NDD-NEXT:    mulq %r10
; EGPR-NDD-NEXT:    movq %rax, %r11
; EGPR-NDD-NEXT:    imulq %r26, %r10
; EGPR-NDD-NEXT:    addq %r10, %rdx
; EGPR-NDD-NEXT:    imulq 120(%r25), %r27, %rax
; EGPR-NDD-NEXT:    leaq (%rdx,%rax), %r10
; EGPR-NDD-NEXT:    movq 96(%r25), %r16
; EGPR-NDD-NEXT:    movq 104(%r25), %r17
; EGPR-NDD-NEXT:    imulq %r17, %r31, %r18
; EGPR-NDD-NEXT:    movq %r31, %rax
; EGPR-NDD-NEXT:    mulq %r16
; EGPR-NDD-NEXT:    addq %r18, %rdx
; EGPR-NDD-NEXT:    imulq %r16, %r21, %r30
; EGPR-NDD-NEXT:    addq %r30, %rdx
; EGPR-NDD-NEXT:    addq %rax, %r11
; EGPR-NDD-NEXT:    adcq %rdx, %r10
; EGPR-NDD-NEXT:    movq %r16, %rax
; EGPR-NDD-NEXT:    mulq %r27
; EGPR-NDD-NEXT:    movq %rdx, %r18
; EGPR-NDD-NEXT:    movq %rax, %r23
; EGPR-NDD-NEXT:    movq %r17, %rax
; EGPR-NDD-NEXT:    mulq %r27
; EGPR-NDD-NEXT:    addq %rax, %r18
; EGPR-NDD-NEXT:    adcq $0, %rdx, %r25
; EGPR-NDD-NEXT:    movq %r16, %rax
; EGPR-NDD-NEXT:    mulq %r26
; EGPR-NDD-NEXT:    addq %rax, %r18
; EGPR-NDD-NEXT:    adcq %rdx, %r25
; EGPR-NDD-NEXT:    setb %r16b
; EGPR-NDD-NEXT:    movq %r17, %rax
; EGPR-NDD-NEXT:    mulq %r26
; EGPR-NDD-NEXT:    addq %r25, %rax
; EGPR-NDD-NEXT:    movzbl %r16b, %r16d
; EGPR-NDD-NEXT:    adcq %r16, %rdx
; EGPR-NDD-NEXT:    addq %r11, %rax
; EGPR-NDD-NEXT:    adcq %r10, %rdx
; EGPR-NDD-NEXT:    addq %r23, %rcx
; EGPR-NDD-NEXT:    adcq %r18, %rdi
; EGPR-NDD-NEXT:    adcq %rsi, %rax
; EGPR-NDD-NEXT:    adcq %r8, %rdx
; EGPR-NDD-NEXT:    addq %rcx, %r9, %r20
; EGPR-NDD-NEXT:    adcq %rdi, %r24, %rbx
; EGPR-NDD-NEXT:    adcq %rax, %r19, %r29
; EGPR-NDD-NEXT:    adcq %rdx, %r22, %r8
; EGPR-NDD-NEXT:    movq 80(%r28), %r27
; EGPR-NDD-NEXT:    movq %r27, %rax
; EGPR-NDD-NEXT:    mulq %r12
; EGPR-NDD-NEXT:    movq %rax, %rsi
; EGPR-NDD-NEXT:    movq %rdx, %rcx
; EGPR-NDD-NEXT:    movq 88(%r28), %r26
; EGPR-NDD-NEXT:    movq %r26, %rax
; EGPR-NDD-NEXT:    mulq %r12
; EGPR-NDD-NEXT:    addq %rax, %rcx
; EGPR-NDD-NEXT:    adcq $0, %rdx, %rdi
; EGPR-NDD-NEXT:    movq %r27, %rax
; EGPR-NDD-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r21 # 8-byte Reload
; EGPR-NDD-NEXT:    mulq %r21
; EGPR-NDD-NEXT:    addq %rcx, %rax, %r10
; EGPR-NDD-NEXT:    adcq %rdx, %rdi
; EGPR-NDD-NEXT:    setb %cl
; EGPR-NDD-NEXT:    movq %r26, %rax
; EGPR-NDD-NEXT:    mulq %r21
; EGPR-NDD-NEXT:    addq %rax, %rdi
; EGPR-NDD-NEXT:    movzbl %cl, %eax
; EGPR-NDD-NEXT:    adcq %rax, %rdx, %r11
; EGPR-NDD-NEXT:    movq 64(%r28), %rcx
; EGPR-NDD-NEXT:    movq %rcx, %rax
; EGPR-NDD-NEXT:    mulq %r12
; EGPR-NDD-NEXT:    movq %rax, %r9
; EGPR-NDD-NEXT:    movq %rdx, %r16
; EGPR-NDD-NEXT:    movq 72(%r28), %r31
; EGPR-NDD-NEXT:    movq %r31, %rax
; EGPR-NDD-NEXT:    mulq %r12
; EGPR-NDD-NEXT:    addq %rax, %r16
; EGPR-NDD-NEXT:    adcq $0, %rdx, %r17
; EGPR-NDD-NEXT:    movq %rcx, %rax
; EGPR-NDD-NEXT:    mulq %r21
; EGPR-NDD-NEXT:    addq %r16, %rax, %r30
; EGPR-NDD-NEXT:    adcq %rdx, %r17
; EGPR-NDD-NEXT:    setb %r16b
; EGPR-NDD-NEXT:    movq %r31, %rax
; EGPR-NDD-NEXT:    mulq %r21
; EGPR-NDD-NEXT:    addq %r17, %rax
; EGPR-NDD-NEXT:    movzbl %r16b, %r16d
; EGPR-NDD-NEXT:    adcq %r16, %rdx
; EGPR-NDD-NEXT:    addq %rax, %rsi
; EGPR-NDD-NEXT:    adcq %rdx, %r10, %r16
; EGPR-NDD-NEXT:    adcq $0, %rdi, %r17
; EGPR-NDD-NEXT:    adcq $0, %r11
; EGPR-NDD-NEXT:    movq %rcx, %rax
; EGPR-NDD-NEXT:    mulq %rbp
; EGPR-NDD-NEXT:    movq %rdx, %rdi
; EGPR-NDD-NEXT:    movq %rax, %r10
; EGPR-NDD-NEXT:    movq %r31, %rax
; EGPR-NDD-NEXT:    mulq %rbp
; EGPR-NDD-NEXT:    addq %rax, %rdi
; EGPR-NDD-NEXT:    adcq $0, %rdx, %r18
; EGPR-NDD-NEXT:    movq %rcx, %rax
; EGPR-NDD-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r23 # 8-byte Reload
; EGPR-NDD-NEXT:    mulq %r23
; EGPR-NDD-NEXT:    addq %rax, %rdi
; EGPR-NDD-NEXT:    adcq %rdx, %r18
; EGPR-NDD-NEXT:    setb %r19b
; EGPR-NDD-NEXT:    movq %r31, %rax
; EGPR-NDD-NEXT:    mulq %r23
; EGPR-NDD-NEXT:    addq %r18, %rax
; EGPR-NDD-NEXT:    movzbl %r19b, %r18d
; EGPR-NDD-NEXT:    adcq %r18, %rdx
; EGPR-NDD-NEXT:    addq %rsi, %r10
; EGPR-NDD-NEXT:    adcq %r16, %rdi
; EGPR-NDD-NEXT:    adcq $0, %rax
; EGPR-NDD-NEXT:    adcq $0, %rdx
; EGPR-NDD-NEXT:    addq %rax, %r17
; EGPR-NDD-NEXT:    adcq %rdx, %r11
; EGPR-NDD-NEXT:    setb %sil
; EGPR-NDD-NEXT:    movq %r27, %rax
; EGPR-NDD-NEXT:    mulq %rbp
; EGPR-NDD-NEXT:    movq %rdx, %r16
; EGPR-NDD-NEXT:    movq %rax, %r19
; EGPR-NDD-NEXT:    movq %r26, %rax
; EGPR-NDD-NEXT:    mulq %rbp
; EGPR-NDD-NEXT:    addq %rax, %r16
; EGPR-NDD-NEXT:    adcq $0, %rdx, %r18
; EGPR-NDD-NEXT:    movq %r27, %rax
; EGPR-NDD-NEXT:    mulq %r23
; EGPR-NDD-NEXT:    addq %rax, %r16
; EGPR-NDD-NEXT:    adcq %rdx, %r18
; EGPR-NDD-NEXT:    setb %r22b
; EGPR-NDD-NEXT:    movq %r26, %rax
; EGPR-NDD-NEXT:    mulq %r23
; EGPR-NDD-NEXT:    addq %r18, %rax
; EGPR-NDD-NEXT:    movzbl %r22b, %r18d
; EGPR-NDD-NEXT:    adcq %r18, %rdx
; EGPR-NDD-NEXT:    addq %r17, %r19
; EGPR-NDD-NEXT:    adcq %r11, %r16, %r22
; EGPR-NDD-NEXT:    movzbl %sil, %r24d
; EGPR-NDD-NEXT:    adcq %rax, %r24
; EGPR-NDD-NEXT:    adcq $0, %rdx, %rsi
; EGPR-NDD-NEXT:    movq 96(%r28), %r16
; EGPR-NDD-NEXT:    imulq %r23, %r16, %r11
; EGPR-NDD-NEXT:    movq %r16, %rax
; EGPR-NDD-NEXT:    mulq %rbp
; EGPR-NDD-NEXT:    movq %rax, %r17
; EGPR-NDD-NEXT:    addq %r11, %rdx
; EGPR-NDD-NEXT:    movq 104(%r28), %r18
; EGPR-NDD-NEXT:    imulq %r18, %rbp
; EGPR-NDD-NEXT:    addq %rdx, %rbp
; EGPR-NDD-NEXT:    movq 112(%r28), %rax
; EGPR-NDD-NEXT:    imulq %r21, %rax, %r11
; EGPR-NDD-NEXT:    mulq %r12
; EGPR-NDD-NEXT:    addq %r11, %rdx
; EGPR-NDD-NEXT:    imulq 120(%r28), %r12, %r11
; EGPR-NDD-NEXT:    addq %r11, %rdx
; EGPR-NDD-NEXT:    addq %r17, %rax, %r23
; EGPR-NDD-NEXT:    adcq %rdx, %rbp
; EGPR-NDD-NEXT:    movq %r12, %rax
; EGPR-NDD-NEXT:    mulq %r16
; EGPR-NDD-NEXT:    movq %rdx, %r17
; EGPR-NDD-NEXT:    movq %rax, %r11
; EGPR-NDD-NEXT:    movq %r21, %rax
; EGPR-NDD-NEXT:    mulq %r16
; EGPR-NDD-NEXT:    addq %rax, %r17
; EGPR-NDD-NEXT:    adcq $0, %rdx, %r16
; EGPR-NDD-NEXT:    movq %r12, %rax
; EGPR-NDD-NEXT:    mulq %r18
; EGPR-NDD-NEXT:    addq %rax, %r17
; EGPR-NDD-NEXT:    adcq %rdx, %r16
; EGPR-NDD-NEXT:    setb %r25b
; EGPR-NDD-NEXT:    movq %r21, %rax
; EGPR-NDD-NEXT:    mulq %r18
; EGPR-NDD-NEXT:    addq %r16, %rax
; EGPR-NDD-NEXT:    movzbl %r25b, %r16d
; EGPR-NDD-NEXT:    adcq %r16, %rdx
; EGPR-NDD-NEXT:    addq %r23, %rax, %r16
; EGPR-NDD-NEXT:    adcq %rbp, %rdx, %r18
; EGPR-NDD-NEXT:    imulq {{[-0-9]+}}(%r{{[sb]}}p), %rcx, %r23 # 8-byte Folded Reload
; EGPR-NDD-NEXT:    movq %rcx, %rax
; EGPR-NDD-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r21 # 8-byte Reload
; EGPR-NDD-NEXT:    mulq %r21
; EGPR-NDD-NEXT:    movq %rax, %r25
; EGPR-NDD-NEXT:    addq %r23, %rdx
; EGPR-NDD-NEXT:    imulq %r21, %r31, %rax
; EGPR-NDD-NEXT:    addq %rax, %rdx, %r23
; EGPR-NDD-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r28 # 8-byte Reload
; EGPR-NDD-NEXT:    imulq %r28, %r27, %r21
; EGPR-NDD-NEXT:    movq %r27, %rax
; EGPR-NDD-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r27 # 8-byte Reload
; EGPR-NDD-NEXT:    mulq %r27
; EGPR-NDD-NEXT:    addq %r21, %rdx
; EGPR-NDD-NEXT:    imulq %r27, %r26
; EGPR-NDD-NEXT:    addq %r26, %rdx
; EGPR-NDD-NEXT:    addq %rax, %r25
; EGPR-NDD-NEXT:    adcq %rdx, %r23
; EGPR-NDD-NEXT:    movq %r27, %rax
; EGPR-NDD-NEXT:    movq %r27, %r21
; EGPR-NDD-NEXT:    mulq %rcx
; EGPR-NDD-NEXT:    movq %rdx, %r26
; EGPR-NDD-NEXT:    movq %rax, %r27
; EGPR-NDD-NEXT:    movq %r28, %rax
; EGPR-NDD-NEXT:    mulq %rcx
; EGPR-NDD-NEXT:    addq %rax, %r26
; EGPR-NDD-NEXT:    adcq $0, %rdx, %rcx
; EGPR-NDD-NEXT:    movq %r21, %rax
; EGPR-NDD-NEXT:    mulq %r31
; EGPR-NDD-NEXT:    addq %rax, %r26
; EGPR-NDD-NEXT:    adcq %rdx, %rcx
; EGPR-NDD-NEXT:    setb %r21b
; EGPR-NDD-NEXT:    movq %r28, %rax
; EGPR-NDD-NEXT:    mulq %r31
; EGPR-NDD-NEXT:    addq %rcx, %rax
; EGPR-NDD-NEXT:    movzbl %r21b, %ecx
; EGPR-NDD-NEXT:    adcq %rdx, %rcx
; EGPR-NDD-NEXT:    addq %r25, %rax
; EGPR-NDD-NEXT:    adcq %r23, %rcx
; EGPR-NDD-NEXT:    addq %r27, %r11
; EGPR-NDD-NEXT:    adcq %r26, %r17
; EGPR-NDD-NEXT:    adcq %r16, %rax
; EGPR-NDD-NEXT:    adcq %r18, %rcx
; EGPR-NDD-NEXT:    addq %r19, %r11
; EGPR-NDD-NEXT:    adcq %r22, %r17
; EGPR-NDD-NEXT:    adcq %r24, %rax
; EGPR-NDD-NEXT:    adcq %rsi, %rcx
; EGPR-NDD-NEXT:    addq {{[-0-9]+}}(%r{{[sb]}}p), %r9 # 8-byte Folded Reload
; EGPR-NDD-NEXT:    adcq %r13, %r30
; EGPR-NDD-NEXT:    adcq %r15, %r10
; EGPR-NDD-NEXT:    adcq %r14, %rdi
; EGPR-NDD-NEXT:    adcq %r20, %r11
; EGPR-NDD-NEXT:    adcq %rbx, %r17
; EGPR-NDD-NEXT:    adcq %r29, %rax
; EGPR-NDD-NEXT:    adcq %r8, %rcx
; EGPR-NDD-NEXT:    addq %r9, {{[-0-9]+}}(%r{{[sb]}}p), %r9 # 8-byte Folded Reload
; EGPR-NDD-NEXT:    adcq %r30, {{[-0-9]+}}(%r{{[sb]}}p), %r30 # 8-byte Folded Reload
; EGPR-NDD-NEXT:    adcq %r10, {{[-0-9]+}}(%r{{[sb]}}p), %r10 # 8-byte Folded Reload
; EGPR-NDD-NEXT:    adcq %rdi, {{[-0-9]+}}(%r{{[sb]}}p), %rdi # 8-byte Folded Reload
; EGPR-NDD-NEXT:    adcq %r11, {{[-0-9]+}}(%r{{[sb]}}p), %r11 # 8-byte Folded Reload
; EGPR-NDD-NEXT:    adcq %r17, {{[-0-9]+}}(%r{{[sb]}}p), %r17 # 8-byte Folded Reload
; EGPR-NDD-NEXT:    adcq %rax, {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Folded Reload
; EGPR-NDD-NEXT:    adcq %rcx, {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Folded Reload
; EGPR-NDD-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rdx # 8-byte Reload
; EGPR-NDD-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rsi # 8-byte Reload
; EGPR-NDD-NEXT:    movq %rsi, (%rdx)
; EGPR-NDD-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rsi # 8-byte Reload
; EGPR-NDD-NEXT:    movq %rsi, 8(%rdx)
; EGPR-NDD-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rsi # 8-byte Reload
; EGPR-NDD-NEXT:    movq %rsi, 16(%rdx)
; EGPR-NDD-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rsi # 8-byte Reload
; EGPR-NDD-NEXT:    movq %rsi, 24(%rdx)
; EGPR-NDD-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rsi # 8-byte Reload
; EGPR-NDD-NEXT:    movq %rsi, 32(%rdx)
; EGPR-NDD-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rsi # 8-byte Reload
; EGPR-NDD-NEXT:    movq %rsi, 40(%rdx)
; EGPR-NDD-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rsi # 8-byte Reload
; EGPR-NDD-NEXT:    movq %rsi, 48(%rdx)
; EGPR-NDD-NEXT:    movq (%rsp), %rsi # 8-byte Reload
; EGPR-NDD-NEXT:    movq %rsi, 56(%rdx)
; EGPR-NDD-NEXT:    movq %r9, 64(%rdx)
; EGPR-NDD-NEXT:    movq %r30, 72(%rdx)
; EGPR-NDD-NEXT:    movq %r10, 80(%rdx)
; EGPR-NDD-NEXT:    movq %rdi, 88(%rdx)
; EGPR-NDD-NEXT:    movq %r11, 96(%rdx)
; EGPR-NDD-NEXT:    movq %r17, 104(%rdx)
; EGPR-NDD-NEXT:    movq %rax, 112(%rdx)
; EGPR-NDD-NEXT:    movq %rcx, 120(%rdx)
; EGPR-NDD-NEXT:    addq $64, %rsp
; EGPR-NDD-NEXT:    popq %rbx
; EGPR-NDD-NEXT:    popq %r12
; EGPR-NDD-NEXT:    popq %r13
; EGPR-NDD-NEXT:    popq %r14
; EGPR-NDD-NEXT:    popq %r15
; EGPR-NDD-NEXT:    popq %rbp
; EGPR-NDD-NEXT:    retq
  %av = load i1024, ptr %a
  %bv = load i1024, ptr %b
  %r = mul i1024 %av, %bv
  store i1024 %r, ptr %out
  ret void
}
