; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=mipsel -relocation-model=pic < %s | FileCheck %s -check-prefix=32
; RUN: llc -mtriple=mips64el -mcpu=mips4 -target-abi=n64 -relocation-model=pic < %s | \
; RUN:     FileCheck %s -check-prefix=64
; RUN: llc -mtriple=mips64el -mcpu=mips64 -target-abi=n64 -relocation-model=pic < %s | \
; RUN:     FileCheck %s -check-prefix=64

%struct.S1 = type { [65536 x i8] }

@s1 = external global %struct.S1

define void @f() nounwind {
; 32-LABEL: f:
; 32:       # %bb.0: # %entry
; 32-NEXT:    lui $2, %hi(_gp_disp)
; 32-NEXT:    addiu $2, $2, %lo(_gp_disp)
; 32-NEXT:    lui $1, 1
; 32-NEXT:    addiu $1, $1, 24
; 32-NEXT:    subu $sp, $sp, $1
; 32-NEXT:    lui $1, 1
; 32-NEXT:    addu $1, $sp, $1
; 32-NEXT:    sw $ra, 20($1) # 4-byte Folded Spill
; 32-NEXT:    lui $1, 1
; 32-NEXT:    addu $1, $sp, $1
; 32-NEXT:    sw $17, 16($1) # 4-byte Folded Spill
; 32-NEXT:    lui $1, 1
; 32-NEXT:    addu $1, $sp, $1
; 32-NEXT:    sw $16, 12($1) # 4-byte Folded Spill
; 32-NEXT:    addu $16, $2, $25
; 32-NEXT:    addiu $sp, $sp, -16
; 32-NEXT:    addiu $17, $sp, 8
; 32-NEXT:    lw $5, %got(s1)($16)
; 32-NEXT:    lw $25, %call16(memcpy)($16)
; 32-NEXT:    move $4, $17
; 32-NEXT:    lui $6, 1
; 32-NEXT:    .reloc $tmp0, R_MIPS_JALR, memcpy
; 32-NEXT:  $tmp0:
; 32-NEXT:    jalr $25
; 32-NEXT:    move $gp, $16
; 32-NEXT:    addiu $sp, $sp, 16
; 32-NEXT:    lui $1, 1
; 32-NEXT:    subu $sp, $sp, $1
; 32-NEXT:    addiu $5, $17, 16
; 32-NEXT:    addiu $4, $sp, 16
; 32-NEXT:    lw $25, %call16(memcpy)($16)
; 32-NEXT:    .reloc $tmp1, R_MIPS_JALR, memcpy
; 32-NEXT:  $tmp1:
; 32-NEXT:    jalr $25
; 32-NEXT:    ori $6, $zero, 65520
; 32-NEXT:    lw $7, 20($sp)
; 32-NEXT:    lw $6, 16($sp)
; 32-NEXT:    lw $5, 12($sp)
; 32-NEXT:    lw $4, 8($sp)
; 32-NEXT:    lw $25, %call16(f2)($16)
; 32-NEXT:    .reloc $tmp2, R_MIPS_JALR, f2
; 32-NEXT:  $tmp2:
; 32-NEXT:    jalr $25
; 32-NEXT:    move $gp, $16
; 32-NEXT:    lui $1, 1
; 32-NEXT:    addu $sp, $sp, $1
; 32-NEXT:    lui $1, 1
; 32-NEXT:    addu $1, $sp, $1
; 32-NEXT:    lw $16, 12($1) # 4-byte Folded Reload
; 32-NEXT:    lui $1, 1
; 32-NEXT:    addu $1, $sp, $1
; 32-NEXT:    lw $17, 16($1) # 4-byte Folded Reload
; 32-NEXT:    lui $1, 1
; 32-NEXT:    addu $1, $sp, $1
; 32-NEXT:    lw $ra, 20($1) # 4-byte Folded Reload
; 32-NEXT:    lui $1, 1
; 32-NEXT:    addiu $1, $1, 24
; 32-NEXT:    jr $ra
; 32-NEXT:    addu $sp, $sp, $1
;
; 64-LABEL: f:
; 64:       # %bb.0: # %entry
; 64-NEXT:    lui $1, 1
; 64-NEXT:    daddiu $1, $1, 48
; 64-NEXT:    dsubu $sp, $sp, $1
; 64-NEXT:    lui $1, 1
; 64-NEXT:    daddu $1, $sp, $1
; 64-NEXT:    sd $ra, 40($1) # 8-byte Folded Spill
; 64-NEXT:    lui $1, 1
; 64-NEXT:    daddu $1, $sp, $1
; 64-NEXT:    sd $gp, 32($1) # 8-byte Folded Spill
; 64-NEXT:    lui $1, 1
; 64-NEXT:    daddu $1, $sp, $1
; 64-NEXT:    sd $17, 24($1) # 8-byte Folded Spill
; 64-NEXT:    lui $1, 1
; 64-NEXT:    daddu $1, $sp, $1
; 64-NEXT:    sd $16, 16($1) # 8-byte Folded Spill
; 64-NEXT:    lui $1, %hi(%neg(%gp_rel(f)))
; 64-NEXT:    daddu $1, $1, $25
; 64-NEXT:    daddiu $16, $1, %lo(%neg(%gp_rel(f)))
; 64-NEXT:    daddiu $17, $sp, 16
; 64-NEXT:    ld $5, %got_disp(s1)($16)
; 64-NEXT:    ld $25, %call16(memcpy)($16)
; 64-NEXT:    move $4, $17
; 64-NEXT:    lui $6, 1
; 64-NEXT:    .reloc .Ltmp0, R_MIPS_JALR, memcpy
; 64-NEXT:  .Ltmp0:
; 64-NEXT:    jalr $25
; 64-NEXT:    move $gp, $16
; 64-NEXT:    ori $1, $zero, 65472
; 64-NEXT:    dsubu $sp, $sp, $1
; 64-NEXT:    daddiu $5, $17, 64
; 64-NEXT:    ori $6, $zero, 65472
; 64-NEXT:    ld $25, %call16(memcpy)($16)
; 64-NEXT:    .reloc .Ltmp1, R_MIPS_JALR, memcpy
; 64-NEXT:  .Ltmp1:
; 64-NEXT:    jalr $25
; 64-NEXT:    move $4, $sp
; 64-NEXT:    ld $11, 72($sp)
; 64-NEXT:    ld $10, 64($sp)
; 64-NEXT:    ld $9, 56($sp)
; 64-NEXT:    ld $8, 48($sp)
; 64-NEXT:    ld $7, 40($sp)
; 64-NEXT:    ld $6, 32($sp)
; 64-NEXT:    ld $5, 24($sp)
; 64-NEXT:    ld $25, %call16(f2)($16)
; 64-NEXT:    .reloc .Ltmp2, R_MIPS_JALR, f2
; 64-NEXT:  .Ltmp2:
; 64-NEXT:    jalr $25
; 64-NEXT:    ld $4, 16($sp)
; 64-NEXT:    ori $1, $zero, 65472
; 64-NEXT:    daddu $sp, $sp, $1
; 64-NEXT:    lui $1, 1
; 64-NEXT:    daddu $1, $sp, $1
; 64-NEXT:    ld $16, 16($1) # 8-byte Folded Reload
; 64-NEXT:    lui $1, 1
; 64-NEXT:    daddu $1, $sp, $1
; 64-NEXT:    ld $17, 24($1) # 8-byte Folded Reload
; 64-NEXT:    lui $1, 1
; 64-NEXT:    daddu $1, $sp, $1
; 64-NEXT:    ld $gp, 32($1) # 8-byte Folded Reload
; 64-NEXT:    lui $1, 1
; 64-NEXT:    daddu $1, $sp, $1
; 64-NEXT:    ld $ra, 40($1) # 8-byte Folded Reload
; 64-NEXT:    lui $1, 1
; 64-NEXT:    daddiu $1, $1, 48
; 64-NEXT:    jr $ra
; 64-NEXT:    daddu $sp, $sp, $1
entry:


  %agg.tmp = alloca %struct.S1, align 8
  call void @llvm.memcpy.p0.p0.i32(ptr align 1 %agg.tmp, ptr align 1 @s1, i32 65536, i1 false)
  call void @f2(ptr byval(%struct.S1) %agg.tmp) nounwind
  ret void
}

declare void @f2(ptr byval(%struct.S1))

declare void @llvm.memcpy.p0.p0.i32(ptr nocapture, ptr nocapture, i32, i1) nounwind
