; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc %s -mtriple=riscv64 -riscv-save-csrs-early=true \
; RUN: -stop-after=finalize-isel -o - | FileCheck %s

define void @test0() {
  ; CHECK-LABEL: name: test0
  ; CHECK: bb.0 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $x1, $x8, $x9, $x18, $x19, $x20, $x21, $x22, $x23, $x24, $x25, $x26, $x27
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gprall = COPY $x27
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gprall = COPY $x26
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gprall = COPY $x25
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:gprall = COPY $x24
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:gprall = COPY $x23
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:gprall = COPY $x22
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:gprall = COPY $x21
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:gprall = COPY $x20
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:gprall = COPY $x19
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:gprall = COPY $x18
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:gprall = COPY $x9
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:gprall = COPY $x8
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:gprall = COPY $x1
  ; CHECK-NEXT:   $x1 = COPY [[COPY12]]
  ; CHECK-NEXT:   $x8 = COPY [[COPY11]]
  ; CHECK-NEXT:   $x9 = COPY [[COPY10]]
  ; CHECK-NEXT:   $x18 = COPY [[COPY9]]
  ; CHECK-NEXT:   $x19 = COPY [[COPY8]]
  ; CHECK-NEXT:   $x20 = COPY [[COPY7]]
  ; CHECK-NEXT:   $x21 = COPY [[COPY6]]
  ; CHECK-NEXT:   $x22 = COPY [[COPY5]]
  ; CHECK-NEXT:   $x23 = COPY [[COPY4]]
  ; CHECK-NEXT:   $x24 = COPY [[COPY3]]
  ; CHECK-NEXT:   $x25 = COPY [[COPY2]]
  ; CHECK-NEXT:   $x26 = COPY [[COPY1]]
  ; CHECK-NEXT:   $x27 = COPY [[COPY]]
  ; CHECK-NEXT:   PseudoRET implicit $x1, implicit $x8, implicit $x9, implicit $x18, implicit $x19, implicit $x20, implicit $x21, implicit $x22, implicit $x23, implicit $x24, implicit $x25, implicit $x26, implicit $x27
  ret void
}
