; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -verify-machineinstrs -mtriple=aarch64-none-linux-gnu -mattr=+neon | FileCheck %s

define ptr @test_scalar_msub(ptr %a, ptr %b) {
; CHECK-LABEL: test_scalar_msub:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ldp w9, w12, [x1]
; CHECK-NEXT:    ldp w10, w11, [x0]
; CHECK-NEXT:    mul w13, w9, w10
; CHECK-NEXT:    mul w9, w11, w9
; CHECK-NEXT:    madd w9, w12, w10, w9
; CHECK-NEXT:    msub w10, w12, w11, w13
; CHECK-NEXT:    stp w10, w9, [x0]
; CHECK-NEXT:    ret
entry:
  %0 = load i32, ptr %a, align 4
  %1 = load i32, ptr %b, align 4
  %mul = mul nsw i32 %1, %0
  %_M_imag = getelementptr inbounds i8, ptr %a, i64 4
  %2 = load i32, ptr %_M_imag, align 4
  %_M_imag.i = getelementptr inbounds i8, ptr %b, i64 4
  %3 = load i32, ptr %_M_imag.i, align 4
  %mul3 = mul nsw i32 %3, %2
  %sub = sub nsw i32 %mul, %mul3
  %mul6 = mul nsw i32 %3, %0
  %mul9 = mul nsw i32 %2, %1
  %add = add nsw i32 %mul6, %mul9
  store i32 %add, ptr %_M_imag, align 4
  store i32 %sub, ptr %a, align 4
  ret ptr %a
}

define ptr @test_scalar_msub_i64(ptr %a, ptr %b) {
; CHECK-LABEL: test_scalar_msub_i64:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ldr x9, [x1]
; CHECK-NEXT:    ldur x10, [x0, #4]
; CHECK-NEXT:    ldr x11, [x0]
; CHECK-NEXT:    ldur x13, [x1, #4]
; CHECK-NEXT:    mul x12, x10, x9
; CHECK-NEXT:    mul x9, x9, x11
; CHECK-NEXT:    madd x11, x13, x11, x12
; CHECK-NEXT:    msub x9, x13, x10, x9
; CHECK-NEXT:    stur x11, [x0, #4]
; CHECK-NEXT:    str x9, [x0]
; CHECK-NEXT:    ret
entry:
  %0 = load i64, ptr %a, align 8
  %1 = load i64, ptr %b, align 8
  %mul = mul nsw i64 %1, %0
  %_M_imag = getelementptr inbounds i8, ptr %a, i64 4
  %2 = load i64, ptr %_M_imag, align 8
  %_M_imag.i = getelementptr inbounds i8, ptr %b, i64 4
  %3 = load i64, ptr %_M_imag.i, align 8
  %mul3 = mul nsw i64 %3, %2
  %sub = sub nsw i64 %mul, %mul3
  %mul6 = mul nsw i64 %3, %0
  %mul9 = mul nsw i64 %2, %1
  %add = add nsw i64 %mul6, %mul9
  store i64 %add, ptr %_M_imag, align 8
  store i64 %sub, ptr %a, align 8
  ret ptr %a
}
