; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=x86_64-apple-macosx -verify-machineinstrs -o - %s | FileCheck --check-prefix=CHECK %s
; RUN: llc -mtriple=x86_64-windows-msvc -verify-machineinstrs -o - %s | FileCheck --check-prefix=WINABI %s

; TODO: support marker generation with GlobalISel
target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128"

declare ptr @foo0(i32)
declare ptr @foo1()

declare void @llvm.objc.release(ptr)
declare void @objc_object(ptr)

declare void @foo2(ptr)

declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture)

declare ptr @_ZN1SD1Ev(ptr nonnull dereferenceable(1))

declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture)


%struct.S = type { i8 }

@g = global ptr null, align 8
@fptr = global ptr null, align 8

define ptr @rv_marker_1_retain() {
; CHECK-LABEL: rv_marker_1_retain:
; CHECK:       ## %bb.0: ## %entry
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    callq _foo1
; CHECK-NEXT:    movq %rax, %rdi
; CHECK-NEXT:    callq _objc_retainAutoreleasedReturnValue
; CHECK-NEXT:    popq %rcx
; CHECK-NEXT:    retq
;
; WINABI-LABEL: rv_marker_1_retain:
; WINABI:       # %bb.0: # %entry
; WINABI-NEXT:    subq $40, %rsp
; WINABI-NEXT:    .seh_stackalloc 40
; WINABI-NEXT:    .seh_endprologue
; WINABI-NEXT:    callq foo1
; WINABI-NEXT:    movq %rax, %rcx
; WINABI-NEXT:    callq objc_retainAutoreleasedReturnValue
; WINABI-NEXT:    nop
; WINABI-NEXT:    .seh_startepilogue
; WINABI-NEXT:    addq $40, %rsp
; WINABI-NEXT:    .seh_endepilogue
; WINABI-NEXT:    retq
; WINABI-NEXT:    .seh_endproc
entry:
  %call = call ptr @foo1() [ "clang.arc.attachedcall"(ptr @objc_retainAutoreleasedReturnValue) ]
  ret ptr %call
}

define ptr @rv_marker_1_unsafeClaim() {
; CHECK-LABEL: rv_marker_1_unsafeClaim:
; CHECK:       ## %bb.0: ## %entry
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    callq _foo1
; CHECK-NEXT:    movq %rax, %rdi
; CHECK-NEXT:    callq _objc_unsafeClaimAutoreleasedReturnValue
; CHECK-NEXT:    popq %rcx
; CHECK-NEXT:    retq
;
; WINABI-LABEL: rv_marker_1_unsafeClaim:
; WINABI:       # %bb.0: # %entry
; WINABI-NEXT:    subq $40, %rsp
; WINABI-NEXT:    .seh_stackalloc 40
; WINABI-NEXT:    .seh_endprologue
; WINABI-NEXT:    callq foo1
; WINABI-NEXT:    movq %rax, %rcx
; WINABI-NEXT:    callq objc_unsafeClaimAutoreleasedReturnValue
; WINABI-NEXT:    nop
; WINABI-NEXT:    .seh_startepilogue
; WINABI-NEXT:    addq $40, %rsp
; WINABI-NEXT:    .seh_endepilogue
; WINABI-NEXT:    retq
; WINABI-NEXT:    .seh_endproc
entry:
  %call = call ptr @foo1() [ "clang.arc.attachedcall"(ptr @objc_unsafeClaimAutoreleasedReturnValue) ]
  ret ptr %call
}

define void @rv_marker_2_select(i32 %c) {
; CHECK-LABEL: rv_marker_2_select:
; CHECK:       ## %bb.0: ## %entry
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    cmpl $1, %edi
; CHECK-NEXT:    adcl $1, %eax
; CHECK-NEXT:    movl %eax, %edi
; CHECK-NEXT:    callq _foo0
; CHECK-NEXT:    movq %rax, %rdi
; CHECK-NEXT:    callq _objc_retainAutoreleasedReturnValue
; CHECK-NEXT:    movq %rax, %rdi
; CHECK-NEXT:    popq %rax
; CHECK-NEXT:    jmp _foo2 ## TAILCALL
;
; WINABI-LABEL: rv_marker_2_select:
; WINABI:       # %bb.0: # %entry
; WINABI-NEXT:    subq $40, %rsp
; WINABI-NEXT:    .seh_stackalloc 40
; WINABI-NEXT:    .seh_endprologue
; WINABI-NEXT:    xorl %eax, %eax
; WINABI-NEXT:    cmpl $1, %ecx
; WINABI-NEXT:    adcl $1, %eax
; WINABI-NEXT:    movl %eax, %ecx
; WINABI-NEXT:    callq foo0
; WINABI-NEXT:    movq %rax, %rcx
; WINABI-NEXT:    callq objc_retainAutoreleasedReturnValue
; WINABI-NEXT:    movq %rax, %rcx
; WINABI-NEXT:    .seh_startepilogue
; WINABI-NEXT:    addq $40, %rsp
; WINABI-NEXT:    .seh_endepilogue
; WINABI-NEXT:    jmp foo2 # TAILCALL
; WINABI-NEXT:    .seh_endproc
entry:
  %tobool.not = icmp eq i32 %c, 0
  %.sink = select i1 %tobool.not, i32 2, i32 1
  %call1 = call ptr @foo0(i32 %.sink) [ "clang.arc.attachedcall"(ptr @objc_retainAutoreleasedReturnValue) ]
  tail call void @foo2(ptr %call1)
  ret void
}

define void @rv_marker_3() personality ptr @__gxx_personality_v0 {
; CHECK-LABEL: rv_marker_3:
; CHECK:       ## %bb.0: ## %entry
; CHECK-NEXT:    pushq %r14
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    .cfi_offset %rbx, -24
; CHECK-NEXT:    .cfi_offset %r14, -16
; CHECK-NEXT:    callq _foo1
; CHECK-NEXT:    movq %rax, %rdi
; CHECK-NEXT:    callq _objc_retainAutoreleasedReturnValue
; CHECK-NEXT:    movq %rax, %r14
; CHECK-NEXT:  Ltmp0: ## EH_LABEL
; CHECK-NEXT:    movq %rax, %rdi
; CHECK-NEXT:    callq _objc_object
; CHECK-NEXT:  Ltmp1: ## EH_LABEL
; CHECK-NEXT:  ## %bb.1: ## %invoke.cont
; CHECK-NEXT:    movq %r14, %rdi
; CHECK-NEXT:    addq $8, %rsp
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    popq %r14
; CHECK-NEXT:    jmpq *_objc_release@GOTPCREL(%rip) ## TAILCALL
; CHECK-NEXT:  LBB3_2: ## %lpad
; CHECK-NEXT:  Ltmp2: ## EH_LABEL
; CHECK-NEXT:    movq %rax, %rbx
; CHECK-NEXT:    movq %r14, %rdi
; CHECK-NEXT:    callq *_objc_release@GOTPCREL(%rip)
; CHECK-NEXT:    movq %rbx, %rdi
; CHECK-NEXT:    callq __Unwind_Resume
; CHECK-NEXT:  Lfunc_end0:
;
; WINABI-LABEL: rv_marker_3:
; WINABI:       # %bb.0: # %entry
; WINABI-NEXT:    pushq %rsi
; WINABI-NEXT:    .seh_pushreg %rsi
; WINABI-NEXT:    pushq %rdi
; WINABI-NEXT:    .seh_pushreg %rdi
; WINABI-NEXT:    subq $40, %rsp
; WINABI-NEXT:    .seh_stackalloc 40
; WINABI-NEXT:    .seh_endprologue
; WINABI-NEXT:    callq foo1
; WINABI-NEXT:    movq %rax, %rcx
; WINABI-NEXT:    callq objc_retainAutoreleasedReturnValue
; WINABI-NEXT:    movq %rax, %rdi
; WINABI-NEXT:  .Ltmp0: # EH_LABEL
; WINABI-NEXT:    movq %rax, %rcx
; WINABI-NEXT:    callq objc_object
; WINABI-NEXT:  .Ltmp1: # EH_LABEL
; WINABI-NEXT:  # %bb.1: # %invoke.cont
; WINABI-NEXT:    movq %rdi, %rcx
; WINABI-NEXT:    .seh_startepilogue
; WINABI-NEXT:    addq $40, %rsp
; WINABI-NEXT:    popq %rdi
; WINABI-NEXT:    popq %rsi
; WINABI-NEXT:    .seh_endepilogue
; WINABI-NEXT:    jmp objc_release # TAILCALL
; WINABI-NEXT:  .LBB3_2: # %lpad
; WINABI-NEXT:  .Ltmp2: # EH_LABEL
; WINABI-NEXT:    movq %rax, %rsi
; WINABI-NEXT:    movq %rdi, %rcx
; WINABI-NEXT:    callq objc_release
; WINABI-NEXT:    movq %rsi, %rcx
; WINABI-NEXT:    callq _Unwind_Resume
; WINABI-NEXT:    int3
; WINABI-NEXT:  .Lfunc_end0:
; WINABI-NEXT:    .seh_handlerdata
; WINABI-NEXT:    .text
; WINABI-NEXT:    .seh_endproc
entry:
  %call = call ptr @foo1() [ "clang.arc.attachedcall"(ptr @objc_retainAutoreleasedReturnValue) ]
  invoke void @objc_object(ptr %call) #5
          to label %invoke.cont unwind label %lpad

invoke.cont:                                      ; preds = %entry
  tail call void @llvm.objc.release(ptr %call)
  ret void

lpad:                                             ; preds = %entry
  %0 = landingpad { ptr, i32 }
          cleanup
  tail call void @llvm.objc.release(ptr %call)
  resume { ptr, i32 } %0
}

define void @rv_marker_4() personality ptr @__gxx_personality_v0 {
; CHECK-LABEL: rv_marker_4:
; CHECK:       ## %bb.0: ## %entry
; CHECK-NEXT:    pushq %r14
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    .cfi_offset %rbx, -24
; CHECK-NEXT:    .cfi_offset %r14, -16
; CHECK-NEXT:  Ltmp3: ## EH_LABEL
; CHECK-NEXT:    callq _foo1
; CHECK-NEXT:    movq %rax, %rdi
; CHECK-NEXT:    callq _objc_retainAutoreleasedReturnValue
; CHECK-NEXT:  Ltmp4: ## EH_LABEL
; CHECK-NEXT:  ## %bb.1: ## %invoke.cont
; CHECK-NEXT:  Ltmp6: ## EH_LABEL
; CHECK-NEXT:    movq %rax, %rbx
; CHECK-NEXT:    movq %rax, %rdi
; CHECK-NEXT:    callq _objc_object
; CHECK-NEXT:  Ltmp7: ## EH_LABEL
; CHECK-NEXT:  ## %bb.2: ## %invoke.cont2
; CHECK-NEXT:    movq %rbx, %rdi
; CHECK-NEXT:    callq *_objc_release@GOTPCREL(%rip)
; CHECK-NEXT:    leaq {{[0-9]+}}(%rsp), %rdi
; CHECK-NEXT:    callq __ZN1SD1Ev
; CHECK-NEXT:    addq $8, %rsp
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    popq %r14
; CHECK-NEXT:    retq
; CHECK-NEXT:  LBB4_4: ## %lpad1
; CHECK-NEXT:  Ltmp8: ## EH_LABEL
; CHECK-NEXT:    movq %rax, %r14
; CHECK-NEXT:    movq %rbx, %rdi
; CHECK-NEXT:    callq *_objc_release@GOTPCREL(%rip)
; CHECK-NEXT:    jmp LBB4_5
; CHECK-NEXT:  LBB4_3: ## %lpad
; CHECK-NEXT:  Ltmp5: ## EH_LABEL
; CHECK-NEXT:    movq %rax, %r14
; CHECK-NEXT:  LBB4_5: ## %ehcleanup
; CHECK-NEXT:    leaq {{[0-9]+}}(%rsp), %rdi
; CHECK-NEXT:    callq __ZN1SD1Ev
; CHECK-NEXT:    movq %r14, %rdi
; CHECK-NEXT:    callq __Unwind_Resume
; CHECK-NEXT:  Lfunc_end1:
;
; WINABI-LABEL: rv_marker_4:
; WINABI:       # %bb.0: # %entry
; WINABI-NEXT:    pushq %rsi
; WINABI-NEXT:    .seh_pushreg %rsi
; WINABI-NEXT:    pushq %rdi
; WINABI-NEXT:    .seh_pushreg %rdi
; WINABI-NEXT:    subq $40, %rsp
; WINABI-NEXT:    .seh_stackalloc 40
; WINABI-NEXT:    .seh_endprologue
; WINABI-NEXT:  .Ltmp3: # EH_LABEL
; WINABI-NEXT:    callq foo1
; WINABI-NEXT:    movq %rax, %rcx
; WINABI-NEXT:    callq objc_retainAutoreleasedReturnValue
; WINABI-NEXT:  .Ltmp4: # EH_LABEL
; WINABI-NEXT:  # %bb.1: # %invoke.cont
; WINABI-NEXT:  .Ltmp6: # EH_LABEL
; WINABI-NEXT:    movq %rax, %rsi
; WINABI-NEXT:    movq %rax, %rcx
; WINABI-NEXT:    callq objc_object
; WINABI-NEXT:  .Ltmp7: # EH_LABEL
; WINABI-NEXT:  # %bb.2: # %invoke.cont2
; WINABI-NEXT:    movq %rsi, %rcx
; WINABI-NEXT:    callq objc_release
; WINABI-NEXT:    leaq {{[0-9]+}}(%rsp), %rcx
; WINABI-NEXT:    callq _ZN1SD1Ev
; WINABI-NEXT:    nop
; WINABI-NEXT:    .seh_startepilogue
; WINABI-NEXT:    addq $40, %rsp
; WINABI-NEXT:    popq %rdi
; WINABI-NEXT:    popq %rsi
; WINABI-NEXT:    .seh_endepilogue
; WINABI-NEXT:    retq
; WINABI-NEXT:  .LBB4_4: # %lpad1
; WINABI-NEXT:  .Ltmp8: # EH_LABEL
; WINABI-NEXT:    movq %rax, %rdi
; WINABI-NEXT:    movq %rsi, %rcx
; WINABI-NEXT:    callq objc_release
; WINABI-NEXT:    jmp .LBB4_5
; WINABI-NEXT:  .LBB4_3: # %lpad
; WINABI-NEXT:  .Ltmp5: # EH_LABEL
; WINABI-NEXT:    movq %rax, %rdi
; WINABI-NEXT:  .LBB4_5: # %ehcleanup
; WINABI-NEXT:    leaq {{[0-9]+}}(%rsp), %rcx
; WINABI-NEXT:    callq _ZN1SD1Ev
; WINABI-NEXT:    movq %rdi, %rcx
; WINABI-NEXT:    callq _Unwind_Resume
; WINABI-NEXT:    int3
; WINABI-NEXT:  .Lfunc_end1:
; WINABI-NEXT:    .seh_handlerdata
; WINABI-NEXT:    .text
; WINABI-NEXT:    .seh_endproc
entry:
  %s = alloca %struct.S, align 1
  call void @llvm.lifetime.start.p0(i64 1, ptr nonnull %s) #2
  %call = invoke ptr @foo1() [ "clang.arc.attachedcall"(ptr @objc_retainAutoreleasedReturnValue) ]
          to label %invoke.cont unwind label %lpad

invoke.cont:                                      ; preds = %entry
  invoke void @objc_object(ptr %call) #5
          to label %invoke.cont2 unwind label %lpad1

invoke.cont2:                                     ; preds = %invoke.cont
  tail call void @llvm.objc.release(ptr %call)
  %call3 = call ptr @_ZN1SD1Ev(ptr nonnull dereferenceable(1) %s)
  call void @llvm.lifetime.end.p0(i64 1, ptr nonnull %s)
  ret void

lpad:                                             ; preds = %entry
  %0 = landingpad { ptr, i32 }
          cleanup
  br label %ehcleanup

lpad1:                                            ; preds = %invoke.cont
  %1 = landingpad { ptr, i32 }
          cleanup
  tail call void @llvm.objc.release(ptr %call)
  br label %ehcleanup

ehcleanup:                                        ; preds = %lpad1, %lpad
  %.pn = phi { ptr, i32 } [ %1, %lpad1 ], [ %0, %lpad ]
  %call4 = call ptr @_ZN1SD1Ev(ptr nonnull dereferenceable(1) %s)
  call void @llvm.lifetime.end.p0(i64 1, ptr nonnull %s)
  resume { ptr, i32 } %.pn
}

; TODO: This should use "callq *_fptr(%rip)".
define ptr @rv_marker_5_indirect_call() {
; CHECK-LABEL: rv_marker_5_indirect_call:
; CHECK:       ## %bb.0: ## %entry
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset %rbx, -16
; CHECK-NEXT:    movq _fptr(%rip), %rax
; CHECK-NEXT:    callq *%rax
; CHECK-NEXT:    movq %rax, %rdi
; CHECK-NEXT:    callq _objc_retainAutoreleasedReturnValue
; CHECK-NEXT:    movq %rax, %rbx
; CHECK-NEXT:    movq %rax, %rdi
; CHECK-NEXT:    callq _foo2
; CHECK-NEXT:    movq %rbx, %rax
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    retq
;
; WINABI-LABEL: rv_marker_5_indirect_call:
; WINABI:       # %bb.0: # %entry
; WINABI-NEXT:    pushq %rsi
; WINABI-NEXT:    .seh_pushreg %rsi
; WINABI-NEXT:    subq $32, %rsp
; WINABI-NEXT:    .seh_stackalloc 32
; WINABI-NEXT:    .seh_endprologue
; WINABI-NEXT:    movq fptr(%rip), %rax
; WINABI-NEXT:    callq *%rax
; WINABI-NEXT:    movq %rax, %rcx
; WINABI-NEXT:    callq objc_retainAutoreleasedReturnValue
; WINABI-NEXT:    movq %rax, %rsi
; WINABI-NEXT:    movq %rax, %rcx
; WINABI-NEXT:    callq foo2
; WINABI-NEXT:    movq %rsi, %rax
; WINABI-NEXT:    .seh_startepilogue
; WINABI-NEXT:    addq $32, %rsp
; WINABI-NEXT:    popq %rsi
; WINABI-NEXT:    .seh_endepilogue
; WINABI-NEXT:    retq
; WINABI-NEXT:    .seh_endproc
entry:
  %lv = load ptr, ptr @fptr, align 8
  %call = call ptr %lv() [ "clang.arc.attachedcall"(ptr @objc_retainAutoreleasedReturnValue) ]
  tail call void @foo2(ptr %call)
  ret ptr %call
}

declare ptr @foo(i64, i64, i64)

define void @rv_marker_multiarg(i64 %a, i64 %b, i64 %c) {
; CHECK-LABEL: rv_marker_multiarg:
; CHECK:       ## %bb.0:
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    movq %rdi, %rax
; CHECK-NEXT:    movq %rdx, %rdi
; CHECK-NEXT:    movq %rax, %rdx
; CHECK-NEXT:    callq _foo
; CHECK-NEXT:    movq %rax, %rdi
; CHECK-NEXT:    callq _objc_retainAutoreleasedReturnValue
; CHECK-NEXT:    popq %rax
; CHECK-NEXT:    retq
;
; WINABI-LABEL: rv_marker_multiarg:
; WINABI:       # %bb.0:
; WINABI-NEXT:    subq $40, %rsp
; WINABI-NEXT:    .seh_stackalloc 40
; WINABI-NEXT:    .seh_endprologue
; WINABI-NEXT:    movq %rcx, %rax
; WINABI-NEXT:    movq %r8, %rcx
; WINABI-NEXT:    movq %rax, %r8
; WINABI-NEXT:    callq foo
; WINABI-NEXT:    movq %rax, %rcx
; WINABI-NEXT:    callq objc_retainAutoreleasedReturnValue
; WINABI-NEXT:    nop
; WINABI-NEXT:    .seh_startepilogue
; WINABI-NEXT:    addq $40, %rsp
; WINABI-NEXT:    .seh_endepilogue
; WINABI-NEXT:    retq
; WINABI-NEXT:    .seh_endproc
  %r = call ptr @foo(i64 %c, i64 %b, i64 %a) [ "clang.arc.attachedcall"(ptr @objc_retainAutoreleasedReturnValue) ]
  ret void
}

define void @test_nonlazybind() {
; CHECK-LABEL: test_nonlazybind:
; CHECK:       ## %bb.0:
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    callq *_foo_nonlazybind@GOTPCREL(%rip)
; CHECK-NEXT:    movq %rax, %rdi
; CHECK-NEXT:    callq _objc_retainAutoreleasedReturnValue
; CHECK-NEXT:    popq %rax
; CHECK-NEXT:    retq
;
; WINABI-LABEL: test_nonlazybind:
; WINABI:       # %bb.0:
; WINABI-NEXT:    subq $40, %rsp
; WINABI-NEXT:    .seh_stackalloc 40
; WINABI-NEXT:    .seh_endprologue
; WINABI-NEXT:    callq foo_nonlazybind
; WINABI-NEXT:    movq %rax, %rcx
; WINABI-NEXT:    callq objc_retainAutoreleasedReturnValue
; WINABI-NEXT:    nop
; WINABI-NEXT:    .seh_startepilogue
; WINABI-NEXT:    addq $40, %rsp
; WINABI-NEXT:    .seh_endepilogue
; WINABI-NEXT:    retq
; WINABI-NEXT:    .seh_endproc
  %call1 = notail call ptr @foo_nonlazybind() [ "clang.arc.attachedcall"(ptr @objc_retainAutoreleasedReturnValue) ]
  ret void
}

declare ptr @foo_nonlazybind()  nonlazybind

declare ptr @objc_retainAutoreleasedReturnValue(ptr)
declare ptr @objc_unsafeClaimAutoreleasedReturnValue(ptr)
declare i32 @__gxx_personality_v0(...)

declare ptr @fn1()
declare ptr @fn2()

define ptr @rv_marker_block_placement(i1 %c.0) {
; CHECK-LABEL: rv_marker_block_placement:
; CHECK:       ## %bb.0: ## %entry
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    testb $1, %dil
; CHECK-NEXT:    je LBB8_2
; CHECK-NEXT:  ## %bb.1: ## %then
; CHECK-NEXT:    callq _fn1
; CHECK-NEXT:    movq %rax, %rdi
; CHECK-NEXT:    callq _objc_retainAutoreleasedReturnValue
; CHECK-NEXT:    jmp LBB8_3
; CHECK-NEXT:  LBB8_2: ## %else
; CHECK-NEXT:    callq _fn2
; CHECK-NEXT:    movq %rax, %rdi
; CHECK-NEXT:    callq _objc_retainAutoreleasedReturnValue
; CHECK-NEXT:  LBB8_3: ## %exit
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    popq %rcx
; CHECK-NEXT:    retq
;
; WINABI-LABEL: rv_marker_block_placement:
; WINABI:       # %bb.0: # %entry
; WINABI-NEXT:    subq $40, %rsp
; WINABI-NEXT:    .seh_stackalloc 40
; WINABI-NEXT:    .seh_endprologue
; WINABI-NEXT:    testb $1, %cl
; WINABI-NEXT:    je .LBB8_2
; WINABI-NEXT:  # %bb.1: # %then
; WINABI-NEXT:    callq fn1
; WINABI-NEXT:    jmp .LBB8_3
; WINABI-NEXT:  .LBB8_2: # %else
; WINABI-NEXT:    callq fn2
; WINABI-NEXT:  .LBB8_3: # %exit
; WINABI-NEXT:    movq %rax, %rcx
; WINABI-NEXT:    callq objc_retainAutoreleasedReturnValue
; WINABI-NEXT:    xorl %eax, %eax
; WINABI-NEXT:    .seh_startepilogue
; WINABI-NEXT:    addq $40, %rsp
; WINABI-NEXT:    .seh_endepilogue
; WINABI-NEXT:    retq
; WINABI-NEXT:    .seh_endproc



entry:
  br i1 %c.0, label %then, label %else

then:
  %call.0 = notail call ptr @fn1() [ "clang.arc.attachedcall"(ptr @objc_retainAutoreleasedReturnValue) ]
  br label %exit

else:
  %call.1 = notail call ptr @fn2() [ "clang.arc.attachedcall"(ptr @objc_retainAutoreleasedReturnValue) ]
  br label %exit

exit:
  ret ptr null
}
