; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -emulated-tls -mtriple=i386-linux-gnu -relocation-model=pic | FileCheck -check-prefix=X86 %s
; RUN: llc < %s -emulated-tls -mtriple=x86_64-linux-gnu -relocation-model=pic | FileCheck -check-prefix=X64 %s
; RUN: llc < %s -emulated-tls -mtriple=i386-linux-android -relocation-model=pic | FileCheck -check-prefix=X86 %s
; RUN: llc < %s -emulated-tls -mtriple=x86_64-linux-android -relocation-model=pic | FileCheck -check-prefix=X64 %s

; RUN: llc < %s -mtriple=i386-linux-gnu -relocation-model=pic | FileCheck -check-prefix=NoEMU %s
; RUN: llc < %s -mtriple=x86_64-linux-gnu -relocation-model=pic | FileCheck -check-prefix=NoEMU %s
; RUN: llc < %s -mtriple=x86_64-linux-android29 -relocation-model=pic | FileCheck -check-prefix=NoEMU %s
; RUN: llc < %s -mtriple=i386-linux-android -relocation-model=pic | FileCheck -check-prefix=X86 %s
; RUN: llc < %s -mtriple=x86_64-linux-android -relocation-model=pic | FileCheck -check-prefix=X64 %s
; RUN: llc < %s -mtriple=i386-linux-ohos -relocation-model=pic | FileCheck -check-prefix=X86 %s
; RUN: llc < %s -mtriple=x86_64-linux-ohos -relocation-model=pic | FileCheck -check-prefix=X64 %s

; NoEMU-NOT: __emutls

; Use my_emutls_get_address like __emutls_get_address.
@my_emutls_v_xyz = external global ptr, align 4
declare ptr @my_emutls_get_address(ptr)

define i32 @my_get_xyz() {
; X86-LABEL: my_get_xyz:
; X86:       # %bb.0: # %entry
; X86-NEXT:    pushl %ebx
; X86-NEXT:    .cfi_def_cfa_offset 8
; X86-NEXT:    subl $8, %esp
; X86-NEXT:    .cfi_def_cfa_offset 16
; X86-NEXT:    .cfi_offset %ebx, -8
; X86-NEXT:    calll .L0$pb
; X86-NEXT:    .cfi_adjust_cfa_offset 4
; X86-NEXT:  .L0$pb:
; X86-NEXT:    popl %ebx
; X86-NEXT:    .cfi_adjust_cfa_offset -4
; X86-NEXT:  .Ltmp0:
; X86-NEXT:    addl $_GLOBAL_OFFSET_TABLE_+(.Ltmp0-.L0$pb), %ebx
; X86-NEXT:    movl my_emutls_v_xyz@GOT(%ebx), %eax
; X86-NEXT:    movl %eax, (%esp)
; X86-NEXT:    calll my_emutls_get_address@PLT
; X86-NEXT:    movl (%eax), %eax
; X86-NEXT:    addl $8, %esp
; X86-NEXT:    .cfi_def_cfa_offset 8
; X86-NEXT:    popl %ebx
; X86-NEXT:    .cfi_def_cfa_offset 4
; X86-NEXT:    retl
;
; X64-LABEL: my_get_xyz:
; X64:       # %bb.0: # %entry
; X64-NEXT:    pushq %rax
; X64-NEXT:    .cfi_def_cfa_offset 16
; X64-NEXT:    movq my_emutls_v_xyz@GOTPCREL(%rip), %rdi
; X64-NEXT:    callq my_emutls_get_address@PLT
; X64-NEXT:    movl (%rax), %eax
; X64-NEXT:    popq %rcx
; X64-NEXT:    .cfi_def_cfa_offset 8
; X64-NEXT:    retq

entry:
  %call = call ptr @my_emutls_get_address(ptr @my_emutls_v_xyz)
  %0 = load i32, ptr %call, align 4
  ret i32 %0
}

@i = thread_local global i32 15
@j = internal thread_local global i32 42
@k = internal thread_local global i32 0, align 8

define i32 @f1() {
; X86-LABEL: f1:
; X86:       # %bb.0: # %entry
; X86-NEXT:    pushl %ebx
; X86-NEXT:    .cfi_def_cfa_offset 8
; X86-NEXT:    subl $8, %esp
; X86-NEXT:    .cfi_def_cfa_offset 16
; X86-NEXT:    .cfi_offset %ebx, -8
; X86-NEXT:    calll .L1$pb
; X86-NEXT:    .cfi_adjust_cfa_offset 4
; X86-NEXT:  .L1$pb:
; X86-NEXT:    popl %ebx
; X86-NEXT:    .cfi_adjust_cfa_offset -4
; X86-NEXT:  .Ltmp1:
; X86-NEXT:    addl $_GLOBAL_OFFSET_TABLE_+(.Ltmp1-.L1$pb), %ebx
; X86-NEXT:    movl __emutls_v.i@GOT(%ebx), %eax
; X86-NEXT:    movl %eax, (%esp)
; X86-NEXT:    calll __emutls_get_address@PLT
; X86-NEXT:    movl (%eax), %eax
; X86-NEXT:    addl $8, %esp
; X86-NEXT:    .cfi_def_cfa_offset 8
; X86-NEXT:    popl %ebx
; X86-NEXT:    .cfi_def_cfa_offset 4
; X86-NEXT:    retl
;
; X64-LABEL: f1:
; X64:       # %bb.0: # %entry
; X64-NEXT:    pushq %rax
; X64-NEXT:    .cfi_def_cfa_offset 16
; X64-NEXT:    movq __emutls_v.i@GOTPCREL(%rip), %rdi
; X64-NEXT:    callq __emutls_get_address@PLT
; X64-NEXT:    movl (%rax), %eax
; X64-NEXT:    popq %rcx
; X64-NEXT:    .cfi_def_cfa_offset 8
; X64-NEXT:    retq
entry:
  %tmp1 = load i32, ptr @i
  ret i32 %tmp1
}


@i2 = external thread_local global i32

define ptr @f2() {
; X86-LABEL: f2:
; X86:       # %bb.0: # %entry
; X86-NEXT:    pushl %ebx
; X86-NEXT:    .cfi_def_cfa_offset 8
; X86-NEXT:    subl $8, %esp
; X86-NEXT:    .cfi_def_cfa_offset 16
; X86-NEXT:    .cfi_offset %ebx, -8
; X86-NEXT:    calll .L2$pb
; X86-NEXT:    .cfi_adjust_cfa_offset 4
; X86-NEXT:  .L2$pb:
; X86-NEXT:    popl %ebx
; X86-NEXT:    .cfi_adjust_cfa_offset -4
; X86-NEXT:  .Ltmp2:
; X86-NEXT:    addl $_GLOBAL_OFFSET_TABLE_+(.Ltmp2-.L2$pb), %ebx
; X86-NEXT:    movl __emutls_v.i@GOT(%ebx), %eax
; X86-NEXT:    movl %eax, (%esp)
; X86-NEXT:    calll __emutls_get_address@PLT
; X86-NEXT:    addl $8, %esp
; X86-NEXT:    .cfi_def_cfa_offset 8
; X86-NEXT:    popl %ebx
; X86-NEXT:    .cfi_def_cfa_offset 4
; X86-NEXT:    retl
;
; X64-LABEL: f2:
; X64:       # %bb.0: # %entry
; X64-NEXT:    pushq %rax
; X64-NEXT:    .cfi_def_cfa_offset 16
; X64-NEXT:    movq __emutls_v.i@GOTPCREL(%rip), %rdi
; X64-NEXT:    callq __emutls_get_address@PLT
; X64-NEXT:    popq %rcx
; X64-NEXT:    .cfi_def_cfa_offset 8
; X64-NEXT:    retq
entry:
  ret ptr @i
}



define i32 @f3() {
; X86-LABEL: f3:
; X86:       # %bb.0: # %entry
; X86-NEXT:    pushl %ebx
; X86-NEXT:    .cfi_def_cfa_offset 8
; X86-NEXT:    subl $8, %esp
; X86-NEXT:    .cfi_def_cfa_offset 16
; X86-NEXT:    .cfi_offset %ebx, -8
; X86-NEXT:    calll .L3$pb
; X86-NEXT:    .cfi_adjust_cfa_offset 4
; X86-NEXT:  .L3$pb:
; X86-NEXT:    popl %ebx
; X86-NEXT:    .cfi_adjust_cfa_offset -4
; X86-NEXT:  .Ltmp3:
; X86-NEXT:    addl $_GLOBAL_OFFSET_TABLE_+(.Ltmp3-.L3$pb), %ebx
; X86-NEXT:    movl __emutls_v.i@GOT(%ebx), %eax
; X86-NEXT:    movl %eax, (%esp)
; X86-NEXT:    calll __emutls_get_address@PLT
; X86-NEXT:    movl (%eax), %eax
; X86-NEXT:    addl $8, %esp
; X86-NEXT:    .cfi_def_cfa_offset 8
; X86-NEXT:    popl %ebx
; X86-NEXT:    .cfi_def_cfa_offset 4
; X86-NEXT:    retl
;
; X64-LABEL: f3:
; X64:       # %bb.0: # %entry
; X64-NEXT:    pushq %rax
; X64-NEXT:    .cfi_def_cfa_offset 16
; X64-NEXT:    movq __emutls_v.i@GOTPCREL(%rip), %rdi
; X64-NEXT:    callq __emutls_get_address@PLT
; X64-NEXT:    movl (%rax), %eax
; X64-NEXT:    popq %rcx
; X64-NEXT:    .cfi_def_cfa_offset 8
; X64-NEXT:    retq
entry:
  %tmp1 = load i32, ptr @i  ; <i32> [#uses=1]
  ret i32 %tmp1
}



define ptr @f4() nounwind {
; X86-LABEL: f4:
; X86:       # %bb.0: # %entry
; X86-NEXT:    pushl %ebx
; X86-NEXT:    subl $8, %esp
; X86-NEXT:    calll .L4$pb
; X86-NEXT:  .L4$pb:
; X86-NEXT:    popl %ebx
; X86-NEXT:  .Ltmp4:
; X86-NEXT:    addl $_GLOBAL_OFFSET_TABLE_+(.Ltmp4-.L4$pb), %ebx
; X86-NEXT:    movl __emutls_v.i@GOT(%ebx), %eax
; X86-NEXT:    movl %eax, (%esp)
; X86-NEXT:    calll __emutls_get_address@PLT
; X86-NEXT:    addl $8, %esp
; X86-NEXT:    popl %ebx
; X86-NEXT:    retl
;
; X64-LABEL: f4:
; X64:       # %bb.0: # %entry
; X64-NEXT:    pushq %rax
; X64-NEXT:    movq __emutls_v.i@GOTPCREL(%rip), %rdi
; X64-NEXT:    callq __emutls_get_address@PLT
; X64-NEXT:    popq %rcx
; X64-NEXT:    retq
entry:
  ret ptr @i
}



define i32 @f5() nounwind {
; X86-LABEL: f5:
; X86:       # %bb.0: # %entry
; X86-NEXT:    pushl %ebx
; X86-NEXT:    pushl %edi
; X86-NEXT:    pushl %esi
; X86-NEXT:    subl $16, %esp
; X86-NEXT:    calll .L5$pb
; X86-NEXT:  .L5$pb:
; X86-NEXT:    popl %esi
; X86-NEXT:  .Ltmp5:
; X86-NEXT:    addl $_GLOBAL_OFFSET_TABLE_+(.Ltmp5-.L5$pb), %esi
; X86-NEXT:    leal __emutls_v.j@GOTOFF(%esi), %eax
; X86-NEXT:    movl %eax, (%esp)
; X86-NEXT:    movl %esi, %ebx
; X86-NEXT:    calll __emutls_get_address@PLT
; X86-NEXT:    movl (%eax), %edi
; X86-NEXT:    leal __emutls_v.k@GOTOFF(%esi), %eax
; X86-NEXT:    movl %eax, (%esp)
; X86-NEXT:    calll __emutls_get_address@PLT
; X86-NEXT:    addl (%eax), %edi
; X86-NEXT:    movl %edi, %eax
; X86-NEXT:    addl $16, %esp
; X86-NEXT:    popl %esi
; X86-NEXT:    popl %edi
; X86-NEXT:    popl %ebx
; X86-NEXT:    retl
;
; X64-LABEL: f5:
; X64:       # %bb.0: # %entry
; X64-NEXT:    pushq %rbx
; X64-NEXT:    leaq __emutls_v.j(%rip), %rdi
; X64-NEXT:    callq __emutls_get_address@PLT
; X64-NEXT:    movl (%rax), %ebx
; X64-NEXT:    leaq __emutls_v.k(%rip), %rdi
; X64-NEXT:    callq __emutls_get_address@PLT
; X64-NEXT:    addl (%rax), %ebx
; X64-NEXT:    movl %ebx, %eax
; X64-NEXT:    popq %rbx
; X64-NEXT:    retq
entry:
  %0 = load i32, ptr @j, align 4
  %1 = load i32, ptr @k, align 4
  %add = add nsw i32 %0, %1
  ret i32 %add
}



;;;;; 32-bit targets







;;;;; 64-bit targets






;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; NoEMU: {{.*}}
