; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=x86_64-- < %s | FileCheck %s

; expand-ir-insts must also run with optnone

; Function Attrs: noinline optnone
define double @main(i224 %0) #0 {
; CHECK-LABEL: main:
; CHECK:       # %bb.0: # %entryitofp-entry
; CHECK-NEXT:    pushq %rbp
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    pushq %r15
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    pushq %r14
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    pushq %r13
; CHECK-NEXT:    .cfi_def_cfa_offset 40
; CHECK-NEXT:    pushq %r12
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 56
; CHECK-NEXT:    subq $72, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 128
; CHECK-NEXT:    .cfi_offset %rbx, -56
; CHECK-NEXT:    .cfi_offset %r12, -48
; CHECK-NEXT:    .cfi_offset %r13, -40
; CHECK-NEXT:    .cfi_offset %r14, -32
; CHECK-NEXT:    .cfi_offset %r15, -24
; CHECK-NEXT:    .cfi_offset %rbp, -16
; CHECK-NEXT:    movq %rcx, %r9
; CHECK-NEXT:    movl %r9d, %eax
; CHECK-NEXT:    movq %rdi, %rcx
; CHECK-NEXT:    orq %rdx, %rcx
; CHECK-NEXT:    movq %rsi, %r8
; CHECK-NEXT:    orq %rax, %r8
; CHECK-NEXT:    xorps %xmm0, %xmm0
; CHECK-NEXT:    orq %r8, %rcx
; CHECK-NEXT:    je .LBB0_10
; CHECK-NEXT:    jmp .LBB0_1
; CHECK-NEXT:  .LBB0_1: # %itofp-if-end
; CHECK-NEXT:    movslq %r9d, %rcx
; CHECK-NEXT:    movq %rcx, %rax
; CHECK-NEXT:    sarq $31, %rax
; CHECK-NEXT:    sarq $63, %rcx
; CHECK-NEXT:    xorq %rcx, %r9
; CHECK-NEXT:    xorq %rcx, %rdx
; CHECK-NEXT:    xorq %rcx, %rsi
; CHECK-NEXT:    xorq %rax, %rdi
; CHECK-NEXT:    subq %rax, %rdi
; CHECK-NEXT:    sbbq %rcx, %rsi
; CHECK-NEXT:    sbbq %rcx, %rdx
; CHECK-NEXT:    sbbq %rcx, %r9
; CHECK-NEXT:    movq %r9, %rcx
; CHECK-NEXT:    shldq $32, %rdx, %rcx
; CHECK-NEXT:    bsrq %rcx, %r11
; CHECK-NEXT:    xorl $63, %r11d
; CHECK-NEXT:    movq %rdx, %r8
; CHECK-NEXT:    shldq $32, %rsi, %r8
; CHECK-NEXT:    bsrq %r8, %r10
; CHECK-NEXT:    xorl $63, %r10d
; CHECK-NEXT:    orl $64, %r10d
; CHECK-NEXT:    testq %rcx, %rcx
; CHECK-NEXT:    cmovnel %r11d, %r10d
; CHECK-NEXT:    movq %rsi, %rbx
; CHECK-NEXT:    shldq $32, %rdi, %rbx
; CHECK-NEXT:    bsrq %rbx, %r14
; CHECK-NEXT:    xorl $63, %r14d
; CHECK-NEXT:    movq %rdi, %r11
; CHECK-NEXT:    shlq $32, %r11
; CHECK-NEXT:    bsrq %r11, %r11
; CHECK-NEXT:    xorl $63, %r11d
; CHECK-NEXT:    orl $64, %r11d
; CHECK-NEXT:    testq %rbx, %rbx
; CHECK-NEXT:    cmovnel %r14d, %r11d
; CHECK-NEXT:    subl $-128, %r11d
; CHECK-NEXT:    orq %rcx, %r8
; CHECK-NEXT:    cmovnel %r10d, %r11d
; CHECK-NEXT:    movl $224, %r10d
; CHECK-NEXT:    subl %r11d, %r10d
; CHECK-NEXT:    movl $223, %r8d
; CHECK-NEXT:    subl %r11d, %r8d
; CHECK-NEXT:    cmpl $53, %r10d
; CHECK-NEXT:    jle .LBB0_8
; CHECK-NEXT:  # %bb.2: # %itofp-if-then4
; CHECK-NEXT:    movl %r10d, %ecx
; CHECK-NEXT:    subl $54, %ecx
; CHECK-NEXT:    je .LBB0_4
; CHECK-NEXT:    jmp .LBB0_3
; CHECK-NEXT:  .LBB0_3: # %itofp-if-then4
; CHECK-NEXT:    movl %r10d, %ecx
; CHECK-NEXT:    subl $55, %ecx
; CHECK-NEXT:    jne .LBB0_5
; CHECK-NEXT:  # %bb.11:
; CHECK-NEXT:    jmp .LBB0_6
; CHECK-NEXT:  .LBB0_4: # %itofp-sw-bb
; CHECK-NEXT:    movq %rsi, %rcx
; CHECK-NEXT:    shldq $1, %rdi, %rcx
; CHECK-NEXT:    movq %rdx, %r11
; CHECK-NEXT:    shldq $1, %rsi, %r11
; CHECK-NEXT:    shldq $1, %rdx, %r9
; CHECK-NEXT:    addq %rdi, %rdi
; CHECK-NEXT:    movq %rcx, %rsi
; CHECK-NEXT:    movq %r11, %rdx
; CHECK-NEXT:    jmp .LBB0_6
; CHECK-NEXT:  .LBB0_5: # %itofp-sw-default
; CHECK-NEXT:    movq %rdi, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    movq %rsi, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    movq %rdx, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    movl %r9d, %ecx
; CHECK-NEXT:    movq %rcx, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    movb $-87, %cl
; CHECK-NEXT:    subb %r11b, %cl
; CHECK-NEXT:    movb %cl, %bl
; CHECK-NEXT:    shrb $6, %bl
; CHECK-NEXT:    movzbl %bl, %r12d
; CHECK-NEXT:    movq $0, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    movq $0, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    movq $0, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    movq $0, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    movq -40(%rsp,%r12,8), %rbx
; CHECK-NEXT:    movq -48(%rsp,%r12,8), %r13
; CHECK-NEXT:    movq %r13, %r14
; CHECK-NEXT:    shrdq %cl, %rbx, %r14
; CHECK-NEXT:    movq -64(%rsp,%r12,8), %r15
; CHECK-NEXT:    movq -56(%rsp,%r12,8), %rbp
; CHECK-NEXT:    movq %rbp, %r12
; CHECK-NEXT:    shrdq %cl, %r13, %r12
; CHECK-NEXT:    shrq %cl, %rbx
; CHECK-NEXT:    shrdq %cl, %rbp, %r15
; CHECK-NEXT:    addb $55, %r11b
; CHECK-NEXT:    movq %rdi, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    movq %rsi, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    movq %rdx, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    movq %r9, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    movq $0, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    movq $0, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    movq $0, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    movq $0, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    movb %r11b, %cl
; CHECK-NEXT:    shrb $3, %cl
; CHECK-NEXT:    andb $24, %cl
; CHECK-NEXT:    negb %cl
; CHECK-NEXT:    movsbq %cl, %rdx
; CHECK-NEXT:    movq -96(%rsp,%rdx), %rsi
; CHECK-NEXT:    movq -88(%rsp,%rdx), %rdi
; CHECK-NEXT:    movq -80(%rsp,%rdx), %r9
; CHECK-NEXT:    movb %r11b, %cl
; CHECK-NEXT:    movq %r9, %r13
; CHECK-NEXT:    shldq %cl, %rdi, %r13
; CHECK-NEXT:    movb %r11b, %cl
; CHECK-NEXT:    movq %rsi, %rbp
; CHECK-NEXT:    shlq %cl, %rbp
; CHECK-NEXT:    orq %r13, %rbp
; CHECK-NEXT:    movq -72(%rsp,%rdx), %rdx
; CHECK-NEXT:    movb %r11b, %cl
; CHECK-NEXT:    shldq %cl, %r9, %rdx
; CHECK-NEXT:    movl %edx, %edx
; CHECK-NEXT:    movb %r11b, %cl
; CHECK-NEXT:    shldq %cl, %rsi, %rdi
; CHECK-NEXT:    orq %rdx, %rdi
; CHECK-NEXT:    xorl %ecx, %ecx
; CHECK-NEXT:    orq %rdi, %rbp
; CHECK-NEXT:    setne %cl
; CHECK-NEXT:    orq %rcx, %r15
; CHECK-NEXT:    movq %r15, %rdi
; CHECK-NEXT:    movq %r12, %rsi
; CHECK-NEXT:    movq %r14, %rdx
; CHECK-NEXT:    movq %rbx, %r9
; CHECK-NEXT:    jmp .LBB0_6
; CHECK-NEXT:  .LBB0_6: # %itofp-sw-epilog
; CHECK-NEXT:    movl %edi, %ecx
; CHECK-NEXT:    shrl $2, %ecx
; CHECK-NEXT:    andl $1, %ecx
; CHECK-NEXT:    orq %rcx, %rdi
; CHECK-NEXT:    addq $1, %rdi
; CHECK-NEXT:    adcq $0, %rsi
; CHECK-NEXT:    adcq $0, %rdx
; CHECK-NEXT:    adcq $0, %r9
; CHECK-NEXT:    movq %rdi, %rdx
; CHECK-NEXT:    shrdq $2, %rsi, %rdx
; CHECK-NEXT:    movq %rdx, %rcx
; CHECK-NEXT:    shrq $32, %rcx
; CHECK-NEXT:    btq $55, %rdi
; CHECK-NEXT:    jae .LBB0_9
; CHECK-NEXT:    jmp .LBB0_7
; CHECK-NEXT:  .LBB0_7: # %itofp-if-then20
; CHECK-NEXT:    shrdq $3, %rsi, %rdi
; CHECK-NEXT:    movq %rdi, %rcx
; CHECK-NEXT:    shrq $32, %rcx
; CHECK-NEXT:    movq %rdi, %rdx
; CHECK-NEXT:    movl %r10d, %r8d
; CHECK-NEXT:    jmp .LBB0_9
; CHECK-NEXT:  .LBB0_8: # %itofp-if-else
; CHECK-NEXT:    movq %rdi, {{[0-9]+}}(%rsp)
; CHECK-NEXT:    movq %rsi, {{[0-9]+}}(%rsp)
; CHECK-NEXT:    movq %rdx, {{[0-9]+}}(%rsp)
; CHECK-NEXT:    movq %r9, {{[0-9]+}}(%rsp)
; CHECK-NEXT:    movq $0, {{[0-9]+}}(%rsp)
; CHECK-NEXT:    movq $0, {{[0-9]+}}(%rsp)
; CHECK-NEXT:    movq $0, {{[0-9]+}}(%rsp)
; CHECK-NEXT:    movq $0, (%rsp)
; CHECK-NEXT:    addb $85, %r11b
; CHECK-NEXT:    movb %r11b, %cl
; CHECK-NEXT:    shrb $3, %cl
; CHECK-NEXT:    andb $24, %cl
; CHECK-NEXT:    negb %cl
; CHECK-NEXT:    movsbq %cl, %rcx
; CHECK-NEXT:    movq 32(%rsp,%rcx), %rdx
; CHECK-NEXT:    movb %r11b, %cl
; CHECK-NEXT:    shlq %cl, %rdx
; CHECK-NEXT:    movq %rdx, %rcx
; CHECK-NEXT:    shrq $32, %rcx
; CHECK-NEXT:  .LBB0_9: # %itofp-if-end26
; CHECK-NEXT:    andl $-2147483648, %eax # imm = 0x80000000
; CHECK-NEXT:    shll $20, %r8d
; CHECK-NEXT:    addl $1072693248, %r8d # imm = 0x3FF00000
; CHECK-NEXT:    andl $1048575, %ecx # imm = 0xFFFFF
; CHECK-NEXT:    orl %eax, %ecx
; CHECK-NEXT:    orl %r8d, %ecx
; CHECK-NEXT:    movl %ecx, %eax
; CHECK-NEXT:    shlq $32, %rax
; CHECK-NEXT:    movabsq $4294967295, %rcx # imm = 0xFFFFFFFF
; CHECK-NEXT:    andq %rcx, %rdx
; CHECK-NEXT:    orq %rdx, %rax
; CHECK-NEXT:    movq %rax, %xmm0
; CHECK-NEXT:  .LBB0_10: # %itofp-return
; CHECK-NEXT:    addq $72, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 56
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    popq %r12
; CHECK-NEXT:    .cfi_def_cfa_offset 40
; CHECK-NEXT:    popq %r13
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    popq %r14
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    popq %r15
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    popq %rbp
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
entry:
  %x = sitofp i224 %0 to double
  ret double %x
}

attributes #0 = { noinline optnone }
