; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=x86_64-unknown-linux-gnu -verify-machineinstrs < %s | FileCheck %s --check-prefix=ASM
; RUN: llc -mtriple=x86_64-unknown-linux-gnu -verify-machineinstrs -stop-after=finalize-isel < %s | FileCheck %s --check-prefix=ISEL
; RUN: llc -mtriple=x86_64-unknown-linux-gnu -verify-machineinstrs -stop-after=kcfi < %s | FileCheck %s --check-prefix=KCFI

define void @f1(ptr noundef %x) !kcfi_type !1 {
; ASM-LABEL: f1:
; ASM:       # %bb.0:
; ASM-NEXT:    pushq %rax
; ASM-NEXT:    .cfi_def_cfa_offset 16
; ASM-NEXT:    movl $4282621618, %r10d # imm = 0xFF439EB2
; ASM-NEXT:    addl -4(%rdi), %r10d
; ASM-NEXT:    je .Ltmp0
; ASM-NEXT:  .Ltmp1:
; ASM-NEXT:    ud2
; ISEL-LABEL: name: f1
; ISEL: bb.0 (%ir-block.0):
; ISEL-NEXT:   liveins: $rdi
; ISEL-NEXT: {{  $}}
; ISEL-NEXT:   [[COPY:%[0-9]+]]:gr64 = COPY $rdi
; ISEL-NEXT:   ADJCALLSTACKDOWN64 0, 0, 0, implicit-def dead $rsp, implicit-def dead $eflags, implicit-def dead $ssp, implicit $rsp, implicit $ssp
; ISEL-NEXT:   CALL64r [[COPY]], csr_64, implicit $rsp, implicit $ssp, implicit-def $rsp, implicit-def $ssp, cfi-type 12345678
; ISEL-NEXT:   ADJCALLSTACKUP64 0, 0, implicit-def dead $rsp, implicit-def dead $eflags, implicit-def dead $ssp, implicit $rsp, implicit $ssp
; ISEL-NEXT:   RET 0
;
; KCFI-LABEL: name: f1
; KCFI: bb.0 (%ir-block.0):
; KCFI-NEXT:   liveins: $rdi
; KCFI-NEXT: {{  $}}
; KCFI-NEXT:   frame-setup PUSH64r undef $rax, implicit-def $rsp, implicit $rsp
; KCFI-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 16
; KCFI-NEXT:   BUNDLE implicit-def $r10, implicit-def $r11, implicit-def $eflags, implicit-def $rsp, implicit-def $ssp, implicit killed $rdi, implicit $rsp, implicit $ssp {
; KCFI-NEXT:     KCFI_CHECK $rdi, 12345678, implicit-def $r10, implicit-def $r11, implicit-def $eflags
; KCFI-NEXT:     CALL64r killed $rdi, csr_64, implicit $rsp, implicit $ssp, implicit-def $rsp, implicit-def $ssp
; KCFI-NEXT:   }
; KCFI-NEXT:   $rax = frame-destroy POP64r implicit-def $rsp, implicit $rsp
; KCFI-NEXT:   frame-destroy CFI_INSTRUCTION def_cfa_offset 8
; KCFI-NEXT:   RET64

  call void %x() [ "kcfi"(i32 12345678) ]
  ret void
}

define void @f2(ptr noundef %x) {
; ASM-LABEL: f2:
; ASM:       # %bb.0:
; ASM-NEXT:    movl $4282621618, %r10d # imm = 0xFF439EB2
; ASM-NEXT:    addl -4(%rdi), %r10d
; ASM-NEXT:    je .Ltmp3
; ASM-NEXT:  .Ltmp4:
; ASM-NEXT:    ud2
; ISEL-LABEL: name: f2
; ISEL: bb.0 (%ir-block.0):
; ISEL-NEXT:   liveins: $rdi
; ISEL-NEXT: {{  $}}
; ISEL-NEXT:   [[COPY:%[0-9]+]]:gr64_tc = COPY $rdi
; ISEL-NEXT:   TCRETURNri64 [[COPY]], 0, csr_64, implicit $rsp, implicit $ssp, cfi-type 12345678
;
; KCFI-LABEL: name: f2
; KCFI: bb.0 (%ir-block.0):
; KCFI-NEXT:   liveins: $rdi
; KCFI-NEXT: {{  $}}
; KCFI-NEXT:   BUNDLE implicit-def $r10, implicit-def $r11, implicit-def $eflags, implicit killed $rdi, implicit $rsp, implicit $ssp {
; KCFI-NEXT:     KCFI_CHECK $rdi, 12345678, implicit-def $r10, implicit-def $r11, implicit-def $eflags
; KCFI-NEXT:     TAILJMPr64 killed $rdi, csr_64, implicit $rsp, implicit $ssp, implicit $rsp, implicit $ssp
; KCFI-NEXT:   }

  tail call void %x() [ "kcfi"(i32 12345678) ]
  ret void
}

define void @f3(ptr noundef %x) #0 {
; ASM-LABEL: f3:
; ASM:       # %bb.0:
; ASM-NEXT:    pushq %rax
; ASM-NEXT:    .cfi_def_cfa_offset 16
; ASM-NEXT:    movq %rdi, %r11
; ASM-NEXT:    movl $4282621618, %r10d # imm = 0xFF439EB2
; ASM-NEXT:    addl -4(%r11), %r10d
; ASM-NEXT:    je .Ltmp6
; ASM-NEXT:  .Ltmp7:
; ASM-NEXT:    ud2
; ISEL-LABEL: name: f3
; ISEL: bb.0 (%ir-block.0):
; ISEL-NEXT:   liveins: $rdi
; ISEL-NEXT: {{  $}}
; ISEL-NEXT:   [[COPY:%[0-9]+]]:gr64 = COPY $rdi
; ISEL-NEXT:   ADJCALLSTACKDOWN64 0, 0, 0, implicit-def dead $rsp, implicit-def dead $eflags, implicit-def dead $ssp, implicit $rsp, implicit $ssp
; ISEL-NEXT:   $r11 = COPY [[COPY]]
; ISEL-NEXT:   CALL64pcrel32 &__llvm_retpoline_r11, csr_64, implicit $rsp, implicit $ssp, implicit-def $rsp, implicit-def $ssp, implicit killed $r11, cfi-type 12345678
; ISEL-NEXT:   ADJCALLSTACKUP64 0, 0, implicit-def dead $rsp, implicit-def dead $eflags, implicit-def dead $ssp, implicit $rsp, implicit $ssp
; ISEL-NEXT:   RET 0
;
; KCFI-LABEL: name: f3
; KCFI: bb.0 (%ir-block.0):
; KCFI-NEXT:   liveins: $rdi
; KCFI-NEXT: {{  $}}
; KCFI-NEXT:   frame-setup PUSH64r undef $rax, implicit-def $rsp, implicit $rsp
; KCFI-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 16
; KCFI-NEXT:   $r11 = MOV64rr killed $rdi
; KCFI-NEXT:   BUNDLE implicit-def $r10, implicit-def $r11, implicit-def $eflags, implicit-def $rsp, implicit-def $ssp, implicit $r11, implicit $rsp, implicit $ssp {
; KCFI-NEXT:     KCFI_CHECK $r11, 12345678, implicit-def $r10, implicit-def $r11, implicit-def $eflags
; KCFI-NEXT:     CALL64pcrel32 &__llvm_retpoline_r11, csr_64, implicit $rsp, implicit $ssp, implicit-def $rsp, implicit-def $ssp, implicit internal $r11
; KCFI-NEXT:   }
; KCFI-NEXT:   $rax = frame-destroy POP64r implicit-def $rsp, implicit $rsp
; KCFI-NEXT:   frame-destroy CFI_INSTRUCTION def_cfa_offset 8
; KCFI-NEXT:   RET64
  call void %x() [ "kcfi"(i32 12345678) ]
  ret void
}

define void @f4(ptr noundef %x) #0 {
; ASM-LABEL: f4:
; ASM:       # %bb.0:
; ASM-NEXT:    movq %rdi, %r11
; ASM-NEXT:    movl $4282621618, %r10d # imm = 0xFF439EB2
; ASM-NEXT:    addl -4(%r11), %r10d
; ASM-NEXT:    je .Ltmp9
; ASM-NEXT:  .Ltmp10:
; ASM-NEXT:    ud2
; ISEL-LABEL: name: f4
; ISEL: bb.0 (%ir-block.0):
; ISEL-NEXT:   liveins: $rdi
; ISEL-NEXT: {{  $}}
; ISEL-NEXT:   [[COPY:%[0-9]+]]:gr64 = COPY $rdi
; ISEL-NEXT:   $r11 = COPY [[COPY]]
; ISEL-NEXT:   TCRETURNdi64 &__llvm_retpoline_r11, 0, csr_64, implicit $rsp, implicit $ssp, implicit killed $r11, cfi-type 12345678
;
; KCFI-LABEL: name: f4
; KCFI: bb.0 (%ir-block.0):
; KCFI-NEXT:   liveins: $rdi
; KCFI-NEXT: {{  $}}
; KCFI-NEXT:   $r11 = MOV64rr killed $rdi
; KCFI-NEXT:   BUNDLE implicit-def $r10, implicit-def $r11, implicit-def $eflags, implicit $r11, implicit $rsp, implicit $ssp {
; KCFI-NEXT:     KCFI_CHECK $r11, 12345678, implicit-def $r10, implicit-def $r11, implicit-def $eflags
; KCFI-NEXT:     TAILJMPd64 &__llvm_retpoline_r11, csr_64, implicit $rsp, implicit $ssp, implicit $rsp, implicit $ssp, implicit internal $r11
; KCFI-NEXT:   }
  tail call void %x() [ "kcfi"(i32 12345678) ]
  ret void
}

;; Ensure we emit Value + 1 for unwanted values (e.g. endbr64 == 4196274163).
define void @f5(ptr noundef %x) !kcfi_type !2 {
; ASM-LABEL: f5:
; ASM:       # %bb.0:
; ASM-NEXT:    movl $98693132, %r10d # imm = 0x5E1F00C
; ASM-NEXT:    addl -4(%rdi), %r10d
; ASM-NEXT:    je .Ltmp12
; ASM-NEXT:  .Ltmp13:
; ASM-NEXT:    ud2
; ISEL-LABEL: name: f5
; ISEL: bb.0 (%ir-block.0):
; ISEL-NEXT:   liveins: $rdi
; ISEL-NEXT: {{  $}}
; ISEL-NEXT:   [[COPY:%[0-9]+]]:gr64_tc = COPY $rdi
; ISEL-NEXT:   TCRETURNri64 [[COPY]], 0, csr_64, implicit $rsp, implicit $ssp, cfi-type 4196274163
;
; KCFI-LABEL: name: f5
; KCFI: bb.0 (%ir-block.0):
; KCFI-NEXT:   liveins: $rdi
; KCFI-NEXT: {{  $}}
; KCFI-NEXT:   BUNDLE implicit-def $r10, implicit-def $r11, implicit-def $eflags, implicit killed $rdi, implicit $rsp, implicit $ssp {
; KCFI-NEXT:     KCFI_CHECK $rdi, 4196274163, implicit-def $r10, implicit-def $r11, implicit-def $eflags
; KCFI-NEXT:     TAILJMPr64 killed $rdi, csr_64, implicit $rsp, implicit $ssp, implicit $rsp, implicit $ssp
; KCFI-NEXT:   }
  tail call void %x() [ "kcfi"(i32 4196274163) ]
  ret void
}

;; Ensure we emit Value + 1 for unwanted values (e.g. -endbr64 == 98693133).
define void @f6(ptr noundef %x) !kcfi_type !3 {
; ASM-LABEL: f6:
; ASM:       # %bb.0:
; ASM-NEXT:    movl $4196274162, %r10d # imm = 0xFA1E0FF2
; ASM-NEXT:    addl -4(%rdi), %r10d
; ASM-NEXT:    je .Ltmp15
; ASM-NEXT:  .Ltmp16:
; ASM-NEXT:    ud2
; ISEL-LABEL: name: f6
; ISEL: bb.0 (%ir-block.0):
; ISEL-NEXT:   liveins: $rdi
; ISEL-NEXT: {{  $}}
; ISEL-NEXT:   [[COPY:%[0-9]+]]:gr64_tc = COPY $rdi
; ISEL-NEXT:   TCRETURNri64 [[COPY]], 0, csr_64, implicit $rsp, implicit $ssp, cfi-type 98693133
;
; KCFI-LABEL: name: f6
; KCFI: bb.0 (%ir-block.0):
; KCFI-NEXT:   liveins: $rdi
; KCFI-NEXT: {{  $}}
; KCFI-NEXT:   BUNDLE implicit-def $r10, implicit-def $r11, implicit-def $eflags, implicit killed $rdi, implicit $rsp, implicit $ssp {
; KCFI-NEXT:     KCFI_CHECK $rdi, 98693133, implicit-def $r10, implicit-def $r11, implicit-def $eflags
; KCFI-NEXT:     TAILJMPr64 killed $rdi, csr_64, implicit $rsp, implicit $ssp, implicit $rsp, implicit $ssp
; KCFI-NEXT:   }
  tail call void %x() [ "kcfi"(i32 98693133) ]
  ret void
}

@g = external local_unnamed_addr global ptr, align 8

define void @f7() {
; ASM-LABEL: f7:
; ASM:       # %bb.0:
; ASM-NEXT:    movq g@GOTPCREL(%rip), %rax
; ASM-NEXT:    movq (%rax), %r11
; ASM-NEXT:    movl $4282621618, %r10d # imm = 0xFF439EB2
; ASM-NEXT:    addl -4(%r11), %r10d
; ASM-NEXT:    je .Ltmp18
; ASM-NEXT:  .Ltmp19:
; ASM-NEXT:    ud2
; ISEL-LABEL: name: f7
; ISEL: bb.0 (%ir-block.0):
; ISEL-NEXT:   [[MOV64rm:%[0-9]+]]:gr64_tc = MOV64rm $rip, 1, $noreg, target-flags(x86-gotpcrel) @g, $noreg :: (load (s64) from got)
; ISEL-NEXT:   TCRETURNmi64 killed [[MOV64rm]], 1, $noreg, 0, $noreg, 0, csr_64, implicit $rsp, implicit $ssp, cfi-type 12345678 :: (dereferenceable load (s64) from @g)
;
; KCFI-LABEL: name: f7
; KCFI: bb.0 (%ir-block.0):
; KCFI-NEXT:   renamable $rax = MOV64rm $rip, 1, $noreg, target-flags(x86-gotpcrel) @g, $noreg :: (load (s64) from got)
; KCFI-NEXT:   $r11 = MOV64rm killed renamable $rax, 1, $noreg, 0, $noreg
; KCFI-NEXT:   BUNDLE implicit-def $r10, implicit-def $r11, implicit-def $eflags, implicit $r11, implicit $rsp, implicit $ssp {
; KCFI-NEXT:     KCFI_CHECK $r11, 12345678, implicit-def $r10, implicit-def $r11, implicit-def $eflags
; KCFI-NEXT:     TAILJMPr64 internal $r11, csr_64, implicit $rsp, implicit $ssp, implicit $rsp, implicit $ssp
; KCFI-NEXT:   }
  %1 = load ptr, ptr @g, align 8
  tail call void %1() [ "kcfi"(i32 12345678) ]
  ret void
}

define void @f8() {
; ASM-LABEL: f8:
; ASM:       # %bb.0:
; ASM-NEXT:    pushq %rax
; ASM-NEXT:    .cfi_def_cfa_offset 16
; ASM-NEXT:    movq g@GOTPCREL(%rip), %rax
; ASM-NEXT:    movq (%rax), %r11
; ASM-NEXT:    movl $4282621618, %r10d # imm = 0xFF439EB2
; ASM-NEXT:    addl -4(%r11), %r10d
; ASM-NEXT:    je .Ltmp21
; ASM-NEXT:  .Ltmp22:
; ASM-NEXT:    ud2
; ISEL-LABEL: name: f8
; ISEL: bb.0 (%ir-block.0):
; ISEL-NEXT:   [[MOV64rm:%[0-9]+]]:gr64 = MOV64rm $rip, 1, $noreg, target-flags(x86-gotpcrel) @g, $noreg :: (load (s64) from got)
; ISEL-NEXT:   ADJCALLSTACKDOWN64 0, 0, 0, implicit-def dead $rsp, implicit-def dead $eflags, implicit-def dead $ssp, implicit $rsp, implicit $ssp
; ISEL-NEXT:   CALL64m killed [[MOV64rm]], 1, $noreg, 0, $noreg, csr_64, implicit $rsp, implicit $ssp, implicit-def $rsp, implicit-def $ssp, cfi-type 12345678 :: (dereferenceable load (s64) from @g)
; ISEL-NEXT:   ADJCALLSTACKUP64 0, 0, implicit-def dead $rsp, implicit-def dead $eflags, implicit-def dead $ssp, implicit $rsp, implicit $ssp
; ISEL-NEXT:   RET 0
;
; KCFI-LABEL: name: f8
; KCFI: bb.0 (%ir-block.0):
; KCFI-NEXT:   frame-setup PUSH64r undef $rax, implicit-def $rsp, implicit $rsp
; KCFI-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 16
; KCFI-NEXT:   renamable $rax = MOV64rm $rip, 1, $noreg, target-flags(x86-gotpcrel) @g, $noreg :: (load (s64) from got)
; KCFI-NEXT:   $r11 = MOV64rm killed renamable $rax, 1, $noreg, 0, $noreg :: (dereferenceable load (s64) from @g)
; KCFI-NEXT:   BUNDLE implicit-def $r10, implicit-def $r11, implicit-def $eflags, implicit-def $rsp, implicit-def $ssp, implicit $r11, implicit $rsp, implicit $ssp {
; KCFI-NEXT:     KCFI_CHECK $r11, 12345678, implicit-def $r10, implicit-def $r11, implicit-def $eflags
; KCFI-NEXT:     CALL64r internal $r11, csr_64, implicit $rsp, implicit $ssp, implicit-def $rsp, implicit-def $ssp
; KCFI-NEXT:   }
; KCFI-NEXT:   $rax = frame-destroy POP64r implicit-def $rsp, implicit $rsp
; KCFI-NEXT:   frame-destroy CFI_INSTRUCTION def_cfa_offset 8
; KCFI-NEXT:   RET64
  %1 = load ptr, ptr @g, align 8
  call void %1() [ "kcfi"(i32 12345678) ]
  ret void
}

declare i32 @__gxx_personality_v0(...)

define void @f9() personality ptr @__gxx_personality_v0 {
; ASM-LABEL: f9:
; ASM:       # %bb.0:
; ASM-NEXT:    pushq %rax
; ASM-NEXT:    .cfi_def_cfa_offset 16
; ASM-NEXT:    movq g@GOTPCREL(%rip), %rax
; ASM-NEXT:    movq (%rax), %r11
; ASM-NEXT:    movl $4282621618, %r10d # imm = 0xFF439EB2
; ASM-NEXT:    addl -4(%r11), %r10d
; ASM-NEXT:    je .Ltmp24
; ASM-NEXT:  .Ltmp25:
; ASM-NEXT:    ud2
; ISEL-LABEL: name: f9
; ISEL: bb.0 (%ir-block.0):
; ISEL-NEXT:   successors: %bb.1(0x80000000)
; ISEL-NEXT: {{  $}}
; ISEL-NEXT:   [[MOV64rm:%[0-9]+]]:gr64 = MOV64rm $rip, 1, $noreg, target-flags(x86-gotpcrel) @g, $noreg :: (load (s64) from got)
; ISEL-NEXT:   ADJCALLSTACKDOWN64 0, 0, 0, implicit-def dead $rsp, implicit-def dead $eflags, implicit-def dead $ssp, implicit $rsp, implicit $ssp
; ISEL-NEXT:   CALL64m killed [[MOV64rm]], 1, $noreg, 0, $noreg, csr_64, implicit $rsp, implicit $ssp, implicit-def $rsp, implicit-def $ssp, cfi-type 12345678 :: (dereferenceable load (s64) from @g)
; ISEL-NEXT:   ADJCALLSTACKUP64 0, 0, implicit-def dead $rsp, implicit-def dead $eflags, implicit-def dead $ssp, implicit $rsp, implicit $ssp
; ISEL-NEXT: {{  $}}
; ISEL-NEXT: bb.1.cont:
; ISEL-NEXT:   RET 0
;
; KCFI-LABEL: name: f9
; KCFI: bb.0 (%ir-block.0):
; KCFI-NEXT:   frame-setup PUSH64r undef $rax, implicit-def $rsp, implicit $rsp
; KCFI-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 16
; KCFI-NEXT:   renamable $rax = MOV64rm $rip, 1, $noreg, target-flags(x86-gotpcrel) @g, $noreg :: (load (s64) from got)
; KCFI-NEXT:   $r11 = MOV64rm killed renamable $rax, 1, $noreg, 0, $noreg :: (dereferenceable load (s64) from @g)
; KCFI-NEXT:   BUNDLE implicit-def $r10, implicit-def $r11, implicit-def $eflags, implicit-def $rsp, implicit-def $ssp, implicit $r11, implicit $rsp, implicit $ssp {
; KCFI-NEXT:     KCFI_CHECK $r11, 12345678, implicit-def $r10, implicit-def $r11, implicit-def $eflags
; KCFI-NEXT:     CALL64r internal $r11, csr_64, implicit $rsp, implicit $ssp, implicit-def $rsp, implicit-def $ssp
; KCFI-NEXT:   }
; KCFI-NEXT:   $rax = frame-destroy POP64r implicit-def $rsp, implicit $rsp
; KCFI-NEXT:   frame-destroy CFI_INSTRUCTION def_cfa_offset 8
; KCFI-NEXT:   RET64
  %1 = load ptr, ptr @g, align 8
  invoke void %1() [ "kcfi"(i32 12345678) ]
    to label %cont
    unwind label %err
cont:
  ret void
err:
  %exn = landingpad { i8*, i32 }
          catch i8* null
  resume { i8*, i32 } %exn
}

attributes #0 = { "target-features"="+retpoline-indirect-branches,+retpoline-indirect-calls" }

!llvm.module.flags = !{!0}
!0 = !{i32 4, !"kcfi", i32 1}
!1 = !{i32 12345678}
!2 = !{i32 4196274163}
!3 = !{i32 98693133}
