; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=x86_64-unknown-linux-gnu -verify-machineinstrs < %s | FileCheck %s --check-prefix=ASM
; RUN: llc -mtriple=x86_64-unknown-none -verify-machineinstrs < %s | FileCheck %s --check-prefix=ASM
; RUN: llc -mtriple=x86_64-unknown-linux-gnu -verify-machineinstrs -stop-after=finalize-isel < %s | FileCheck %s --check-prefix=ISEL
; RUN: llc -mtriple=x86_64-unknown-linux-gnu -verify-machineinstrs -stop-after=kcfi < %s | FileCheck %s --check-prefix=KCFI

define void @f1(ptr noundef %x) !kcfi_type !1 {
; ASM-LABEL: f1:
; ASM:       # %bb.0:
; ASM-NEXT:    pushq %rax
; ASM-NEXT:    .cfi_def_cfa_offset 16
; ASM-NEXT:    movl $4282621618, %r10d # imm = 0xFF439EB2
; ASM-NEXT:    addl -4(%rdi), %r10d
; ASM-NEXT:    je .Ltmp0
; ASM-NEXT:  .Ltmp1:
; ASM-NEXT:    ud2
; ISEL-LABEL: name: f1
; ISEL: bb.0 (%ir-block.0):
; ISEL-NEXT:   liveins: $rdi
; ISEL-NEXT: {{  $}}
; ISEL-NEXT:   [[COPY:%[0-9]+]]:gr64 = COPY $rdi
; ISEL-NEXT:   ADJCALLSTACKDOWN64 0, 0, 0, implicit-def dead $rsp, implicit-def dead $eflags, implicit-def dead $ssp, implicit $rsp, implicit $ssp
; ISEL-NEXT:   CALL64r [[COPY]], csr_64, implicit $rsp, implicit $ssp, implicit-def $rsp, implicit-def $ssp, cfi-type 12345678
; ISEL-NEXT:   ADJCALLSTACKUP64 0, 0, implicit-def dead $rsp, implicit-def dead $eflags, implicit-def dead $ssp, implicit $rsp, implicit $ssp
; ISEL-NEXT:   RET 0
;
; KCFI-LABEL: name: f1
; KCFI: bb.0 (%ir-block.0):
; KCFI-NEXT:   liveins: $rdi
; KCFI-NEXT: {{  $}}
; KCFI-NEXT:   frame-setup PUSH64r undef $rax, implicit-def $rsp, implicit $rsp
; KCFI-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 16
; KCFI-NEXT:   BUNDLE implicit-def $r10, implicit-def $r11, implicit-def $eflags, implicit-def $rsp, implicit-def $ssp, implicit killed $rdi, implicit $rsp, implicit $ssp {
; KCFI-NEXT:     KCFI_CHECK $rdi, 12345678, implicit-def $r10, implicit-def $r11, implicit-def $eflags
; KCFI-NEXT:     CALL64r killed $rdi, csr_64, implicit $rsp, implicit $ssp, implicit-def $rsp, implicit-def $ssp
; KCFI-NEXT:   }
; KCFI-NEXT:   $rax = frame-destroy POP64r implicit-def $rsp, implicit $rsp
; KCFI-NEXT:   frame-destroy CFI_INSTRUCTION def_cfa_offset 8
; KCFI-NEXT:   RET64

  call void %x() [ "kcfi"(i32 12345678) ]
  ret void
}

define void @f2(ptr noundef %x) {
; ASM-LABEL: f2:
; ASM:       # %bb.0:
; ASM-NEXT:    movl $4282621618, %r10d # imm = 0xFF439EB2
; ASM-NEXT:    addl -4(%rdi), %r10d
; ASM-NEXT:    je .Ltmp3
; ASM-NEXT:  .Ltmp4:
; ASM-NEXT:    ud2
; ISEL-LABEL: name: f2
; ISEL: bb.0 (%ir-block.0):
; ISEL-NEXT:   liveins: $rdi
; ISEL-NEXT: {{  $}}
; ISEL-NEXT:   [[COPY:%[0-9]+]]:gr64_tc = COPY $rdi
; ISEL-NEXT:   TCRETURNri64 [[COPY]], 0, csr_64, implicit $rsp, implicit $ssp, cfi-type 12345678
;
; KCFI-LABEL: name: f2
; KCFI: bb.0 (%ir-block.0):
; KCFI-NEXT:   liveins: $rdi
; KCFI-NEXT: {{  $}}
; KCFI-NEXT:   BUNDLE implicit-def $r10, implicit-def $r11, implicit-def $eflags, implicit killed $rdi, implicit $rsp, implicit $ssp {
; KCFI-NEXT:     KCFI_CHECK $rdi, 12345678, implicit-def $r10, implicit-def $r11, implicit-def $eflags
; KCFI-NEXT:     TAILJMPr64 killed $rdi, csr_64, implicit $rsp, implicit $ssp, implicit $rsp, implicit $ssp
; KCFI-NEXT:   }

  tail call void %x() [ "kcfi"(i32 12345678) ]
  ret void
}

define void @f3(ptr noundef %x) #0 {
; ASM-LABEL: f3:
; ASM:       # %bb.0:
; ASM-NEXT:    pushq %rax
; ASM-NEXT:    .cfi_def_cfa_offset 16
; ASM-NEXT:    movq %rdi, %r11
; ASM-NEXT:    movl $4282621618, %r10d # imm = 0xFF439EB2
; ASM-NEXT:    addl -4(%r11), %r10d
; ASM-NEXT:    je .Ltmp6
; ASM-NEXT:  .Ltmp7:
; ASM-NEXT:    ud2
; ISEL-LABEL: name: f3
; ISEL: bb.0 (%ir-block.0):
; ISEL-NEXT:   liveins: $rdi
; ISEL-NEXT: {{  $}}
; ISEL-NEXT:   [[COPY:%[0-9]+]]:gr64 = COPY $rdi
; ISEL-NEXT:   ADJCALLSTACKDOWN64 0, 0, 0, implicit-def dead $rsp, implicit-def dead $eflags, implicit-def dead $ssp, implicit $rsp, implicit $ssp
; ISEL-NEXT:   $r11 = COPY [[COPY]]
; ISEL-NEXT:   CALL64pcrel32 &__llvm_retpoline_r11, csr_64, implicit $rsp, implicit $ssp, implicit-def $rsp, implicit-def $ssp, implicit killed $r11, cfi-type 12345678
; ISEL-NEXT:   ADJCALLSTACKUP64 0, 0, implicit-def dead $rsp, implicit-def dead $eflags, implicit-def dead $ssp, implicit $rsp, implicit $ssp
; ISEL-NEXT:   RET 0
;
; KCFI-LABEL: name: f3
; KCFI: bb.0 (%ir-block.0):
; KCFI-NEXT:   liveins: $rdi
; KCFI-NEXT: {{  $}}
; KCFI-NEXT:   frame-setup PUSH64r undef $rax, implicit-def $rsp, implicit $rsp
; KCFI-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 16
; KCFI-NEXT:   $r11 = MOV64rr killed $rdi
; KCFI-NEXT:   BUNDLE implicit-def $r10, implicit-def $r11, implicit-def $eflags, implicit-def $rsp, implicit-def $ssp, implicit $r11, implicit $rsp, implicit $ssp {
; KCFI-NEXT:     KCFI_CHECK $r11, 12345678, implicit-def $r10, implicit-def $r11, implicit-def $eflags
; KCFI-NEXT:     CALL64pcrel32 &__llvm_retpoline_r11, csr_64, implicit $rsp, implicit $ssp, implicit-def $rsp, implicit-def $ssp, implicit internal $r11
; KCFI-NEXT:   }
; KCFI-NEXT:   $rax = frame-destroy POP64r implicit-def $rsp, implicit $rsp
; KCFI-NEXT:   frame-destroy CFI_INSTRUCTION def_cfa_offset 8
; KCFI-NEXT:   RET64
  call void %x() [ "kcfi"(i32 12345678) ]
  ret void
}

define void @f4(ptr noundef %x) #0 {
; ASM-LABEL: f4:
; ASM:       # %bb.0:
; ASM-NEXT:    movq %rdi, %r11
; ASM-NEXT:    movl $4282621618, %r10d # imm = 0xFF439EB2
; ASM-NEXT:    addl -4(%r11), %r10d
; ASM-NEXT:    je .Ltmp9
; ASM-NEXT:  .Ltmp10:
; ASM-NEXT:    ud2
; ISEL-LABEL: name: f4
; ISEL: bb.0 (%ir-block.0):
; ISEL-NEXT:   liveins: $rdi
; ISEL-NEXT: {{  $}}
; ISEL-NEXT:   [[COPY:%[0-9]+]]:gr64 = COPY $rdi
; ISEL-NEXT:   $r11 = COPY [[COPY]]
; ISEL-NEXT:   TCRETURNdi64 &__llvm_retpoline_r11, 0, csr_64, implicit $rsp, implicit $ssp, implicit killed $r11, cfi-type 12345678
;
; KCFI-LABEL: name: f4
; KCFI: bb.0 (%ir-block.0):
; KCFI-NEXT:   liveins: $rdi
; KCFI-NEXT: {{  $}}
; KCFI-NEXT:   $r11 = MOV64rr killed $rdi
; KCFI-NEXT:   BUNDLE implicit-def $r10, implicit-def $r11, implicit-def $eflags, implicit $r11, implicit $rsp, implicit $ssp {
; KCFI-NEXT:     KCFI_CHECK $r11, 12345678, implicit-def $r10, implicit-def $r11, implicit-def $eflags
; KCFI-NEXT:     TAILJMPd64 &__llvm_retpoline_r11, csr_64, implicit $rsp, implicit $ssp, implicit $rsp, implicit $ssp, implicit internal $r11
; KCFI-NEXT:   }
  tail call void %x() [ "kcfi"(i32 12345678) ]
  ret void
}

;; Ensure we emit Value + 1 for unwanted values (e.g. endbr64 == 4196274163).
define void @f5(ptr noundef %x) !kcfi_type !2 {
; ASM-LABEL: f5:
; ASM:       # %bb.0:
; ASM-NEXT:    movl $98693132, %r10d # imm = 0x5E1F00C
; ASM-NEXT:    addl -4(%rdi), %r10d
; ASM-NEXT:    je .Ltmp12
; ASM-NEXT:  .Ltmp13:
; ASM-NEXT:    ud2
; ISEL-LABEL: name: f5
; ISEL: bb.0 (%ir-block.0):
; ISEL-NEXT:   liveins: $rdi
; ISEL-NEXT: {{  $}}
; ISEL-NEXT:   [[COPY:%[0-9]+]]:gr64_tc = COPY $rdi
; ISEL-NEXT:   TCRETURNri64 [[COPY]], 0, csr_64, implicit $rsp, implicit $ssp, cfi-type 4196274163
;
; KCFI-LABEL: name: f5
; KCFI: bb.0 (%ir-block.0):
; KCFI-NEXT:   liveins: $rdi
; KCFI-NEXT: {{  $}}
; KCFI-NEXT:   BUNDLE implicit-def $r10, implicit-def $r11, implicit-def $eflags, implicit killed $rdi, implicit $rsp, implicit $ssp {
; KCFI-NEXT:     KCFI_CHECK $rdi, 4196274163, implicit-def $r10, implicit-def $r11, implicit-def $eflags
; KCFI-NEXT:     TAILJMPr64 killed $rdi, csr_64, implicit $rsp, implicit $ssp, implicit $rsp, implicit $ssp
; KCFI-NEXT:   }
  tail call void %x() [ "kcfi"(i32 4196274163) ]
  ret void
}

;; Ensure we emit Value + 1 for unwanted values (e.g. -endbr64 == 98693133).
define void @f6(ptr noundef %x) !kcfi_type !3 {
; ASM-LABEL: f6:
; ASM:       # %bb.0:
; ASM-NEXT:    movl $4196274162, %r10d # imm = 0xFA1E0FF2
; ASM-NEXT:    addl -4(%rdi), %r10d
; ASM-NEXT:    je .Ltmp15
; ASM-NEXT:  .Ltmp16:
; ASM-NEXT:    ud2
; ISEL-LABEL: name: f6
; ISEL: bb.0 (%ir-block.0):
; ISEL-NEXT:   liveins: $rdi
; ISEL-NEXT: {{  $}}
; ISEL-NEXT:   [[COPY:%[0-9]+]]:gr64_tc = COPY $rdi
; ISEL-NEXT:   TCRETURNri64 [[COPY]], 0, csr_64, implicit $rsp, implicit $ssp, cfi-type 98693133
;
; KCFI-LABEL: name: f6
; KCFI: bb.0 (%ir-block.0):
; KCFI-NEXT:   liveins: $rdi
; KCFI-NEXT: {{  $}}
; KCFI-NEXT:   BUNDLE implicit-def $r10, implicit-def $r11, implicit-def $eflags, implicit killed $rdi, implicit $rsp, implicit $ssp {
; KCFI-NEXT:     KCFI_CHECK $rdi, 98693133, implicit-def $r10, implicit-def $r11, implicit-def $eflags
; KCFI-NEXT:     TAILJMPr64 killed $rdi, csr_64, implicit $rsp, implicit $ssp, implicit $rsp, implicit $ssp
; KCFI-NEXT:   }
  tail call void %x() [ "kcfi"(i32 98693133) ]
  ret void
}

@g = external local_unnamed_addr global ptr, align 8

define void @f7() {
; ASM-LABEL: f7:
; ASM:       # %bb.0:
; ASM-NEXT:    movq g@GOTPCREL(%rip), %rax
; ASM-NEXT:    movq (%rax), %r11
; ASM-NEXT:    movl $4282621618, %r10d # imm = 0xFF439EB2
; ASM-NEXT:    addl -4(%r11), %r10d
; ASM-NEXT:    je .Ltmp18
; ASM-NEXT:  .Ltmp19:
; ASM-NEXT:    ud2
; ISEL-LABEL: name: f7
; ISEL: bb.0 (%ir-block.0):
; ISEL-NEXT:   [[MOV64rm:%[0-9]+]]:gr64_tc = MOV64rm $rip, 1, $noreg, target-flags(x86-gotpcrel) @g, $noreg :: (load (s64) from got)
; ISEL-NEXT:   TCRETURNmi64 killed [[MOV64rm]], 1, $noreg, 0, $noreg, 0, csr_64, implicit $rsp, implicit $ssp, cfi-type 12345678 :: (dereferenceable load (s64) from @g)
;
; KCFI-LABEL: name: f7
; KCFI: bb.0 (%ir-block.0):
; KCFI-NEXT:   renamable $rax = MOV64rm $rip, 1, $noreg, target-flags(x86-gotpcrel) @g, $noreg :: (load (s64) from got)
; KCFI-NEXT:   $r11 = MOV64rm killed renamable $rax, 1, $noreg, 0, $noreg
; KCFI-NEXT:   BUNDLE implicit-def $r10, implicit-def $r11, implicit-def $eflags, implicit $r11, implicit $rsp, implicit $ssp {
; KCFI-NEXT:     KCFI_CHECK $r11, 12345678, implicit-def $r10, implicit-def $r11, implicit-def $eflags
; KCFI-NEXT:     TAILJMPr64 internal $r11, csr_64, implicit $rsp, implicit $ssp, implicit $rsp, implicit $ssp
; KCFI-NEXT:   }
  %1 = load ptr, ptr @g, align 8
  tail call void %1() [ "kcfi"(i32 12345678) ]
  ret void
}

define void @f8() {
; ASM-LABEL: f8:
; ASM:       # %bb.0:
; ASM-NEXT:    pushq %rax
; ASM-NEXT:    .cfi_def_cfa_offset 16
; ASM-NEXT:    movq g@GOTPCREL(%rip), %rax
; ASM-NEXT:    movq (%rax), %r11
; ASM-NEXT:    movl $4282621618, %r10d # imm = 0xFF439EB2
; ASM-NEXT:    addl -4(%r11), %r10d
; ASM-NEXT:    je .Ltmp21
; ASM-NEXT:  .Ltmp22:
; ASM-NEXT:    ud2
; ISEL-LABEL: name: f8
; ISEL: bb.0 (%ir-block.0):
; ISEL-NEXT:   [[MOV64rm:%[0-9]+]]:gr64 = MOV64rm $rip, 1, $noreg, target-flags(x86-gotpcrel) @g, $noreg :: (load (s64) from got)
; ISEL-NEXT:   ADJCALLSTACKDOWN64 0, 0, 0, implicit-def dead $rsp, implicit-def dead $eflags, implicit-def dead $ssp, implicit $rsp, implicit $ssp
; ISEL-NEXT:   CALL64m killed [[MOV64rm]], 1, $noreg, 0, $noreg, csr_64, implicit $rsp, implicit $ssp, implicit-def $rsp, implicit-def $ssp, cfi-type 12345678 :: (dereferenceable load (s64) from @g)
; ISEL-NEXT:   ADJCALLSTACKUP64 0, 0, implicit-def dead $rsp, implicit-def dead $eflags, implicit-def dead $ssp, implicit $rsp, implicit $ssp
; ISEL-NEXT:   RET 0
;
; KCFI-LABEL: name: f8
; KCFI: bb.0 (%ir-block.0):
; KCFI-NEXT:   frame-setup PUSH64r undef $rax, implicit-def $rsp, implicit $rsp
; KCFI-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 16
; KCFI-NEXT:   renamable $rax = MOV64rm $rip, 1, $noreg, target-flags(x86-gotpcrel) @g, $noreg :: (load (s64) from got)
; KCFI-NEXT:   $r11 = MOV64rm killed renamable $rax, 1, $noreg, 0, $noreg :: (dereferenceable load (s64) from @g)
; KCFI-NEXT:   BUNDLE implicit-def $r10, implicit-def $r11, implicit-def $eflags, implicit-def $rsp, implicit-def $ssp, implicit $r11, implicit $rsp, implicit $ssp {
; KCFI-NEXT:     KCFI_CHECK $r11, 12345678, implicit-def $r10, implicit-def $r11, implicit-def $eflags
; KCFI-NEXT:     CALL64r internal $r11, csr_64, implicit $rsp, implicit $ssp, implicit-def $rsp, implicit-def $ssp
; KCFI-NEXT:   }
; KCFI-NEXT:   $rax = frame-destroy POP64r implicit-def $rsp, implicit $rsp
; KCFI-NEXT:   frame-destroy CFI_INSTRUCTION def_cfa_offset 8
; KCFI-NEXT:   RET64
  %1 = load ptr, ptr @g, align 8
  call void %1() [ "kcfi"(i32 12345678) ]
  ret void
}

%struct.S9 = type { [10 x i64] }

;; Ensure that functions with large (e.g., greater than 8 bytes) arguments passed on the stack are assigned arity=7
define dso_local void @f9(ptr noundef byval(%struct.S9) align 8 %s) !kcfi_type !4  {
; ASM-LABEL: f9:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    retq
; ISEL-LABEL: name: f9
; ISEL: bb.0.entry:
; ISEL-NEXT:   RET 0
;
; KCFI-LABEL: name: f9
; KCFI: bb.0.entry:
; KCFI-NEXT:   RET64
entry:
  ret void
}

;; Ensure that functions with fewer than 7 register arguments and no stack arguments are assigned arity<7
define dso_local void @f10(i32 noundef %v1, i32 noundef %v2, i32 noundef %v3, i32 noundef %v4, i32 noundef %v5, i32 noundef %v6) #0 !kcfi_type !5 {
; ASM-LABEL: f10:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    movl %edi, -{{[0-9]+}}(%rsp)
; ASM-NEXT:    movl %esi, -{{[0-9]+}}(%rsp)
; ASM-NEXT:    movl %edx, -{{[0-9]+}}(%rsp)
; ASM-NEXT:    movl %ecx, -{{[0-9]+}}(%rsp)
; ASM-NEXT:    movl %r8d, -{{[0-9]+}}(%rsp)
; ASM-NEXT:    movl %r9d, -{{[0-9]+}}(%rsp)
; ASM-NEXT:    retq
; ISEL-LABEL: name: f10
; ISEL: bb.0.entry:
; ISEL-NEXT:   liveins: $edi, $esi, $edx, $ecx, $r8d, $r9d
; ISEL-NEXT: {{  $}}
; ISEL-NEXT:   [[COPY:%[0-9]+]]:gr32 = COPY $r9d
; ISEL-NEXT:   [[COPY1:%[0-9]+]]:gr32 = COPY $r8d
; ISEL-NEXT:   [[COPY2:%[0-9]+]]:gr32 = COPY $ecx
; ISEL-NEXT:   [[COPY3:%[0-9]+]]:gr32 = COPY $edx
; ISEL-NEXT:   [[COPY4:%[0-9]+]]:gr32 = COPY $esi
; ISEL-NEXT:   [[COPY5:%[0-9]+]]:gr32 = COPY $edi
; ISEL-NEXT:   MOV32mr %stack.0.v1.addr, 1, $noreg, 0, $noreg, [[COPY5]] :: (store (s32) into %ir.v1.addr)
; ISEL-NEXT:   MOV32mr %stack.1.v2.addr, 1, $noreg, 0, $noreg, [[COPY4]] :: (store (s32) into %ir.v2.addr)
; ISEL-NEXT:   MOV32mr %stack.2.v3.addr, 1, $noreg, 0, $noreg, [[COPY3]] :: (store (s32) into %ir.v3.addr)
; ISEL-NEXT:   MOV32mr %stack.3.v4.addr, 1, $noreg, 0, $noreg, [[COPY2]] :: (store (s32) into %ir.v4.addr)
; ISEL-NEXT:   MOV32mr %stack.4.v5.addr, 1, $noreg, 0, $noreg, [[COPY1]] :: (store (s32) into %ir.v5.addr)
; ISEL-NEXT:   MOV32mr %stack.5.v6.addr, 1, $noreg, 0, $noreg, [[COPY]] :: (store (s32) into %ir.v6.addr)
; ISEL-NEXT:   RET 0
;
; KCFI-LABEL: name: f10
; KCFI: bb.0.entry:
; KCFI-NEXT:   liveins: $ecx, $edi, $edx, $esi, $r8d, $r9d
; KCFI-NEXT: {{  $}}
; KCFI-NEXT:   MOV32mr $rsp, 1, $noreg, -4, $noreg, killed renamable $edi :: (store (s32) into %ir.v1.addr)
; KCFI-NEXT:   MOV32mr $rsp, 1, $noreg, -8, $noreg, killed renamable $esi :: (store (s32) into %ir.v2.addr)
; KCFI-NEXT:   MOV32mr $rsp, 1, $noreg, -12, $noreg, killed renamable $edx :: (store (s32) into %ir.v3.addr)
; KCFI-NEXT:   MOV32mr $rsp, 1, $noreg, -16, $noreg, killed renamable $ecx :: (store (s32) into %ir.v4.addr)
; KCFI-NEXT:   MOV32mr $rsp, 1, $noreg, -20, $noreg, killed renamable $r8d :: (store (s32) into %ir.v5.addr)
; KCFI-NEXT:   MOV32mr $rsp, 1, $noreg, -24, $noreg, killed renamable $r9d :: (store (s32) into %ir.v6.addr)
; KCFI-NEXT:   RET64
entry:
  %v1.addr = alloca i32, align 4
  %v2.addr = alloca i32, align 4
  %v3.addr = alloca i32, align 4
  %v4.addr = alloca i32, align 4
  %v5.addr = alloca i32, align 4
  %v6.addr = alloca i32, align 4
  store i32 %v1, ptr %v1.addr, align 4
  store i32 %v2, ptr %v2.addr, align 4
  store i32 %v3, ptr %v3.addr, align 4
  store i32 %v4, ptr %v4.addr, align 4
  store i32 %v5, ptr %v5.addr, align 4
  store i32 %v6, ptr %v6.addr, align 4
  ret void
}

;; Ensure that functions with greater than 7 register arguments and no stack arguments are assigned arity=7
define dso_local void @f11(i32 noundef %v1, i32 noundef %v2, i32 noundef %v3, i32 noundef %v4, i32 noundef %v5, i32 noundef %v6, i32 noundef %v7, i32 noundef %v8) #0 !kcfi_type !6 {
; ASM-LABEL: f11:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    movl %edi, -{{[0-9]+}}(%rsp)
; ASM-NEXT:    movl %esi, -{{[0-9]+}}(%rsp)
; ASM-NEXT:    movl %edx, -{{[0-9]+}}(%rsp)
; ASM-NEXT:    movl %ecx, -{{[0-9]+}}(%rsp)
; ASM-NEXT:    movl %r8d, -{{[0-9]+}}(%rsp)
; ASM-NEXT:    movl %r9d, -{{[0-9]+}}(%rsp)
; ASM-NEXT:    retq
; ISEL-LABEL: name: f11
; ISEL: bb.0.entry:
; ISEL-NEXT:   liveins: $edi, $esi, $edx, $ecx, $r8d, $r9d
; ISEL-NEXT: {{  $}}
; ISEL-NEXT:   [[COPY:%[0-9]+]]:gr32 = COPY $r9d
; ISEL-NEXT:   [[COPY1:%[0-9]+]]:gr32 = COPY $r8d
; ISEL-NEXT:   [[COPY2:%[0-9]+]]:gr32 = COPY $ecx
; ISEL-NEXT:   [[COPY3:%[0-9]+]]:gr32 = COPY $edx
; ISEL-NEXT:   [[COPY4:%[0-9]+]]:gr32 = COPY $esi
; ISEL-NEXT:   [[COPY5:%[0-9]+]]:gr32 = COPY $edi
; ISEL-NEXT:   MOV32mr %stack.0.v1.addr, 1, $noreg, 0, $noreg, [[COPY5]] :: (store (s32) into %ir.v1.addr)
; ISEL-NEXT:   MOV32mr %stack.1.v2.addr, 1, $noreg, 0, $noreg, [[COPY4]] :: (store (s32) into %ir.v2.addr)
; ISEL-NEXT:   MOV32mr %stack.2.v3.addr, 1, $noreg, 0, $noreg, [[COPY3]] :: (store (s32) into %ir.v3.addr)
; ISEL-NEXT:   MOV32mr %stack.3.v4.addr, 1, $noreg, 0, $noreg, [[COPY2]] :: (store (s32) into %ir.v4.addr)
; ISEL-NEXT:   MOV32mr %stack.4.v5.addr, 1, $noreg, 0, $noreg, [[COPY1]] :: (store (s32) into %ir.v5.addr)
; ISEL-NEXT:   MOV32mr %stack.5.v6.addr, 1, $noreg, 0, $noreg, [[COPY]] :: (store (s32) into %ir.v6.addr)
; ISEL-NEXT:   RET 0
;
; KCFI-LABEL: name: f11
; KCFI: bb.0.entry:
; KCFI-NEXT:   liveins: $ecx, $edi, $edx, $esi, $r8d, $r9d
; KCFI-NEXT: {{  $}}
; KCFI-NEXT:   MOV32mr $rsp, 1, $noreg, -4, $noreg, killed renamable $edi :: (store (s32) into %ir.v1.addr)
; KCFI-NEXT:   MOV32mr $rsp, 1, $noreg, -8, $noreg, killed renamable $esi :: (store (s32) into %ir.v2.addr)
; KCFI-NEXT:   MOV32mr $rsp, 1, $noreg, -12, $noreg, killed renamable $edx :: (store (s32) into %ir.v3.addr)
; KCFI-NEXT:   MOV32mr $rsp, 1, $noreg, -16, $noreg, killed renamable $ecx :: (store (s32) into %ir.v4.addr)
; KCFI-NEXT:   MOV32mr $rsp, 1, $noreg, -20, $noreg, killed renamable $r8d :: (store (s32) into %ir.v5.addr)
; KCFI-NEXT:   MOV32mr $rsp, 1, $noreg, -24, $noreg, killed renamable $r9d :: (store (s32) into %ir.v6.addr)
; KCFI-NEXT:   RET64
entry:
  %v1.addr = alloca i32, align 4
  %v2.addr = alloca i32, align 4
  %v3.addr = alloca i32, align 4
  %v4.addr = alloca i32, align 4
  %v5.addr = alloca i32, align 4
  %v6.addr = alloca i32, align 4
  %v7.addr = alloca i32, align 4
  %v8.addr = alloca i32, align 4
  store i32 %v1, ptr %v1.addr, align 4
  store i32 %v2, ptr %v2.addr, align 4
  store i32 %v3, ptr %v3.addr, align 4
  store i32 %v4, ptr %v4.addr, align 4
  store i32 %v5, ptr %v5.addr, align 4
  store i32 %v6, ptr %v6.addr, align 4
  store i32 %v7, ptr %v7.addr, align 4
  store i32 %v8, ptr %v8.addr, align 4
  ret void
}

;; Ensure that floating-point values are not counted toward the arity
define dso_local void @f12(i32 noundef %v1, i32 noundef %v2, float noundef %v3, double noundef %v4, float noundef %v5, i32 noundef %v6, i32 noundef %v7, i32 noundef %v8) #0 !kcfi_type !7 {
; ASM-LABEL: f12:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    movl %edi, -{{[0-9]+}}(%rsp)
; ASM-NEXT:    movl %esi, -{{[0-9]+}}(%rsp)
; ASM-NEXT:    movss %xmm0, -{{[0-9]+}}(%rsp)
; ASM-NEXT:    movsd %xmm1, -{{[0-9]+}}(%rsp)
; ASM-NEXT:    movss %xmm2, -{{[0-9]+}}(%rsp)
; ASM-NEXT:    movl %edx, -{{[0-9]+}}(%rsp)
; ASM-NEXT:    movl %ecx, -{{[0-9]+}}(%rsp)
; ASM-NEXT:    movl %r8d, -{{[0-9]+}}(%rsp)
; ASM-NEXT:    retq
; ISEL-LABEL: name: f12
; ISEL: bb.0.entry:
; ISEL-NEXT:   liveins: $edi, $esi, $xmm0, $xmm1, $xmm2, $edx, $ecx, $r8d
; ISEL-NEXT: {{  $}}
; ISEL-NEXT:   [[COPY:%[0-9]+]]:gr32 = COPY $r8d
; ISEL-NEXT:   [[COPY1:%[0-9]+]]:gr32 = COPY $ecx
; ISEL-NEXT:   [[COPY2:%[0-9]+]]:gr32 = COPY $edx
; ISEL-NEXT:   [[COPY3:%[0-9]+]]:fr32 = COPY $xmm2
; ISEL-NEXT:   [[COPY4:%[0-9]+]]:fr64 = COPY $xmm1
; ISEL-NEXT:   [[COPY5:%[0-9]+]]:fr32 = COPY $xmm0
; ISEL-NEXT:   [[COPY6:%[0-9]+]]:gr32 = COPY $esi
; ISEL-NEXT:   [[COPY7:%[0-9]+]]:gr32 = COPY $edi
; ISEL-NEXT:   MOV32mr %stack.0.v1.addr, 1, $noreg, 0, $noreg, [[COPY7]] :: (store (s32) into %ir.v1.addr)
; ISEL-NEXT:   MOV32mr %stack.1.v2.addr, 1, $noreg, 0, $noreg, [[COPY6]] :: (store (s32) into %ir.v2.addr)
; ISEL-NEXT:   MOVSSmr %stack.2.v3.addr, 1, $noreg, 0, $noreg, [[COPY5]] :: (store (s32) into %ir.v3.addr)
; ISEL-NEXT:   MOVSDmr %stack.3.v4.addr, 1, $noreg, 0, $noreg, [[COPY4]] :: (store (s64) into %ir.v4.addr, align 4)
; ISEL-NEXT:   MOVSSmr %stack.4.v5.addr, 1, $noreg, 0, $noreg, [[COPY3]] :: (store (s32) into %ir.v5.addr)
; ISEL-NEXT:   MOV32mr %stack.5.v6.addr, 1, $noreg, 0, $noreg, [[COPY2]] :: (store (s32) into %ir.v6.addr)
; ISEL-NEXT:   MOV32mr %stack.6.v7.addr, 1, $noreg, 0, $noreg, [[COPY1]] :: (store (s32) into %ir.v7.addr)
; ISEL-NEXT:   MOV32mr %stack.7.v8.addr, 1, $noreg, 0, $noreg, [[COPY]] :: (store (s32) into %ir.v8.addr)
; ISEL-NEXT:   RET 0
;
; KCFI-LABEL: name: f12
; KCFI: bb.0.entry:
; KCFI-NEXT:   liveins: $ecx, $edi, $edx, $esi, $xmm0, $xmm1, $xmm2, $r8d
; KCFI-NEXT: {{  $}}
; KCFI-NEXT:   MOV32mr $rsp, 1, $noreg, -12, $noreg, killed renamable $edi :: (store (s32) into %ir.v1.addr)
; KCFI-NEXT:   MOV32mr $rsp, 1, $noreg, -16, $noreg, killed renamable $esi :: (store (s32) into %ir.v2.addr)
; KCFI-NEXT:   MOVSSmr $rsp, 1, $noreg, -20, $noreg, killed renamable $xmm0 :: (store (s32) into %ir.v3.addr)
; KCFI-NEXT:   MOVSDmr $rsp, 1, $noreg, -8, $noreg, killed renamable $xmm1 :: (store (s64) into %ir.v4.addr, align 4)
; KCFI-NEXT:   MOVSSmr $rsp, 1, $noreg, -24, $noreg, killed renamable $xmm2 :: (store (s32) into %ir.v5.addr)
; KCFI-NEXT:   MOV32mr $rsp, 1, $noreg, -28, $noreg, killed renamable $edx :: (store (s32) into %ir.v6.addr)
; KCFI-NEXT:   MOV32mr $rsp, 1, $noreg, -32, $noreg, killed renamable $ecx :: (store (s32) into %ir.v7.addr)
; KCFI-NEXT:   MOV32mr $rsp, 1, $noreg, -36, $noreg, killed renamable $r8d :: (store (s32) into %ir.v8.addr)
; KCFI-NEXT:   RET64
entry:
  %v1.addr = alloca i32, align 4
  %v2.addr = alloca i32, align 4
  %v3.addr = alloca float, align 4
  %v4.addr = alloca double, align 4
  %v5.addr = alloca float, align 4
  %v6.addr = alloca i32, align 4
  %v7.addr = alloca i32, align 4
  %v8.addr = alloca i32, align 4
  store i32 %v1, ptr %v1.addr, align 4
  store i32 %v2, ptr %v2.addr, align 4
  store float %v3, ptr %v3.addr, align 4
  store double %v4, ptr %v4.addr, align 4
  store float %v5, ptr %v5.addr, align 4
  store i32 %v6, ptr %v6.addr, align 4
  store i32 %v7, ptr %v7.addr, align 4
  store i32 %v8, ptr %v8.addr, align 4
  ret void
}

attributes #0 = { "target-features"="+retpoline-indirect-branches,+retpoline-indirect-calls" }

!llvm.module.flags = !{!0, !8}
!0 = !{i32 4, !"kcfi", i32 1}
!1 = !{i32 12345678}
!2 = !{i32 4196274163}
!3 = !{i32 98693133}
!4 = !{i32 199571451}
!5 = !{i32 1046421190}
!6 = !{i32 1342488295}
!7 = !{i32 2253188362}
!8 = !{i32 4, !"kcfi-arity", i32 1}
