; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -relocation-model pic < %s | FileCheck %s
target datalayout = "e-m:e-p:32:32-f64:32:64-f80:32-n8:16:32-S128"
target triple = "i386-unknown-freebsd"

@x1 = external thread_local global i32, align 4

define void @x3() #0 {
; CHECK-LABEL: x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushl %ebx
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    pushl %esi
; CHECK-NEXT:    .cfi_def_cfa_offset 12
; CHECK-NEXT:    .cfi_offset %esi, -12
; CHECK-NEXT:    .cfi_offset %ebx, -8
; CHECK-NEXT:    calll .L0$pb
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4
; CHECK-NEXT:  .L0$pb:
; CHECK-NEXT:    popl %esi
; CHECK-NEXT:    .cfi_adjust_cfa_offset -4
; CHECK-NEXT:  .Ltmp0:
; CHECK-NEXT:    addl $_GLOBAL_OFFSET_TABLE_+(.Ltmp0-.L0$pb), %esi
; CHECK-NEXT:    movl %esi, %ebx
; CHECK-NEXT:    leal x1@TLSGD(,%ebx), %eax
; CHECK-NEXT:    calll ___tls_get_addr@PLT
; CHECK-NEXT:    cmpl $92, (%eax)
; CHECK-NEXT:    je .LBB0_2
; CHECK-NEXT:  # %bb.1: # %sw.epilog
; CHECK-NEXT:    popl %esi
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    popl %ebx
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    retl
; CHECK-NEXT:  .LBB0_2: # %sw.bb
; CHECK-NEXT:    .cfi_def_cfa_offset 12
; CHECK-NEXT:    movl %esi, %ebx
; CHECK-NEXT:    pushl $0
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4
; CHECK-NEXT:    calll x2@PLT
entry:
  %0 = load i32, ptr @x1, align 4
  %cond = icmp eq i32 %0, 92
  br i1 %cond, label %sw.bb, label %sw.epilog

sw.bb:                                            ; preds = %entry
  call void @x2(ptr null)
  unreachable

sw.epilog:                                        ; preds = %entry
  ret void
}

declare void @x2(ptr)

attributes #0 = { optsize }

