; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=i386-unknown-freebsd -enable-misched -relocation-model=pic | FileCheck %s

@c = external local_unnamed_addr global ptr

declare i32 @fn2() local_unnamed_addr

declare i32 @fn3() local_unnamed_addr

define noundef i32 @fn4() #0 {
; CHECK-LABEL: fn4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushl %ebp
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    .cfi_offset %ebp, -8
; CHECK-NEXT:    movl %esp, %ebp
; CHECK-NEXT:    .cfi_def_cfa_register %ebp
; CHECK-NEXT:    pushl %ebx
; CHECK-NEXT:    pushl %edi
; CHECK-NEXT:    pushl %esi
; CHECK-NEXT:    pushl %eax
; CHECK-NEXT:    .cfi_offset %esi, -20
; CHECK-NEXT:    .cfi_offset %edi, -16
; CHECK-NEXT:    .cfi_offset %ebx, -12
; CHECK-NEXT:    calll .L0$pb
; CHECK-NEXT:  .L0$pb:
; CHECK-NEXT:    popl %ebx
; CHECK-NEXT:  .Ltmp0:
; CHECK-NEXT:    addl $_GLOBAL_OFFSET_TABLE_+(.Ltmp0-.L0$pb), %ebx
; CHECK-NEXT:    movl fn4@GOT(%ebx), %esi
; CHECK-NEXT:    movl (%esi), %edx
; CHECK-NEXT:    movl c@GOT(%ebx), %eax
; CHECK-NEXT:    movl (%eax), %edi
; CHECK-NEXT:    testl %edi, %edi
; CHECK-NEXT:    jne .LBB0_3
; CHECK-NEXT:  # %bb.1: # %if.then.g
; CHECK-NEXT:    cmpl $0, 1
; CHECK-NEXT:    js .LBB0_2
; CHECK-NEXT:  .LBB0_3: # %if.end3.g
; CHECK-NEXT:    testl %edx, %edx
; CHECK-NEXT:    je .LBB0_7
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB0_4: # %while.body.g
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; CHECK-NEXT:    pushl %edx
; CHECK-NEXT:    pushl %esi
; CHECK-NEXT:    pushl %edi
; CHECK-NEXT:    calll fn3@PLT
; CHECK-NEXT:    addl $12, %esp
; CHECK-NEXT:    testl %eax, %eax
; CHECK-NEXT:    js .LBB0_5
; CHECK-NEXT:  # %bb.6: # %if.end8.g
; CHECK-NEXT:    # in Loop: Header=BB0_4 Depth=1
; CHECK-NEXT:    addl $4, %esi
; CHECK-NEXT:    movl $0, 4(%edi)
; CHECK-NEXT:    movl $0, (%edi)
; CHECK-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; CHECK-NEXT:    incl %edx
; CHECK-NEXT:    jne .LBB0_4
; CHECK-NEXT:    jmp .LBB0_7
; CHECK-NEXT:  .LBB0_5: # %if.then6.g
; CHECK-NEXT:    pushl $0
; CHECK-NEXT:    calll fn2@PLT
; CHECK-NEXT:    addl $4, %esp
; CHECK-NEXT:    jmp .LBB0_7
; CHECK-NEXT:  .LBB0_2: # %if.then2.g
; CHECK-NEXT:    movl 0, %eax
; CHECK-NEXT:  .LBB0_7: # %f.exit
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    addl $4, %esp
; CHECK-NEXT:    popl %esi
; CHECK-NEXT:    popl %edi
; CHECK-NEXT:    popl %ebx
; CHECK-NEXT:    popl %ebp
; CHECK-NEXT:    .cfi_def_cfa %esp, 4
; CHECK-NEXT:    retl
entry:
  %tmp0 = load i32, ptr @fn4, align 4
  %tmp1 = load ptr, ptr @c, align 4
  %cmp.g = icmp eq ptr %tmp1, null
  br i1 %cmp.g, label %if.then.g, label %if.end3.g

if.then.g:                                        ; preds = %entry
  %tmp2 = load i32, ptr inttoptr (i32 1 to ptr), align 4
  %cmp1.g = icmp slt i32 %tmp2, 0
  br i1 %cmp1.g, label %if.then2.g, label %if.end3.g

if.then2.g:                                       ; preds = %if.then.g
  %.g = load volatile i32, ptr null, align 2147483648
  br label %f.exit

if.end3.g:                                        ; preds = %if.then.g, %entry
  %h.i.g = icmp eq i32 %tmp0, 0
  br i1 %h.i.g, label %f.exit, label %while.body.g

while.body.g:                                     ; preds = %if.end3.g, %if.end8.g
  %buff.addr.019.g = phi ptr [ %incdec.ptr.g, %if.end8.g ], [ @fn4, %if.end3.g ]
  %g.addr.018.g = phi i32 [ %dec.g, %if.end8.g ], [ %tmp0, %if.end3.g ]
  %call4.g = tail call i32 @fn3(ptr %tmp1, ptr %buff.addr.019.g, i32 %g.addr.018.g)
  %cmp5.g = icmp slt i32 %call4.g, 0
  br i1 %cmp5.g, label %if.then6.g, label %if.end8.g

if.then6.g:                                       ; preds = %while.body.g
  %call7.g = tail call i32 @fn2(ptr null)
  br label %f.exit

if.end8.g:                                        ; preds = %while.body.g
  %dec.g = add i32 %g.addr.018.g, 1
  %incdec.ptr.g = getelementptr i32, ptr %buff.addr.019.g, i32 1
  store i64 0, ptr %tmp1, align 4
  %h.not.g = icmp eq i32 %dec.g, 0
  br i1 %h.not.g, label %f.exit, label %while.body.g

f.exit:                                           ; preds = %if.end8.g, %if.then6.g, %if.end3.g, %if.then2.g
  ret i32 0
}

attributes #0 = { "frame-pointer"="all" "tune-cpu"="generic" }
